#!/bin/python
#
# GAMBIT: Global and Modular BSM Inference Tool
#*********************************************
# \file
#
#  Functor type harvesting script
#  Generates all_functor_types.hpp
#  
#  This script reads through all the headers
#  listed in Core/include/module_rollcall.hpp
#  and harvests the types of every functor
#  that GAMBIT will try to compile. These
#  are needed to generate the default (virtual) 
#  'print' functions in the base printer class
#  (see Utils/include/printers.hpp)  
#
#*********************************************
#
#  Authors (add name and date if you modify):
#   
#  \author Ben Farmer 
#          (ben.farmer@gmail.com)
#    \date 2013 Sep 
#
#  \author Pat Scott 
#          (patscott@physics.mcgill.ca)
#    \date 2013 Oct 
#
#*********************************************
import os
import re
import datetime

# Harvest header filename from an include statement
def addifheader(line,headerset):
    splitline = line.split()
    if len(splitline)>1 and splitline[0]=="#include":
        #dig the file name out of the enclosing <> or "" 
        split2 = re.split('"|<|>',splitline[1])
        headerset.add(split2[1])

# Harvest type from a START_FUNCTION macro call
def addiffunctormacro(line,typeset):
    splitline = re.split('\(|\)|,',line)
    if len(splitline)>0 and splitline[0].strip()=="START_FUNCTION":
        typeset.add(splitline[1])


# List of headers NOT to search (things we know are not module rollcall headers, but are included in module_rollcall.hpp)
exclude_header=set(["module_macros_incore.hpp"])
# List of types NOT to return (things we know are not printable, but can appear in START_FUNCTION calls)
exclude_type=set(["void"])

# Harvest the list of rollcall headers to be searched
# FIXME this should be made recursive, in case someone
# has so many rollcall definitions they put them in
# multiple files
headers=set()
with open("Core/include/module_rollcall.hpp") as f:
    for line in f.readlines():
        addifheader(line,headers)        

# Remove excluded headers from the set
headers.difference_update(exclude_header)

# Determine the paths of the harvested headers    
fullheaders=[]
for header in headers:
    # Locate the header in the GAMBIT directory structure...
    # (we should technically search all the include paths in the make file; could pass these in to this script)
    for root,dirs,files in os.walk("."):
        for name in files:
            if name==header:
                fullheaders+=[os.path.join(root,name)]
    
# Search through headers and look for macro calls which create 'module_functor's     
types=set(["ModelParameters"]) #Manually add this one to avoid scanning through modelbit
for header in fullheaders:
    with open(header) as f:
        print "Scanning header {0}".format(header)
        for line in f.readlines():
            # Check for calls to functor creation macros, and harvest the types used.
            addiffunctormacro(line,types)

# Remove excluded types from the set
types.difference_update(exclude_type)

print "\nTypes harvested from headers:"
for t in types:
    print '   ',t

# Generate a c++ header containing the preprocessor sequence needed by Utils/include/printers.hpp, containing all the types we have harvested.

towrite = "\
//   GAMBIT: Global and Modular BSM Inference Tool\n\
//   *********************************************\n\
///  \\file                                       \n\
///                                               \n\
///  Automatically generated preprocessor sequence\n\
///  of functor types.                            \n\
///                                               \n\
///  This file was automatically generated by     \n\
///  functor_type_harvester.py. Do not modify.    \n\
///  The content is harvested from the rollcall   \n\
///  headers registered in module_rollcall.hpp    \n\
///                                               \n\
///  *********************************************\n\
///                                               \n\
///  Authors (add name and date if you modify):   \n\
///                                               \n\
///  \\author The GAMBIT Collaboration            \n\
///  \date "+datetime.datetime.now().strftime("%I:%M%p on %B %d, %Y")+"\n\
///                                               \n\
///  *********************************************\n\
                                                  \n\
#ifndef __all_functor_types_hpp__                 \n\
#define __all_functor_types_hpp__                 \n\
                                                  \n\
#include \"types_rollcall.hpp\"                   \n\
                                                  \n\
// Automatically generated preprocessor sequence of types \n\
#define PRINTABLE_TYPES "
for t in types:
    towrite+='({0})'.format(t)
towrite+="\n\n#endif // defined __all_functor_types_hpp__\n"

with open("./Utils/include/all_functor_types.hpp","w") as f:
    f.write(towrite)

# Done!


