# simple makefile. 
#
# Lundberg 2011-Aug
# Pat Scott 2012-Nov
# Abram Krislock 2014-Jan
#
###
include makefile.common

ifndef CC
  CC = icc 
endif
LNFLAGS += -lstdc++ -rdynamic -ldl -lgfortran -lrt 

ifndef FC
  FC = ifort
endif
CCEXTRA= -pipe -pg 
