# simple makefile. 
#
# Lundberg 2011-Aug
# Pat Scott 2012-Nov+
# Abram Krislock 2014-Jan
#
###
include makefile.common

CC = g++ 
FC = gfortran
CCEXTRA= -pipe -pg -Wextra -g -Wfatal-errors
FMODULE = J
FEXTRA = -ffixed-line-length-none
