# simple makefile. 
#
# Lundberg 2011-Aug
# Pat Scott 2012-Nov
# Abram Krislock 2014-Jan
#
###
include makefile.common

CC = icc 
LNFLAGS += -lstdc++ -rdynamic -ldl -lgfortran -lrt 

FC = ifort
CCEXTRA= -pipe -pg 
