//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of backend types.  
///                                               
///  This file was automatically generated by     
///  backend_harvester.py. Do not modify.         
///                                               
///  Do not add to this if you want to add new    
///  types associated with a new (or old) backend.
///  Just add your backend type headers to the    
///  directory tree in the right place, and rest  
///  assured that backend_harvester.py will make  
///  sure they end up here.                       
///                                               
///  Where is 'the right place'?                
///  -Regular backend types: in a new header file 
///    Backends/include/backend_types/X_types.hpp 
///   where X is the name of the backend.         
///  -When the types you want to add are a result 
///   of running BOSS: add the directory created  
///   by BOSS as                                  
///    Backends/include/backend_types/X/          
///   where X is the name of the backend.  BOSS   
///   will actually do this itself automatically  
///   in some circumstances.                      
///                                               
///  *********************************************
///                                               
///  Authors (add name and date if you modify):   
///                                               
///  \author The GAMBIT Collaboration            
///  \date 02:19AM on February 05, 2015
///                                               
///  *********************************************
                                                  
#ifndef __backend_types_rollcall_hpp__            
#define __backend_types_rollcall_hpp__            
                                                  
// Macro definitions                              
#include "type_macros.hpp"                      
                                                  
// Regular backend type definitions.              
#include "backend_types/libfirst.hpp"
#include "backend_types/libFarrayTest.hpp"
#include "backend_types/FastSim.hpp"
#include "backend_types/SuperIso.hpp"
#include "backend_types/micrOMEGAs.hpp"
#include "backend_types/SUSYHIT.hpp"
#include "backend_types/DarkSUSY.hpp"
#include "backend_types/FeynHiggs.hpp"

// BOSSed backend type definitions.
#include "backend_types/BOSSMinimalExample_1_1/loaded_types.hpp"
#include "backend_types/Pythia_8_186/loaded_types.hpp"
#include "backend_types/BOSSMinimalExample_1_2/loaded_types.hpp"
#include "backend_types/BOSSMinimalExample_1_0/loaded_types.hpp"

#endif // defined __backend_types_rollcall_hpp__
