//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of GAMBIT model    
///  types.                                       
///                                               
///  This file was automatically generated by     
///  model_harvester.py. Do not modify.           
///                                               
///  Do not add to this if you want to add new    
///  types associated with a new (or old) model.  
///  Just add your model type header to           
///  Models/include/model_types and rest assured  
///  that model_harvester.py will make sure it    
///  ends up here.                                
///                                               
///  *********************************************
///                                               
///  Authors (add name and date if you modify):   
///                                               
///  \author The GAMBIT Collaboration            
///  \date 07:42AM on February 05, 2015
///                                               
///  *********************************************
                                                  
#ifndef __model_types_rollcall_hpp__              
#define __model_types_rollcall_hpp__              
                                                  
// Automatically-generated list of model types.   

#endif // defined __model_types_rollcall_hpp__
