//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of GAMBIT models.  
///                                               
///  This file was automatically generated by     
///  model_harvester.py. Do not modify.           
///                                               
///  Do not add to this if you want to add a new  
///  model -- just add your model header to       
///  Models/include/models and rest assured that  
///  model_harvester.py will make sure it ends    
///  up here.                                     
///                                               
///  *********************************************
///                                               
///  Authors (add name and date if you modify):   
///                                               
///  \author The GAMBIT Collaboration            
///  \date 07:42AM on February 05, 2015
///                                               
///  *********************************************
                                                  
#ifndef __model_rollcall_hpp__                    
#define __model_rollcall_hpp__                    
                                                  
// Include the model macro definitions            
#include "model_macros.hpp"                     
                                                  
// Automatically-generated list of models.        
#include "models/extraCMSSM.hpp"
#include "models/demo.hpp"
#include "models/CMSSM.hpp"
#include "models/SingletDM.hpp"
#include "models/MSSM78atMGUT.hpp"
#include "models/MSSM78atQ.hpp"
#include "models/MSSM25atQ.hpp"

#endif // defined __model_rollcall_hpp__
