//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of GAMBIT models.  
///                                               
///  This file was automatically generated by     
///  printer_harvester.py. Do not modify.         
///                                               
///  Do not add to this if you want to add a new  
///  printer -- just add your printer header to   
///  Printers/include/gambit/Printers/printers    
///  and rest assured that printer_harvester.py   
///  will make sure it ends up here.              
///                                               
///  *********************************************
///                                               
///  Authors (add name and date if you modify):   
///                                               
///  \author The GAMBIT Collaboration            
///  \date 06:01PM on May 28, 2015
///                                               
///  *********************************************
                                                  
#ifndef __printer_rollcall_hpp__                  
#define __printer_rollcall_hpp__                  
                                                  
// Automatically-generated list of printers.      
#include "include/gambit/Printers/printers/ostreamprinter.hpp"
#include "include/gambit/Printers/printers/asciiprinter.hpp"

#endif // defined __printer_rollcall_hpp__
