//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Automatically generated preprocessor sequence
///  of functor types.                            
///                                               
///  This file was automatically generated by     
///  module_harvester.py. Do not modify.          
///  The content is harvested from the rollcall   
///  headers registered in module_rollcall.hpp    
///  and the types registered in                  
///  types_rollcall.hpp.                          
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 07:42AM on February 05, 2015
///                                               
///  *********************************************
                                                  
#ifndef __all_functor_types_hpp__                 
#define __all_functor_types_hpp__                 
                                                  
#include "types_rollcall.hpp"                   
                                                  
// Automatically generated preprocessor sequence of types 
#define PRINTABLE_TYPES (Gambit::DarkBit::simpleHistContainter)(Gambit::DarkBit::stringFunkMap)(Gambit::DarkBit::DD_couplings)(int)(shared_ptr<Gambit::ColliderBit::DelphesBase>)(DarkBit::nuyield_functype)(std::vector<std::string>)(ExampleBit_A::singleprec)(DarkBit::fptr_dd)(Gambit::DarkBit::DecayChain::ChainContainer)(Gambit::DarkBit::stringIntMap)(parameters)(Gambit::DarkBit::SimYieldTable)(eaSLHA)(bool)(Pythia8::Event)(Gambit::DarkBit::RD_spectrum_type)(shared_ptr<Gambit::ColliderBit::BuckFastBase>)(fptr)(HEPUtils::Event)(shared_ptr<Gambit::ColliderBit::PythiaBase>)(std::string)(std::vector<double>)(Spectrum*)(Gambit::DarkBit::TH_resonances_thresholds)(X)(Gambit::DarkBit::DecayChain::DecayTable)(Gambit::DarkBit::TH_ProcessCatalog)(DecayTable)(double)(DarkBit::nudata)(DecayTable::Entry)(ModelParameters)(Funk::Funk)(Gambit::DarkBit::mutableFinalStateContainer)(ColliderBit::ColliderLogLikes)(ColliderBit::AnalysisPointerVector)

#endif // defined __all_functor_types_hpp__
