//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Automatically generated preprocessor sequence
///  of functor types.                            
///                                               
///  This file was automatically generated by     
///  functor_type_harvester.py. Do not modify.    
///  The content is harvested from the rollcall   
///  headers registered in module_rollcall.hpp    
///  and the types registered in                  
///  types_rollcall.hpp.                          
///                                               
///  *********************************************
///                                               
///  Authors (add name and date if you modify):   
///                                               
///  \author The GAMBIT Collaboration            
///  \date 03:12PM on October 31, 2014
///                                               
///  *********************************************
                                                  
#ifndef __all_functor_types_hpp__                 
#define __all_functor_types_hpp__                 
                                                  
#include "types_rollcall.hpp"                   
                                                  
// Automatically generated preprocessor sequence of types 
#define PRINTABLE_TYPES (Gambit::DarkBit::DD_couplings)(int)(Gambit::BF::BFptr)(Py8SLHA)(DarkBit::nuyield_functype)(DarkBit::RDspectype)(DarkBit::fptr_dd)(DarkBit::RDrestype)(std::vector<double>)(HEP_Simple_Lib::Event)(parameters)(eaSLHA)(MSSMSpec*)(fptr)(std::string)(Spectrum*)(Gambit::DarkBit::TH_ProcessCatalog)(double)(DarkBit::nudata)(ModelParameters)(ExampleBit_A::singleprec)

#endif // defined __all_functor_types_hpp__
