//  GAMBIT: Global and Modular BSM Inference Tool
//  *********************************************
///  \file
///
///  Copies of boost headers that are required
///  but that may be too recent to be present
///  on the user's machine.
///
///  *********************************************
///  Boost Software License - Version 1.0 - August 17th, 2003
///  
///  Permission is hereby granted, free of charge, to any person or organization
///  obtaining a copy of the software and accompanying documentation covered by
///  this license (the "Software") to use, reproduce, display, distribute,
///  execute, and transmit the Software, and to prepare derivative works of the
///  Software, and to permit third-parties to whom the Software is furnished to
///  do so, all subject to the following:
///  
///  The copyright notices in the Software and this entire statement, including
///  the above license grant, this restriction and the following disclaimer,
///  must be included in all copies of the Software, in whole or in part, and
///  all derivative works of the Software, unless such copies or derivative
///  works are solely in the form of machine-executable object code generated by
///  a source language processor.
///  
///  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
///  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
///  FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
///  SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
///  FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
///  ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
///  DEALINGS IN THE SOFTWARE.
///  *********************************************

# if GAMBIT_CONFIG_FLAG_boost_is_at_least_v1_49
#   include <boost/preprocessor/variadic/size.hpp>
# else

/// BOOST_PP_VARIADIC_SIZE; Returns the number of arguments passed.
/// 
/// ****************************************************************************
///                                                                           
///      (C) Copyright Edward Diener 2011.                                    
///      (C) Copyright Paul Mensonides 2011.                                  
///      Distributed under the Boost Software License, Version 1.0. (See      
///      accompanying file LICENSE_1_0.txt or copy at                         
///      http://www.boost.org/LICENSE_1_0.txt)                                
///                                                                           
/// ****************************************************************************
///
/// See http://www.boost.org for most recent version.

# ifndef BOOST_PREPROCESSOR_VARIADIC_SIZE_HPP
# define BOOST_PREPROCESSOR_VARIADIC_SIZE_HPP

# include <boost/preprocessor/cat.hpp>
# include <boost/preprocessor/config/config.hpp>

#    if BOOST_PP_VARIADICS_MSVC
#        define BOOST_PP_VARIADIC_SIZE(...) BOOST_PP_CAT(BOOST_PP_VARIADIC_SIZE_I(__VA_ARGS__, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1,),)
#    else
#        define BOOST_PP_VARIADIC_SIZE(...) BOOST_PP_VARIADIC_SIZE_I(__VA_ARGS__, 64, 63, 62, 61, 60, 59, 58, 57, 56, 55, 54, 53, 52, 51, 50, 49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1,)
#    endif
#    define BOOST_PP_VARIADIC_SIZE_I(e0, e1, e2, e3, e4, e5, e6, e7, e8, e9, e10, e11, e12, e13, e14, e15, e16, e17, e18, e19, e20, e21, e22, e23, e24, e25, e26, e27, e28, e29, e30, e31, e32, e33, e34, e35, e36, e37, e38, e39, e40, e41, e42, e43, e44, e45, e46, e47, e48, e49, e50, e51, e52, e53, e54, e55, e56, e57, e58, e59, e60, e61, e62, e63, size, ...) size
# endif

# endif
