//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of GAMBIT module   
///  types.                                       
///                                               
///  This file was automatically generated by     
///  module_harvester.py. Do not modify.          
///                                               
///  Do not add to this if you want to add new    
///  types associated with a new (or old) module. 
///  Just add your model type header as           
///  XBit/include/XBit_types.hpp and rest assured 
///  that module_harvester.py will make sure it   
///  ends up here.                                
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 12:48AM on February 05, 2015
///                                               
///  *********************************************
                                                  
#ifndef __module_types_rollcall_hpp__             
#define __module_types_rollcall_hpp__             
                                                  
// Automatically-generated list of module types.  
#include "ExampleBit_A_types.hpp"
#include "DarkBit_types.hpp"
#include "DecayBit_types.hpp"
#include "EWPOBit_types.hpp"

#endif // defined __module_types_rollcall_hpp__
