//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file
///
///  Rollcall header for module SpecBit
///
///  These functions link ModelParameters to 
///  Spectrum objects in various ways.
///
///  *********************************************
///
///  Authors (add name and date if you modify):
///
///  \author Ben Farmer
///          (benjamin.farmer@fysik.su.se)
///    \date 2014 Sep - Dec, 2015 Jan - Mar
///  
///  *********************************************

#ifndef __SpecBit_rollcall_hpp__
#define __SpecBit_rollcall_hpp__

#define MODULE SpecBit
START_MODULE

  /// Produce an SMInputs object (SLHA2 conventions)
  // i.e. provide Standard Model parameters in SLHA2 input conventions
  #define CAPABILITY SMINPUTS
  START_CAPABILITY

    #define FUNCTION get_SMINPUTS            
    START_FUNCTION(SMInputs)                  
    ALLOW_MODELS(StandardModel_SLHA2)
    #undef FUNCTION

  #undef CAPABILITY


  /// @{ Functions to supply particle spectra in various forms
  
  // This capability supplies the physical mass spectrum of the MSSM plus running
  // parameters in the DRbar scheme. This can be generated by many different 
  // constrained models with various boundary conditions, or defined directly.
  #define CAPABILITY MSSM_spectrum   
  START_CAPABILITY                          

    // ==========================
    // GUT MSSM parameterisations 
    // (CMSSM and its various non-universal generalisations)    
 
    /// Get MSSM spectrum from CMSSM boundary conditions
    //  The type, (const) Spectrum, is a class containing two SubSpectrum* members and an SMInputs
    //  member. The SubSpectrum* members point to a "UV" Spectrum object (the MSSM) and an
    //  "LE" (low energy) Spectrum object (an effective Standard Model description), while SMInputs
    //  contains the information in the SMINPUTS block defined by SLHA2.
    #define FUNCTION get_CMSSM_spectrum            
    START_FUNCTION(const Spectrum*)                  
    ALLOW_MODELS(CMSSM)
    DEPENDENCY(SMINPUTS, SMInputs) // Need SLHA2 SMINPUTS to set up spectrum generator
    #undef FUNCTION

    // FlexibleSUSY compatible maximal CMSSM generalisation (MSSM with GUT boundary conditions) 
    #define FUNCTION get_MSSMatMGUT_spectrum
    START_FUNCTION(const Spectrum*)                  
    ALLOW_MODELS(MSSM78atMGUT)
    DEPENDENCY(SMINPUTS, SMInputs) // Need SLHA2 SMINPUTS to set up spectrum generator
    #undef FUNCTION

    // ============================== 
    // MSSM parameterised with input at (user-defined) scale Q 
    #define FUNCTION get_MSSMatQ_spectrum
    START_FUNCTION(const Spectrum*)                  
    ALLOW_MODELS(MSSM78atQ)
    DEPENDENCY(SMINPUTS, SMInputs) // Need SLHA2 SMINPUTS to set up spectrum generator
    #undef FUNCTION

    // ============================== 
    // MSSM spectrum retrieved from an SLHA file
    // Wraps it up in MSSMskeleton; i.e. no RGE running possible.
    // This is mainly for testing against benchmark points, but may be a useful last
    // resort for interacting with "difficult" spectrum generators.
    #define FUNCTION get_MSSM_spectrum_from_SLHAfile 
    START_FUNCTION(const Spectrum*)
    // Technically doesn't need a Model to work...
    // Could add some kind of dependency here, like on the input filename, to allow dependency
    // resolver to ignore it most of the time. 
    #undef FUNCTION
    
    // ==============================

    // Extract appropriate SubSpectrum* from Spectrum struct, while preserving the Capability
    #define FUNCTION get_MSSM_SubSpectrum_from_MSSM_Spectrum
    START_FUNCTION(const SubSpectrum*)
    DEPENDENCY(MSSM_spectrum, const Spectrum*)
    #undef FUNCTION

    // Get MSSM spectrum as an SLHAea object
    #define FUNCTION get_MSSM_spectrum_as_SLHAea
    START_FUNCTION(eaSLHA)                  
    DEPENDENCY(MSSM_spectrum, const SubSpectrum*)           // Takes a (pointer to a) SubSpectrum object and returns an eaSLHA object
    #undef FUNCTION

  #undef CAPABILITY

  // For testing only
  #define CAPABILITY test_MSSM_spectrum   
  START_CAPABILITY                          
    #define FUNCTION make_test_spectrum  // Get (pointer to) test MSSM spectrum
    START_FUNCTION(SubSpectrum*)
    #undef FUNCTION
  #undef CAPABILITY

  // Functions to changes the capability associated with a Spectrum object to "SM_spectrum"
  ///TODO: CURRENTLY THERE SEEMS TO BE A BUG WITH RETRIEVING THESE DEPENDENCIES! SWITCHING BACK TO OLD METHOD
  //QUICK_FUNCTION(SpecBit, SM_spectrum, NEW_CAPABILITY, convert_MSSM_to_SM,   Spectrum*, (), (MSSM_spectrum, Spectrum*))
  //QUICK_FUNCTION(MODULE, SM_spectrum, OLD_CAPABILITY, convert_NMSSM_to_SM,  Spectrum*, (), (NMSSM_spectrum, Spectrum*))
  //QUICK_FUNCTION(MODULE, SM_spectrum, OLD_CAPABILITY, convert_E6MSSM_to_SM, Spectrum*, (), (E6MSSM_spectrum, Spectrum*))

  // Note: QUICK_FUNCTION usage:
  // Arguments: MODULE, CAPABILITY, NEW_CAPABILITY_FLAG, FUNCTION, TYPE, (n x ALLOWED_MODEL), m x (DEPENDENCY, DEPENDENCY_TYPE)
  //            The last two arguments are optional, and n and m can be anything from 0 to 10.
  //
  // equivalent to:
  #define CAPABILITY SM_spectrum
  START_CAPABILITY                          
    // TODO: NOTE! I removed this because currently the string names don't quite match correctly and the MSSM version doesn't provide all the Standard Model pole masses.

    //  #define FUNCTION convert_MSSM_to_SM
    //  START_FUNCTION(const Spectrum*)
    //  DEPENDENCY(MSSM_spectrum, const Spectrum*)
    //  #undef FUNCTION 

    //  // etc. for other functions

    // Extract appropriate SubSpectrum* from Spectrum struct, starting from MSSM_spectrum
    #define FUNCTION get_SM_SubSpectrum_from_MSSM_Spectrum
    START_FUNCTION(const SubSpectrum*)
    DEPENDENCY(MSSM_spectrum, const Spectrum*)
    #undef FUNCTION

    // Create QedQcdWrapper version of Spectrum* from SMInputs structs
    #define FUNCTION get_QedQcd_spectrum
    START_FUNCTION(const SubSpectrum*)
    DEPENDENCY(SMINPUTS, SMInputs)
    #undef FUNCTION

  #undef CAPABILITY

  /// @}

  // 'Convenience' functions to retrieve certain particle properities in a simple format

  // #define CAPABILITY LSP_mass   // Supplies the mass of the lightest supersymmetric particle
  // START_CAPABILITY

  //   #define FUNCTION get_LSP_mass                      // Retrieves the LSP mass from a Spectrum object
  //   START_FUNCTION(double)                  
  //   DEPENDENCY(particle_spectrum, SpectrumPtr)            // Takes a Spectrum object and returns an eaSLHA object
  //   ALLOW_MODELS(MSSM24, CMSSM)
  //   #undef FUNCTION

  // #undef CAPABILITY
    

  /// TEST FUNCTIONS
  // Just some functions for testing SpecBit and Spectrum object components


  #define CAPABILITY specbit_tests1
  START_CAPABILITY
     #define FUNCTION specbit_test_func1
     START_FUNCTION(double)
     DEPENDENCY(MSSM_spectrum, const Spectrum*)
     #undef FUNCTION
  #undef CAPABILITY

  #define CAPABILITY specbit_tests2
  START_CAPABILITY
     #define FUNCTION specbit_test_func2
     START_FUNCTION(double)
     #undef FUNCTION
  #undef CAPABILITY

  #define CAPABILITY specbit_tests3
  START_CAPABILITY
     #define FUNCTION specbit_test_func3
     START_FUNCTION(double)
     DEPENDENCY(SM_spectrum, const SubSpectrum*)
     #undef FUNCTION
  #undef CAPABILITY

  #define CAPABILITY specbit_test_Spectrum
  START_CAPABILITY
     #define FUNCTION specbit_test_Spectrum
     START_FUNCTION(double)
     DEPENDENCY(MSSM_spectrum, const Spectrum*)
     DEPENDENCY(SM_spectrum, const SubSpectrum*)
   #undef FUNCTION
  #undef CAPABILITY


 #define CAPABILITY dump_spectrum_slha
 START_CAPABILITY
 
     #define FUNCTION dump_spectrum
     START_FUNCTION(double)
     DEPENDENCY(SM_spectrum, const SubSpectrum*)
     #undef FUNCTION

 #undef CAPABILITY


 #define CAPABILITY SpecBit_examples
 START_CAPABILITY

     #define FUNCTION exampleRead
     START_FUNCTION(bool)
     DEPENDENCY(MSSM_spectrum, const Spectrum*)
     #undef FUNCTION

 #undef CAPABILITY

#undef MODULE

#endif /* defined(__SpecBit_rollcall_hpp__) */



