# GAMBIT: Global and Modular BSM Inference Tool  
#************************************************
# \file                                         
#                                                
#  Cmake linking and rpath commands for GAMBIT.  
#                                                
#  This file has been automatically generated by 
#  locate_scanners.py.  Please do not modify.    
#                                                
#************************************************
#                                                
#  Authors:                                      
#                                                
#  \author The GAMBIT Collaboration             
#  \date 02:02AM on January 23, 2015
#                                               
#***********************************************
                                                
foreach(program ${uses_scannerbit})             
endforeach()