//
// Frontend header generated by BOSS for GAMBIT backend Pythia 8.212.
//

#include "gambit/Backends/backend_types/Pythia_8_212/identification.hpp"

LOAD_LIBRARY

// Functions
// Variables

// Initialisation function (dependencies)

// Convenience functions (registration)

// Initialisation function (definition)
BE_INI_FUNCTION{} END_BE_INI_FUNCTION

// Convenience functions (definitions)

// End
#include "gambit/Backends/backend_undefs.hpp"
