#! /usr/bin/env bash

BASEDIR=$PWD
cd ../../..  # to main modules dir

for i in $*; do
    IDIR=$BASEDIR/$i
    echo "Running GAMBIT in $i"
    cp $IDIR/spectrum.slha .
    rm -f $IDIR/*.txt
    date > $IDIR/log.txt
    export OMP_NUM_THREADS=1
    timeout 30m ./gambit -f $BASEDIR/gambit_testcollider.yaml > $IDIR/log.txt
    date >> $IDIR/log.txt
    if test $? -eq 0; then
        grep COLLIDER_RESULT $IDIR/log.txt > $IDIR/results.txt;
    else
        echo "ERROR in processing point $i" 1>&2
    fi
done
