//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of available back- 
///  ends.                                        
///                                               
///  This file was automatically generated by     
///  backend_harvester.py. Do not modify.         
///                                               
///  Do not add to this if you want to add a new  
///  backend -- just add your frontend header to  
///  Backends/include/gambit/Backends/frontends   
///  and rest assured that backend_harvester.py   
///  will make sure it ends up here.              
///                                               
///  *********************************************
///                                               
///  Authors (add name and date if you modify):   
///                                               
///  \author The GAMBIT Collaboration            
///  \date 12:36AM on April 26, 2015
///                                               
///  *********************************************
                                                  
#ifndef __backend_rollcall_hpp__                  
#define __backend_rollcall_hpp__                  
                                                  
// Include the backend macro definitions          
#include "gambit/Backends/backend_macros.hpp"   
                                                  
// Automatically-generated list of frontends.     
#include "gambit/Backends/frontends/BOSSMinimalExample_1_2.hpp"
#include "gambit/Backends/frontends/BOSSMinimalExample_1_0.hpp"
#include "gambit/Backends/frontends/HiggsBounds.hpp"
#include "gambit/Backends/frontends/Pythia_8_186.hpp"
#include "gambit/Backends/frontends/fakeSoftSUSY.hpp"
#include "gambit/Backends/frontends/SUSYPOPE.hpp"
#include "gambit/Backends/frontends/FastSim.hpp"
#include "gambit/Backends/frontends/libFarrayTest.hpp"
#include "gambit/Backends/frontends/FeynHiggs.hpp"
#include "gambit/Backends/frontends/libfortran.hpp"
#include "gambit/Backends/frontends/SUSYHIT.hpp"
#include "gambit/Backends/frontends/MicrOmegas.hpp"
#include "gambit/Backends/frontends/nulike.hpp"
#include "gambit/Backends/frontends/SuperIso.hpp"
#include "gambit/Backends/frontends/DarkSUSY.hpp"
#include "gambit/Backends/frontends/gamLike.hpp"
#include "gambit/Backends/frontends/DDCalc0.hpp"
#include "gambit/Backends/frontends/BOSSMinimalExample_1_1.hpp"
#include "gambit/Backends/frontends/HiggsSignals.hpp"
#include "gambit/Backends/frontends/libfirst_1_0.hpp"
#include "gambit/Backends/frontends/libfirst_1_1.hpp"

#endif // defined __backend_rollcall_hpp__
