//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Automatically generated preprocessor sequence
///  of functor types.                            
///                                               
///  This file was automatically generated by     
///  module_harvester.py. Do not modify.          
///  The content is harvested from the rollcall   
///  headers registered in module_rollcall.hpp    
///  and the types registered in                  
///  types_rollcall.hpp.                          
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 06:03PM on April 15, 2015
///                                               
///  *********************************************
                                                  
#ifndef __all_functor_types_hpp__                 
#define __all_functor_types_hpp__                 
                                                  
#include "gambit/Elements/types_rollcall.hpp"   
                                                  
// Automatically generated preprocessor sequence of module functor types 
#define PRINTABLE_TYPES \
(Gambit::DarkBit::simpleHistContainter)\
(Gambit::DarkBit::stringFunkMap)\
(Gambit::DarkBit::DD_couplings)\
(int)\
(DarkBit::nuyield_functype)\
(std::vector<std::string>)\
(ExampleBit_A::singleprec)\
(DarkBit::fptr_dd)\
(Gambit::DarkBit::DecayChain::ChainContainer)\
(std::vector<double>)\
(parameters)\
(Gambit::DarkBit::SimYieldTable)\
(eaSLHA)\
(bool)\
(Gambit::DarkBit::stringIntMap)\
(Gambit::DarkBit::RD_spectrum_type)\
(SMInputs)\
(Funk::Funk)\
(Gambit::DarkBit::TH_ProcessCatalog)\
(HEPUtils::Event)\
(Spectrum*)\
(const SMplusUV*)\
(Gambit::DarkBit::TH_resonances_thresholds)\
(X)\
(Gambit::DarkBit::DecayChain::DecayTable)\
(fptr)\
(DecayTable)\
(double)\
(const Spectrum*)\
(DarkBit::nudata)\
(DecayTable::Entry)\
(ModelParameters)\
(str)\

// Automatically generated preprocessor sequence of backend functor types 
#define BACKEND_FUNCTOR_TYPES \
((sd_char2bodygrav_type*(*)(),sd_char2bodygrav_type*))\
((DS_PACODES*(*)(),DS_PACODES*))\
((void(*)(double*,double*,double*,double*),void,double*,double*,double*,double*))\
((void(*)(double*,double*,double*,double,double*,double*,double*,double,parameters*),void,double*,double*,double*,double,double*,double*,double*,double,parameters*))\
((void(*)(int&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,int&),void,int&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,int&))\
((sd_neut2body_type*(*)(),sd_neut2body_type*))\
((sd_sel2body_type*(*)(),sd_sel2body_type*))\
((sd_sdownwidth_type*(*)(),sd_sdownwidth_type*))\
((void(*)(double(*)(double&),double&,double&,double&,double&,int&),void,double(*)(double&),double&,double&,double&,double&,int&))\
((widthhl_hdec_type*(*)(),widthhl_hdec_type*))\
((void(*)(double&,double&,double&,double&,double&),void,double&,double&,double&,double&,double&))\
((void(*)(int&),void,int&))\
((void(*)(int&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&),void,int&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&))\
((void(*)(double&,double),void,double&,double))\
((double(*)(double(*)(double&),int&),double,double(*)(double&),int&))\
((void(*)(int&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_creal&,fh_creal&,fh_creal&),void,int&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_creal&,fh_creal&,fh_creal&))\
((DS_INTDOF*(*)(),DS_INTDOF*))\
((libFarrayTest_CB3_type*(*)(),libFarrayTest_CB3_type*))\
((sd_sbotwidth_type*(*)(),sd_sbotwidth_type*))\
((sd_gluiwidth_type*(*)(),sd_gluiwidth_type*))\
((void(*)(double*,double*,double,double*,double*,double,parameters*),void,double*,double*,double,double*,double*,double,parameters*))\
((sd_selwidth_type*(*)(),sd_selwidth_type*))\
((DS_RDPTH*(*)(),DS_RDPTH*))\
((sd_stopwidth_type*(*)(),sd_stopwidth_type*))\
((sd_glui3body_type*(*)(),sd_glui3body_type*))\
((double(*)(parameters*),double,parameters*))\
((sd_stop3body_type*(*)(),sd_stop3body_type*))\
((sd_sbot3body_type*(*)(),sd_sbot3body_type*))\
((int(*)(double,int,int,double*),int,double,int,int,double*))\
((DS_RDPARS*(*)(),DS_RDPARS*))\
((int(*)(int),int,int))\
((void(*)(std::complex<double>*,std::complex<double>*,double,double,parameters*),void,std::complex<double>*,std::complex<double>*,double,double,parameters*))\
((double(*)(int&,double&,double&,double&),double,int&,double&,double&,double&))\
((void(*)(bool*),void,bool*))\
((DS_DDCOM*(*)(),DS_DDCOM*))\
((sd_stau2bodygrav_type*(*)(),sd_stau2bodygrav_type*))\
((sd_stop4body_type*(*)(),sd_stop4body_type*))\
((void(*)(double*,double*,double*,double,parameters*),void,double*,double*,double*,double,parameters*))\
((sd_topwidth_type*(*)(),sd_topwidth_type*))\
((void(*)(int&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&),void,int&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&,fh_real&))\
((sd_char2body_type*(*)(),sd_char2body_type*))\
((sd_sntau2body_type*(*)(),sd_sntau2body_type*))\
((sd_supwidth_type*(*)(),sd_supwidth_type*))\
((sd_stau2body_type*(*)(),sd_stau2body_type*))\
((int(*)(double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double),int,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double,double))\
((void(*)(),void))\
((void(*)(double*),void,double*))\
((Fdouble(*)(Farray< Fdouble,1,3>&),Fdouble,Farray< Fdouble,1,3>&))\
((double(*)(int&,int&,double&,int&,int&,int&),double,int&,int&,double&,int&,int&,int&))\
((sd_sbot2body_type*(*)(),sd_sbot2body_type*))\
((void(*)(double*,std::complex<double>*,double,double,parameters*),void,double*,std::complex<double>*,double,double,parameters*))\
((double(*)(double,double,int),double,double,double,int))\
((sd_sup2body_type*(*)(),sd_sup2body_type*))\
((void(*)(const char&,const char&,const char&,const char&,const char&,double&,double&,bool&,bool&),void,const char&,const char&,const char&,const char&,const char&,double&,double&,bool&,bool&))\
((DS_MSPCTM*(*)(),DS_MSPCTM*))\
((double(*)(double,double,double*,double*,double*,double*,std::complex<double>*,std::complex<double>*,double*,std::complex<double>*,parameters*,double),double,double,double,double*,double*,double*,double*,std::complex<double>*,std::complex<double>*,double*,std::complex<double>*,parameters*,double))\
((void(*)(int&,int&,int&,int&,int&,int&,int&,int&,int&,int&),void,int&,int&,int&,int&,int&,int&,int&,int&,int&,int&))\
((sd_neutwidth_type*(*)(),sd_neutwidth_type*))\
((Fdouble(*)(Farray<Fdouble, 1,2, 2,3>&),Fdouble,Farray<Fdouble, 1,2, 2,3>&))\
((double(*)(int,...),double,int))\
((double(*)(double&,double&,int&,int&,int&),double,double&,double&,int&,int&,int&))\
((sd_glui2body_type*(*)(),sd_glui2body_type*))\
((void(*)(double*,double*),void,double*,double*))\
((DS_IBINTVARS*(*)(),DS_IBINTVARS*))\
((void(*)(const char&,const double&,const double&,double(*)(const double&, const int&, void*&),double&,double&,int&,double&,double&,const int&,const bool&,const double&,const double&,void*&),void,const char&,const double&,const double&,double(*)(const double&, const int&, void*&),double&,double&,int&,double&,double&,const int&,const bool&,const double&,const double&,void*&))\
((void(*)(double (*)(int&),int&),void,double (*)(int&),int&))\
((widthhh_hdec_type*(*)(),widthhh_hdec_type*))\
((wisfer_hdec_type*(*)(),wisfer_hdec_type*))\
((void(*)(int,int),void,int,int))\
((void(*)(int&,int&,int&),void,int&,int&,int&))\
((DS_MSSMPAR*(*)(),DS_MSSMPAR*))\
((sd_neut2bodygrav_type*(*)(),sd_neut2bodygrav_type*))\
((void(*)(parameters*),void,parameters*))\
((double(*)(const std::vector<double> &,const std::vector<double> &),double,const std::vector<double> &,const std::vector<double> &))\
((sd_stoploop_type*(*)(),sd_stoploop_type*))\
((void(*)(int&,int&,Farray<fh_real, 1,2, 1,5, 1,3>&,Farray<fh_complex, 1,2, 1,2, 1,5, 1,3>&,Farray<fh_real, 1,6, 1,5>&,Farray<fh_complex, 1,36, 1,5>&,Farray< fh_real,1,2>&,Farray< fh_complex,1,4>&,Farray< fh_complex,1,4>&,Farray< fh_real,1,4>&,Farray< fh_complex, 1,16>&,fh_complex&,fh_real&,Farray< fh_real,1,4>&,fh_real&),void,int&,int&,Farray<fh_real, 1,2, 1,5, 1,3>&,Farray<fh_complex, 1,2, 1,2, 1,5, 1,3>&,Farray<fh_real, 1,6, 1,5>&,Farray<fh_complex, 1,36, 1,5>&,Farray< fh_real,1,2>&,Farray< fh_complex,1,4>&,Farray< fh_complex,1,4>&,Farray< fh_real,1,4>&,Farray< fh_complex, 1,16>&,fh_complex&,fh_real&,Farray< fh_real,1,4>&,fh_real&))\
((sd_stop2body_type*(*)(),sd_stop2body_type*))\
((Fdouble(*)(Fdouble*),Fdouble,Fdouble*))\
((sd_neut3body_type*(*)(),sd_neut3body_type*))\
((double(*)(double&),double,double&))\
((DS_RDMGEV*(*)(),DS_RDMGEV*))\
((void(*)(double*,double*,double*,double*,double*),void,double*,double*,double*,double*,double*))\
((double(*)(int&,double&,double&),double,int&,double&,double&))\
((hd_golddec_type*(*)(),hd_golddec_type*))\
((int*(*)(),int*))\
((void(*)(int&,Farray< fh_real,1,4>&,fh_complex&,Farray<fh_complex, 1,3, 1,3>&,Farray<fh_complex, 1,3, 1,3>&),void,int&,Farray< fh_real,1,4>&,fh_complex&,Farray<fh_complex, 1,3, 1,3>&,Farray<fh_complex, 1,3, 1,3>&))\
((void(*)(int),void,int))\
((sd_sntauwidth_type*(*)(),sd_sntauwidth_type*))\
((double(*)(int&,const double&),double,int&,const double&))\
((int(*)(),int))\
((int(*)(double(*)(double,double,double,double),double*,double*,double*,double*),int,double(*)(double,double,double,double),double*,double*,double*,double*))\
((wisusy_hdec_type*(*)(),wisusy_hdec_type*))\
((double(*)(double*,int,double),double,double*,int,double))\
((DS_WIDTHS*(*)(),DS_WIDTHS*))\
((sd_snel2body_type*(*)(),sd_snel2body_type*))\
((libFarrayTest_CB2_type*(*)(),libFarrayTest_CB2_type*))\
((void(*)(int&,double&,double&,double&,int&,double&),void,int&,double&,double&,double&,int&,double&))\
((void(*)(char*,int&,char*,int&),void,char*,int&,char*,int&))\
((double*(*)(),double*))\
((int(*)(char*,double),int,char*,double))\
((sd_top2body_type*(*)(),sd_top2body_type*))\
((DS_RDDOF*(*)(),DS_RDDOF*))\
((double(*)(double*,double*,double*,std::complex<double>*,std::complex<double>*,double*,std::complex<double>*,parameters*,double),double,double*,double*,double*,std::complex<double>*,std::complex<double>*,double*,std::complex<double>*,parameters*,double))\
((sd_snelwidth_type*(*)(),sd_snelwidth_type*))\
((void(*)(double&,double&,double&,int&),void,double&,double&,double&,int&))\
((std::vector<double>*(*)(),std::vector<double>*))\
((double(*)(int&),double,int&))\
((double(*)(double,double,double*,double*,double*,parameters*,double),double,double,double,double*,double*,double*,parameters*,double))\
((double(*)(double,double*),double,double,double*))\
((void(*)(int&,int&),void,int&,int&))\
((sd_char3body_type*(*)(),sd_char3body_type*))\
((double(*)(double,double,int,int),double,double,double,int,int))\
((void(*)(Farray< Fdouble,1,3>&,Finteger&,Fdouble(*)(Farray< Fdouble,1,3>&)),void,Farray< Fdouble,1,3>&,Finteger&,Fdouble(*)(Farray< Fdouble,1,3>&)))\
((double(*)(double*,double*,double*,std::complex<double>*,std::complex<double>*,parameters*,double),double,double*,double*,double*,std::complex<double>*,std::complex<double>*,parameters*,double))\
((double(*)(double*,double*,double*,double*,double,double,parameters*),double,double*,double*,double*,double*,double,double,parameters*))\
((libFarrayTest_CB_type*(*)(),libFarrayTest_CB_type*))\
((void(*)(const char&),void,const char&))\
((sd_stauwidth_type*(*)(),sd_stauwidth_type*))\
((void(*)(char*,int&,int),void,char*,int&,int))\
((sd_neutloop_type*(*)(),sd_neutloop_type*))\
((double(*)(double*,double*,double*,double*,double*,parameters*,double,double,double),double,double*,double*,double*,double*,double*,parameters*,double,double,double))\
((double(*)(),double))\
((widtha_hdec_type*(*)(),widtha_hdec_type*))\
((void(*)(int&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&),void,int&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&,fh_ccomplex&))\
((void(*)(double&,int&,double&,int&),void,double&,int&,double&,int&))\
((double(*)(int),double,int))\
((DS_RDSWITCH*(*)(),DS_RDSWITCH*))\
((void(*)(double(*)(double&),double&),void,double(*)(double&),double&))\
((DS_RDERRORS*(*)(),DS_RDERRORS*))\
((double(*)(double,double,double,double),double,double,double,double,double))\
((sd_charwidth_type*(*)(),sd_charwidth_type*))\
((double(*)(double&,int&,int&,int&),double,double&,int&,int&,int&))\
((widthhc_hdec_type*(*)(),widthhc_hdec_type*))\
((sd_sdown2body_type*(*)(),sd_sdown2body_type*))\
((double(*)(double*,double*,double*,parameters*,double),double,double*,double*,double*,parameters*,double))\
((sd_gluiloop_type*(*)(),sd_gluiloop_type*))\
((DS_RDPADD*(*)(),DS_RDPADD*))\
((void(*)(int&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&),void,int&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&,fh_creal&))\
((dblarr*(*)(),dblarr*))\
((int(*)(char*),int,char*))\
((micrOMEGAs::MOcommonSTR*(*)(),micrOMEGAs::MOcommonSTR*))\
((void(*)(double&,double&,double&,double&),void,double&,double&,double&,double&))\
((DS_RDLUN*(*)(),DS_RDLUN*))\
((void(*)(const char *),void,const char *))\


#endif // defined __all_functor_types_hpp__
