//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of GAMBIT module   
///  types.                                       
///                                               
///  This file was automatically generated by     
///  module_harvester.py. Do not modify.          
///                                               
///  Do not add to this if you want to add new    
///  types associated with a new (or old) module. 
///  Just add your model type header as           
///  XBit/include/gambit/XBit/XBit_types.hpp and  
///  rest assured that module_harvester.py will   
///  make sure it ends up here.                   
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 12:30PM on April 17, 2015
///                                               
///  *********************************************
                                                  
#ifndef __module_types_rollcall_hpp__             
#define __module_types_rollcall_hpp__             
                                                  
// Automatically-generated list of module types.  
#include "gambit/DecayBit/DecayBit_types.hpp"
#include "gambit/ExampleBit_A/ExampleBit_A_types.hpp"
#include "gambit/DarkBit/DarkBit_types.hpp"
#include "gambit/ColliderBit/ColliderBit_types.hpp"
#include "gambit/EWPOBit/EWPOBit_types.hpp"

#endif // defined __module_types_rollcall_hpp__
