//   GAMBIT: Global and Modular BSM Inference Tool
//   *********************************************
///  \file                                       
///                                               
///  Compile-time registration of GAMBIT modules. 
///                                               
///  This file was automatically generated by     
///  module_harvester.py. Do not modify.          
///  The content is harvested from your local     
///  installation.  If you want to add a new      
///  module, just create it and make sure it      
///  contains a rollcall header, and the          
///  module_harvester.py script will make         
///  sure it turns up here.                       
///                                               
///  By 'rollcall header', we mean a file         
///  myBit/include/myBit_rollcall.hpp,            
///  where myBit is the name of your module.      
///                                               
///  *********************************************
///                                               
///  Authors:                                     
///                                               
///  \author The GAMBIT Collaboration            
///  \date 09:46PM on November 24, 2014
///                                               
///  *********************************************
                                                  
#ifndef __module_rollcall_hpp__                   
#define __module_rollcall_hpp__                   
                                                  
#include "module_macros_incore.hpp"           

#include "DarkBit_rollcall.hpp"
#include "ExampleBit_A_rollcall.hpp"
#include "ExampleBit_B_rollcall.hpp"
#include "SUSYspecBit_rollcall.hpp"
#include "FlavBit_rollcall.hpp"
#include "HiggsBit_rollcall.hpp"
#include "DecayBit_rollcall.hpp"
#include "SpecBit_rollcall.hpp"

#endif // defined __module_rollcall_hpp__
