/********************************************************************
* BinnedLik_Dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BinnedLik_Dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBinnedLik_Dict();
extern void G__cpp_setup_inheritanceBinnedLik_Dict();
extern void G__cpp_setup_typetableBinnedLik_Dict();
extern void G__cpp_setup_memvarBinnedLik_Dict();
extern void G__cpp_setup_globalBinnedLik_Dict();
extern void G__cpp_setup_memfuncBinnedLik_Dict();
extern void G__cpp_setup_funcBinnedLik_Dict();
extern void G__set_cpp_environmentBinnedLik_Dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "ComputeMT2.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BinnedLik_DictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BinnedLik_DictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BinnedLik_DictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BinnedLik_DictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTBaselEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTBaselEdoublegR;
extern G__linked_taginfo G__BinnedLik_DictLN_TVectorTlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TVectorTlEdoublegR;
extern G__linked_taginfo G__BinnedLik_DictLN_TElementActionTlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TElementPosActionTlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTRow_constlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTRowlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTDiag_constlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTColumn_constlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTFlat_constlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTSub_constlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTSparseRow_constlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTSparseDiag_constlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTColumnlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTDiaglEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTFlatlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTSublEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTSparseRowlEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TMatrixTSparseDiaglEfloatgR;
extern G__linked_taginfo G__BinnedLik_DictLN_TLorentzVector;
extern G__linked_taginfo G__BinnedLik_DictLN_ComputeMT2;

/* STUB derived class for protected member access */
