CXXFLAGS := -std=c++11 -fPIC

FILES_NETWORKS = \
  networks/NNfunction_bb_b1b1.o \
  networks/NNfunction_bb_b2b2.o \
  networks/NNfunction_gg.o \
  networks/NNfunction_ng_chi01.o \
  networks/NNfunction_ng_chi02.o \
  networks/NNfunction_ng_chi03.o \
  networks/NNfunction_ng_chi04.o \
  networks/NNfunction_ng_chiMinus1.o \
  networks/NNfunction_ng_chiMinus2.o \
  networks/NNfunction_ng_chiPlus1.o \
  networks/NNfunction_ng_chiPlus2.o \
  networks/NNfunction_nn_charge1p_charge1m.o \
  networks/NNfunction_nn_charge1p_charge2m.o \
  networks/NNfunction_nn_charge2p_charge1m.o \
  networks/NNfunction_nn_charge2p_charge2m.o \
  networks/NNfunction_nn_chi1_charge1m.o \
  networks/NNfunction_nn_chi1_charge1p.o \
  networks/NNfunction_nn_chi1_charge2m.o \
  networks/NNfunction_nn_chi1_charge2p.o \
  networks/NNfunction_nn_chi1_chi1.o \
  networks/NNfunction_nn_chi1_chi2.o \
  networks/NNfunction_nn_chi1_chi3.o \
  networks/NNfunction_nn_chi1_chi4.o \
  networks/NNfunction_nn_chi2_charge1m.o \
  networks/NNfunction_nn_chi2_charge1p.o \
  networks/NNfunction_nn_chi2_charge2m.o \
  networks/NNfunction_nn_chi2_charge2p.o \
  networks/NNfunction_nn_chi2_chi2.o \
  networks/NNfunction_nn_chi2_chi3.o \
  networks/NNfunction_nn_chi2_chi4.o \
  networks/NNfunction_nn_chi3_charge1m.o \
  networks/NNfunction_nn_chi3_charge1p.o \
  networks/NNfunction_nn_chi3_charge2m.o \
  networks/NNfunction_nn_chi3_charge2p.o \
  networks/NNfunction_nn_chi3_chi3.o \
  networks/NNfunction_nn_chi3_chi4.o \
  networks/NNfunction_nn_chi4_chi4.o \
  networks/NNfunction_ns_chi01_cL.o \
  networks/NNfunction_ns_chi01_cR.o \
  networks/NNfunction_ns_chi01_dL.o \
  networks/NNfunction_ns_chi01_dR.o \
  networks/NNfunction_ns_chi01_sL.o \
  networks/NNfunction_ns_chi01_sR.o \
  networks/NNfunction_ns_chi01_uL.o \
  networks/NNfunction_ns_chi01_uR.o \
  networks/NNfunction_ns_chi02_cL.o \
  networks/NNfunction_ns_chi02_cR.o \
  networks/NNfunction_ns_chi02_dL.o \
  networks/NNfunction_ns_chi02_dR.o \
  networks/NNfunction_ns_chi02_sL.o \
  networks/NNfunction_ns_chi02_sR.o \
  networks/NNfunction_ns_chi02_uL.o \
  networks/NNfunction_ns_chi02_uR.o \
  networks/NNfunction_ns_chi03_cL.o \
  networks/NNfunction_ns_chi03_cR.o \
  networks/NNfunction_ns_chi03_dL.o \
  networks/NNfunction_ns_chi03_dR.o \
  networks/NNfunction_ns_chi03_sL.o \
  networks/NNfunction_ns_chi03_sR.o \
  networks/NNfunction_ns_chi03_uL.o \
  networks/NNfunction_ns_chi03_uR.o \
  networks/NNfunction_ns_chi04_cL.o \
  networks/NNfunction_ns_chi04_cR.o \
  networks/NNfunction_ns_chi04_dL.o \
  networks/NNfunction_ns_chi04_dR.o \
  networks/NNfunction_ns_chi04_sL.o \
  networks/NNfunction_ns_chi04_sR.o \
  networks/NNfunction_ns_chi04_uL.o \
  networks/NNfunction_ns_chi04_uR.o \
  networks/NNfunction_ns_chiMinus1_cL.o \
  networks/NNfunction_ns_chiMinus1_dL.o \
  networks/NNfunction_ns_chiMinus1_sL.o \
  networks/NNfunction_ns_chiMinus1_uL.o \
  networks/NNfunction_ns_chiMinus2_cL.o \
  networks/NNfunction_ns_chiMinus2_dL.o \
  networks/NNfunction_ns_chiMinus2_sL.o \
  networks/NNfunction_ns_chiMinus2_uL.o \
  networks/NNfunction_ns_chiPlus1_cL.o \
  networks/NNfunction_ns_chiPlus1_dL.o \
  networks/NNfunction_ns_chiPlus1_sL.o \
  networks/NNfunction_ns_chiPlus1_uL.o \
  networks/NNfunction_ns_chiPlus2_cL.o \
  networks/NNfunction_ns_chiPlus2_dL.o \
  networks/NNfunction_ns_chiPlus2_sL.o \
  networks/NNfunction_ns_chiPlus2_uL.o \
  networks/NNfunction_sb_cLcL.o \
  networks/NNfunction_sb_cLcR.o \
  networks/NNfunction_sb_cLdL.o \
  networks/NNfunction_sb_cLdR.o \
  networks/NNfunction_sb_cLsL.o \
  networks/NNfunction_sb_cLsR.o \
  networks/NNfunction_sb_cLuL.o \
  networks/NNfunction_sb_cLuR.o \
  networks/NNfunction_sb_cRcR.o \
  networks/NNfunction_sb_dLcR.o \
  networks/NNfunction_sb_dLdL.o \
  networks/NNfunction_sb_dLdR.o \
  networks/NNfunction_sb_dLsR.o \
  networks/NNfunction_sb_dLuL.o \
  networks/NNfunction_sb_dLuR.o \
  networks/NNfunction_sb_dRcR.o \
  networks/NNfunction_sb_dRdR.o \
  networks/NNfunction_sb_dRsR.o \
  networks/NNfunction_sb_sLcR.o \
  networks/NNfunction_sb_sLdL.o \
  networks/NNfunction_sb_sLdR.o \
  networks/NNfunction_sb_sLsL.o \
  networks/NNfunction_sb_sLsR.o \
  networks/NNfunction_sb_sLuL.o \
  networks/NNfunction_sb_sLuR.o \
  networks/NNfunction_sb_sRcR.o \
  networks/NNfunction_sb_sRsR.o \
  networks/NNfunction_sb_uLcR.o \
  networks/NNfunction_sb_uLdR.o \
  networks/NNfunction_sb_uLsR.o \
  networks/NNfunction_sb_uLuL.o \
  networks/NNfunction_sb_uLuR.o \
  networks/NNfunction_sb_uRcR.o \
  networks/NNfunction_sb_uRdR.o \
  networks/NNfunction_sb_uRsR.o \
  networks/NNfunction_sb_uRuR.o \
  networks/NNfunction_sg_cL.o \
  networks/NNfunction_sg_cR.o \
  networks/NNfunction_sg_dL.o \
  networks/NNfunction_sg_dR.o \
  networks/NNfunction_sg_sL.o \
  networks/NNfunction_sg_sR.o \
  networks/NNfunction_sg_uL.o \
  networks/NNfunction_sg_uR.o \
  networks/NNfunction_ss_cLcL.o \
  networks/NNfunction_ss_cLcR.o \
  networks/NNfunction_ss_cLdL.o \
  networks/NNfunction_ss_cLdR.o \
  networks/NNfunction_ss_cLsL.o \
  networks/NNfunction_ss_cLsR.o \
  networks/NNfunction_ss_cLuL.o \
  networks/NNfunction_ss_cLuR.o \
  networks/NNfunction_ss_cRcR.o \
  networks/NNfunction_ss_dLcR.o \
  networks/NNfunction_ss_dLdL.o \
  networks/NNfunction_ss_dLdR.o \
  networks/NNfunction_ss_dLsR.o \
  networks/NNfunction_ss_dLuL.o \
  networks/NNfunction_ss_dLuR.o \
  networks/NNfunction_ss_dRcR.o \
  networks/NNfunction_ss_dRdR.o \
  networks/NNfunction_ss_dRsR.o \
  networks/NNfunction_ss_sLcR.o \
  networks/NNfunction_ss_sLdL.o \
  networks/NNfunction_ss_sLdR.o \
  networks/NNfunction_ss_sLsL.o \
  networks/NNfunction_ss_sLsR.o \
  networks/NNfunction_ss_sLuL.o \
  networks/NNfunction_ss_sLuR.o \
  networks/NNfunction_ss_sRcR.o \
  networks/NNfunction_ss_sRsR.o \
  networks/NNfunction_ss_uLcR.o \
  networks/NNfunction_ss_uLdR.o \
  networks/NNfunction_ss_uLsR.o \
  networks/NNfunction_ss_uLuL.o \
  networks/NNfunction_ss_uLuR.o \
  networks/NNfunction_ss_uRcR.o \
  networks/NNfunction_ss_uRdR.o \
  networks/NNfunction_ss_uRsR.o \
  networks/NNfunction_ss_uRuR.o \
  networks/NNfunction_tb_t1t1.o \
  networks/NNfunction_tb_t2t2.o

.PHONY = all clean

SLHA = ../../../../modules/contrib/SLHAPy8

all: testxsec evalxsec libxsec.a libxsec.so
	@true

%xsec: %_xsec.cpp libxsec.a
	$(CXX) $(CXXFLAGS) $^ -o $@ -I$(SLHA)

libxsec.a: $(FILES_NETWORKS) xsec.o SusyLesHouches.o
	ar rcs $@ $^
	ranlib $@

libxsec.so: $(FILES_NETWORKS) xsec.o SusyLesHouches.o
	$(CXX) -shared -o $@ $^

SusyLesHouches.o:
	$(CXX) $(CXXFLAGS) -c $(SLHA)/src/SusyLesHouches.cc -I$(SLHA)

%.o: %.cpp %.h
	$(CXX) $(CXXFLAGS) -c $< -o $@ -I$(SLHA)

networks/%.o: networks/%.cxx networks/%.h
	$(CXX) $(CXXFLAGS) -c $< -o $@

clean:
	rm -f networks/*.o *.o libxsec.a
