#!/bin/sh

# Author: Alexander Voigt

models="models/MSSM"
version="1.0.1"
cppflags=""
cxxflags="-std=c++11 -O2"
fflags="-O2 -frecursive"
cxx="g++"
fc="gfortran"
flibs="-L/usr/local/gcc/4.7.2/lib64/../lib64/ -lgfortran -lm"
makelib="ar cru"
math="math"
packagename="FlexibleSUSY"
threadlibs="-lpthread"

usage="\
Usage: `basename $0` [--all-models] [--cxx] [--cxxflags] [--cppflags]\
 [--fc] [--fflags] [--flibs] [--make-lib-cmd] [--math-cmd] [--threadlibs]\
 [--with-<model>] [--help] [--version]"

if test $# -eq 0; then
    echo "${usage}" 1>&2
    exit 1
fi

help() {
cat <<EOF
Usage: `basename $0` [options]
Options:
  --all-models          Print all models that are build
  --cxx                 Print C++ compiler
  --cxxflags            Print CXXFLAGS
  --cppflags            Print CPPFLAGS
  --fc                  Print Fortran compiler
  --fflags              Print FFLAGS
  --flibs               Print FLIBS
  --make-lib-cmd        Print make library command
  --math-cmd            Print Mathematica kernel command
  --threadlibs          Print thread library
  --with-<model>        Test if <model> is compiled in
  --version             Print the $packagename version
  --help                Print this message
EOF
}

out=""

while test $# -gt 0; do
    case "$1" in
        -*=*) optarg=`echo "$1" | sed 's/[-_a-zA-Z0-9]*=//'` ;;
        *)    optarg= ;;
    esac

    case $1 in
        --all-models)    out="$out $models"   ;;
        --cxx)           out="$out $cxx"      ;;
        --cxxflags)      out="$out $cxxflags" ;;
        --cppflags)      out="$out $cppflags" ;;
        --fc)            out="$out $fc"       ;;
        --fflags)        out="$out $fflags"   ;;
        --flibs)         out="$out $flibs"    ;;
        --make-lib-cmd)  out="$out $makelib"  ;;
        --math-cmd)      out="$out $math"     ;;
        --threadlibs)    out="$out $threadlibs" ;;
        --with-*)
      ### Check for model
            f=`echo $1 | sed 's/--with-//'`
            for c in $models ; do
                if test "x`basename $c`" = "x$f" ; then
                    out="$out yes"
                    break
                fi
                c=""
            done
            if test "x$c" = "x" ; then
                out="$out no"
            fi
            ;;
        --version)       out="$out $version"  ;;
        --help)
      ### Print a help message
            help
            exit 0
            ;;
        *)
      ### Give an error
            echo "Unknown argument \"$1\"!" 1>&2
            echo "${usage}" 1>&2
            exit 1
            ;;
    esac
    shift
done

### Output the stuff
echo $out
