/********************************************************************
* BTaggingWithTruthModule_dict.h
* CAUTION: DON'T CHANGE THIS FILE. THIS FILE IS AUTOMATICALLY GENERATED
*          FROM HEADER FILES LISTED IN G__setup_cpp_environmentXXX().
*          CHANGE THOSE HEADER FILES AND REGENERATE THIS FILE.
********************************************************************/
#ifdef __CINT__
#error BTaggingWithTruthModule_dict.h/C is only for compilation. Abort cint.
#endif
#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <string.h>
#define G__ANSIHEADER
#define G__DICTIONARY
#define G__PRIVATE_GVALUE
#include "G__ci.h"
#include "FastAllocString.h"
extern "C" {
extern void G__cpp_setup_tagtableBTaggingWithTruthModule_dict();
extern void G__cpp_setup_inheritanceBTaggingWithTruthModule_dict();
extern void G__cpp_setup_typetableBTaggingWithTruthModule_dict();
extern void G__cpp_setup_memvarBTaggingWithTruthModule_dict();
extern void G__cpp_setup_globalBTaggingWithTruthModule_dict();
extern void G__cpp_setup_memfuncBTaggingWithTruthModule_dict();
extern void G__cpp_setup_funcBTaggingWithTruthModule_dict();
extern void G__set_cpp_environmentBTaggingWithTruthModule_dict();
}


#include "TObject.h"
#include "TMemberInspector.h"
#include "../../include/delphes/BTaggingWithTruthModule.h"
#include <algorithm>
namespace std { }
using namespace std;

#ifndef G__MEMFUNCBODY
#endif

extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TClass;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TBuffer;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TMemberInspector;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TObject;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TNamed;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_vectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgR;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_reverse_iteratorlEvectorlEROOTcLcLTSchemaHelpercOallocatorlEROOTcLcLTSchemaHelpergRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TObjArray;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_vectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgR;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_reverse_iteratorlEvectorlETVirtualArraymUcOallocatorlETVirtualArraymUgRsPgRcLcLiteratorgR;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TIterator;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_iteratorlEbidirectional_iterator_tagcOTObjectmUcOlongcOconstsPTObjectmUmUcOconstsPTObjectmUaNgR;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_TTask;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_maplETStringcOTStringcOlesslETStringgRcOallocatorlEpairlEconstsPTStringcOTStringgRsPgRsPgR;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_ExRootTask;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_DelphesModule;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_ExRootFilter;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_BTaggingWithTruthPartonClassifier;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_BTaggingWithTruth;
extern G__linked_taginfo G__BTaggingWithTruthModule_dictLN_maplEintcODelphesFormulamUcOlesslEintgRcOallocatorlEpairlEconstsPintcODelphesFormulamUgRsPgRsPgR;

/* STUB derived class for protected member access */
