GAMBIT: HEColliderBit/src/HEColliderMain.cpp File Reference
HEColliderMain.cpp File Reference
#include "Pythia8Backend.hpp"
#include "Delphes3Backend.hpp"
#include "Analysis.hpp"
#include "Event.hpp"
#include <string>
#include <iostream>
#include <fstream>
#include "boost/lexical_cast.hpp"
#include "omp.h"
Defines
#define CHUNKSIZE 50
#define NEVENTS 1000
#define MAIN_SHARED counter,slhaFileName,delphesConfigFile
#define MAIN_PRIVATE genEvent,recoEvent,outFile,temp
Functions
int main ()
Define Documentation
#define CHUNKSIZE 50
Definition at line 35 of file HEColliderMain.cpp.
Referenced by main().
#define MAIN_PRIVATE genEvent,recoEvent,outFile,temp
Definition at line 38 of file HEColliderMain.cpp.
#define MAIN_SHARED counter,slhaFileName,delphesConfigFile
Definition at line 37 of file HEColliderMain.cpp.
#define NEVENTS 1000
Definition at line 36 of file HEColliderMain.cpp.
Referenced by main().
Function Documentation
int main ()
Todo:
Generalise to a vector of analyses, populated by names
Definition at line 43 of file HEColliderMain.cpp.
References GAMBIT::Analysis::analyze(), CHUNKSIZE, GAMBIT::Event::clear(), GAMBIT::Analysis::finalize(), GAMBIT::Analysis::init(), GAMBIT::Event::met(), GAMBIT::mkAnalysis(), NEVENTS, GAMBIT::HEColliderBit::Pythia8Backend::nextEvent(), and GAMBIT::HEColliderBit::Delphes3Backend::processEvent().
{
  // simulation setup...
  //string slhaFileName = "mhmodBenchmark.slha";
  string slhaFileName = "sps1aWithDecays.spc";
  string delphesConfigFile = "delphes_card_ATLAS.tcl";
  // variables used during parallelization
  string temp;
  ofstream outFile;
  int counter, chunk;
  // For event storage
  Pythia8::Event genEvent;
  GAMBIT::Event recoEvent;
  cout<<"\n\n Now testing Parallelized HECollider Simulation:\n\n";
  chunk = CHUNKSIZE;
  GAMBIT::Analysis* ana = GAMBIT::mkAnalysis("ATLAS_0LEP");
  ana->init();
//  #pragma omp parallel shared(MAIN_SHARED) private(MAIN_PRIVATE)
  {
    // Initialize the backends
    GAMBIT::HEColliderBit::Pythia8Backend myPythia(12345 + 17 * omp_get_thread_num(), slhaFileName);
    GAMBIT::HEColliderBit::Delphes3Backend myDelphes(delphesConfigFile);
    // For a reasonable output
//    temp = "tester_thread.dat";
    temp = "tester_thread"+boost::lexical_cast<string>(omp_get_thread_num())+".dat";
    outFile.open(temp.c_str());
//     #pragma omp for schedule(dynamic,chunk)
    for (counter=0; counter<NEVENTS; counter++)
    {
      genEvent.clear();
      recoEvent.clear();
      myPythia.nextEvent(genEvent);
      myDelphes.processEvent(genEvent, recoEvent);
      ana->analyze(recoEvent);
      outFile<<"\n Event "<<counter<<" Generated, with event size = "<<genEvent.size();
      outFile<<"\n Event "<<counter<<" Processed, with missingET = "<<recoEvent.met();
    }
    cout<<"\n\n";
    outFile.close();
  } // end omp parallel block
  ana->finalize();
  //cout << "LIKELIHOOD = " << ana->likelihood() << endl;
  delete ana;
  cout<<"\n\n Parallelized HECollider Simulation + Analysis finished. Generated ";
  cout<<counter<<" events.\n\n";
  return 0;
}