GAMBIT: GAMBIT::module_functor< TYPE > Class Template Reference
GAMBIT::module_functor< TYPE > Class Template Reference
#include <functors.hpp>
Public Member Functions
module_functor (void(*inputFunction)(TYPE &), str func_name, str func_capability, str result_type, str origin_name)
void calculate ()
TYPE operator() ()
void setDependency (str dep, str type, void(*resolver)(functor *))
void setBackendConditionalDependency (str req, str be, str ver, str dep, str dep_type, void(*resolver)(functor *))
void setBackendConditionalDependencySingular (str req, str be, str ver, str dep, str dep_type, void(*resolver)(functor *))
void setModelConditionalDependency (str model, str dep, str dep_type, void(*resolver)(functor *))
void setBackendReq (str req, str type, void(*resolver)(functor *))
void setPermittedBackend (str req, str be, str ver)
void setPermittedBackendSingular (str req, str be, str ver)
Protected Attributes
TYPE myValue
void(* myFunction)(TYPE &)
Detailed Description
template<typename TYPE>
class GAMBIT::module_functor< TYPE >
Definition at line 228 of file functors.hpp.
Constructor & Destructor Documentation
template<typename TYPE > GAMBIT::module_functor< TYPE >::module_functor (void(*)(TYPE &) inputFunction, str func_name, str func_capability, str result_type, str origin_name) [inline]
Definition at line 234 of file functors.hpp.
References GAMBIT::functor::myCapability, GAMBIT::module_functor< TYPE >::myFunction, GAMBIT::functor::myName, GAMBIT::functor::myOrigin, GAMBIT::functor::myStatus, GAMBIT::functor::myType, and GAMBIT::functor::needs_recalculating.
      {
        myFunction      = inputFunction;
        myName          = func_name;
        myCapability    = func_capability;
        myType          = result_type;
        myOrigin        = origin_name;
        myStatus        = 1;
        needs_recalculating = true;
      }
Member Function Documentation
template<typename TYPE > void GAMBIT::module_functor< TYPE >::calculate () [inline, virtual]
Reimplemented from GAMBIT::functor.
Definition at line 250 of file functors.hpp.
References GAMBIT::module_functor< TYPE >::myFunction, GAMBIT::module_functor< TYPE >::myValue, and GAMBIT::functor::needs_recalculating.
{ if(needs_recalculating) { this->myFunction(myValue); } }
template<typename TYPE > TYPE GAMBIT::module_functor< TYPE >::operator() () [inline]
Definition at line 253 of file functors.hpp.
References GAMBIT::module_functor< TYPE >::myValue.
{ return myValue; }
template<typename TYPE > void GAMBIT::module_functor< TYPE >::setBackendConditionalDependency (str req, str be, str ver, str dep, str dep_type, void(*)(functor *) resolver) [inline]
Definition at line 265 of file functors.hpp.
References GAMBIT::delimiterSplit(), and GAMBIT::module_functor< TYPE >::setBackendConditionalDependencySingular().
      {
        // Split the version string and send each version to be registered
        std::vector<str> versions = delimiterSplit(ver, ",");
        for (std::vector<str>::iterator it = versions.begin() ; it != versions.end(); ++it)
        {
          setBackendConditionalDependencySingular(req, be, *it, dep, dep_type, resolver);
        }
      }
template<typename TYPE > void GAMBIT::module_functor< TYPE >::setBackendConditionalDependencySingular (str req, str be, str ver, str dep, str dep_type, void(*)(functor *) resolver) [inline]
Definition at line 277 of file functors.hpp.
References GAMBIT::functor::backendreq_types, GAMBIT::functor::dependency_map, GAMBIT::functor::myBackendConditionalDependencies, GAMBIT::functor::name(), and GAMBIT::functor::origin().
Referenced by GAMBIT::module_functor< TYPE >::setBackendConditionalDependency().
      {
        sspair key (dep, dep_type);
        std::vector<str> quad;
        if (this->backendreq_types.find(req) != this->backendreq_types.end())
        {
          quad.push_back(req);
          quad.push_back(this->backendreq_types[req]);
          quad.push_back(be);
          quad.push_back(ver);
        }
        else
        {
          cout << "Error whilst attempting to set backend-conditional dependency:" << endl;
          cout << "The type of the backend requirement " << req << "on which the " << endl;
          cout << "dependency "<< dep << " is conditional has not been set.  This" << endl;
          cout << "is " << this->name() << " in " << this->origin() << "." << endl;
          //FIXME throw a real error here
        }
        if (this->myBackendConditionalDependencies.find(quad) == this->myBackendConditionalDependencies.end())
        {
          std::vector<sspair> newvec;
          this->myBackendConditionalDependencies[quad] = newvec;
        }
        this->myBackendConditionalDependencies[quad].push_back(key);
        this->dependency_map[key] = resolver;
      }
template<typename TYPE > void GAMBIT::module_functor< TYPE >::setBackendReq (str req, str type, void(*)(functor *) resolver) [inline]
Definition at line 320 of file functors.hpp.
References GAMBIT::functor::backendreq_map, GAMBIT::functor::backendreq_types, GAMBIT::functor::myBackendReqs, and GAMBIT::functor::type().
      {
        sspair key (req, type);
        this->backendreq_types[req] = type;
        this->myBackendReqs.push_back(key);
        this->backendreq_map[key] = resolver;
      }
template<typename TYPE > void GAMBIT::module_functor< TYPE >::setDependency (str dep, str type, void(*)(functor *) resolver) [inline]
Definition at line 256 of file functors.hpp.
References GAMBIT::functor::dependency_map, and GAMBIT::functor::myDependencies.
      {
        sspair key (dep, type);
        this->myDependencies.push_back(key);
        this->dependency_map[key] = resolver;
      }
template<typename TYPE > void GAMBIT::module_functor< TYPE >::setModelConditionalDependency (str model, str dep, str dep_type, void(*)(functor *) resolver) [inline]
Definition at line 307 of file functors.hpp.
References GAMBIT::functor::dependency_map, and GAMBIT::functor::myModelConditionalDependencies.
      {
        sspair key (dep, dep_type);
        if (this->myModelConditionalDependencies.find(model) == this->myModelConditionalDependencies.end())
        {
          std::vector<sspair> newvec;
          this->myModelConditionalDependencies[model] = newvec;
        }
        this->myModelConditionalDependencies[model].push_back(key);
        this->dependency_map[key] = resolver;
      }
template<typename TYPE > void GAMBIT::module_functor< TYPE >::setPermittedBackend (str req, str be, str ver) [inline]
Definition at line 329 of file functors.hpp.
References GAMBIT::delimiterSplit(), and GAMBIT::module_functor< TYPE >::setPermittedBackendSingular().
      {
        // Split the version string and send each version to be registered
        std::vector<str> versions = delimiterSplit(ver, ",");
        for (std::vector<str>::iterator it = versions.begin() ; it != versions.end(); ++it)
        {
          setPermittedBackendSingular(req, be, *it);
        }
      }
template<typename TYPE > void GAMBIT::module_functor< TYPE >::setPermittedBackendSingular (str req, str be, str ver) [inline]
Definition at line 340 of file functors.hpp.
References GAMBIT::functor::backendreq_types, GAMBIT::functor::name(), GAMBIT::functor::origin(), and GAMBIT::functor::permitted_map.
Referenced by GAMBIT::module_functor< TYPE >::setPermittedBackend().
      {
        sspair key;
        if (this->backendreq_types.find(req) != this->backendreq_types.end())
        {
          key = std::make_pair(req, this->backendreq_types[req]);
        }
        else
        {
          cout << "Error whilst attempting to set permitted backend:" << endl;
          cout << "The return type of the backend requirement " << req << "is not set." << endl;
          cout << "This is " << this->name() << " in " << this->origin() << "." << endl;
          //FIXME throw a real error here
        }
        sspair vector_entry (be,  ver);
        if (this->permitted_map.find(key) == this->permitted_map.end())
        {
          std::vector<sspair> newvec;
          this->permitted_map[key] = newvec;
        }
        this->permitted_map[key].push_back(vector_entry);
      }
Member Data Documentation
template<typename TYPE > void(* GAMBIT::module_functor< TYPE >::myFunction)(TYPE &) [protected]
Definition at line 369 of file functors.hpp.
Referenced by GAMBIT::module_functor< TYPE >::calculate(), and GAMBIT::module_functor< TYPE >::module_functor().
template<typename TYPE > TYPE GAMBIT::module_functor< TYPE >::myValue [protected]
Definition at line 366 of file functors.hpp.
Referenced by GAMBIT::module_functor< TYPE >::calculate(), and GAMBIT::module_functor< TYPE >::operator()().
The documentation for this class was generated from the following file:
Utils/include/functors.hpp