GAMBIT: gambit::RandomScanner Class Reference
gambit::RandomScanner Class Reference
Random Scanner.
#include <RandomScanner.hpp>
Public Member Functions
RandomScanner (ModelBasePtr usedModel, int nScansPerModel=10, std::string const &dumpfilename=std::string("_RandomScanDumpfile.txt"))
void setNScansPerModel (unsigned int nScans)
virtual ~RandomScanner ()
virtual void doScanStep ()
virtual void runStepping ()
virtual void runStepping (int maxsteps=100)
Private Attributes
longlong _nScansPerModel
std::ofstream * _dumpfile
Detailed Description
Random Scanner.
Gutted of ComparatorBase dependency for GAMBIT example
Author:
Johan Lundberg
Date:
July 2011
Author:
Pat Scott
Date:
November 2012
Definition at line 28 of file RandomScanner.hpp.
Constructor & Destructor Documentation
gambit::RandomScanner::RandomScanner (ModelBasePtr usedModel, int nScansPerModel = 10, std::string const & dumpfilename = std::string("_RandomScanDumpfile.txt")) [inline]
Definition at line 33 of file RandomScanner.hpp.
References _dumpfile, and PlantSeeds().
                                                                                       :
      ScannerBase(usedModel),_nScansPerModel(nScansPerModel),
      _dumpfile(0){
      PlantSeeds(-1); // from rngs.h
      std::cout<<"workset is:"<<*(usedModel->getModelParameters());
      //      exit(1);
      _dumpfile = new std::ofstream("_RandomScanDumpfile.txt");
    }
virtual gambit::RandomScanner::~RandomScanner () [inline, virtual]
Definition at line 48 of file RandomScanner.hpp.
{
Member Function Documentation
virtual void gambit::RandomScanner::doScanStep () [inline, virtual]
Implements gambit::ScannerBase.
Definition at line 51 of file RandomScanner.hpp.
Referenced by runStepping().
                                                              : " << workset->getVersion());
      // make new set of random values
      std::vector<std::string> modelVarKeys=workset->getKeys();
      for (std::vector<std::string>::iterator it=modelVarKeys.begin(); it!=modelVarKeys.end();it++){
        double rangelow;
        double rangehigh;
        //        double oldvalue=workset->getValue(*it);
        workset->getRange(*it,rangelow,rangehigh);
        double newvalue=rangelow+Random()*(rangehigh-rangelow);
        workset->setValue(*it,newvalue);
      }
      //GAMBIT_MSG_DEBUG("workset is:"<<*workset);
      double current_LLH=0;
      try{
        //FIXME PS replaced with constant like for now
        //current_LLH=_LLHcalculator->getLLH();
        current_LLH = 0.5;
        if(current_LLH>0){}else{}; // <<-- just to remove not-used warning
        GAMBIT_MSG_INFO("Got LLH:" << current_LLH);
        *_dumpfile<<std::string("Good model:")<<*workset<<std::endl;
      }catch( ::gambit::exceptions::gambit_exception_base & e){
        GAMBIT_MSG_LOG("Caught exception: "<<exceptions::get_exception_dump(e));
        // do something more.. record/skip model
        *_dumpfile<<std::string("Bad model:")<<*workset<<std::endl;
      }catch(...){
        GAMBIT_MSG_ERROR("Caught exception... ? ");
        throw;  // this should not be the case...
      }
      // Here we would also save stuff to scanner internals
      // required for future steps
      // And accept/rejetc etc.
    }
    virtual void runStepping(){
virtual void gambit::RandomScanner::runStepping (int maxsteps = 100) [inline, virtual]
Implements gambit::ScannerBase.
Definition at line 94 of file RandomScanner.hpp.
References doScanStep(), and GAMBIT_MSG_INFO.
{
        GAMBIT_MSG_INFO("scanning at step;"<<i);
        doScanStep();
      }
    }
  private:
virtual void gambit::RandomScanner::runStepping () [inline, virtual]
Definition at line 91 of file RandomScanner.hpp.
{
void gambit::RandomScanner::setNScansPerModel (unsigned int nScans) [inline]
Definition at line 45 of file RandomScanner.hpp.
{
Member Data Documentation
std::ofstream* gambit::RandomScanner::_dumpfile [private]
Definition at line 102 of file RandomScanner.hpp.
Referenced by RandomScanner().
longlong gambit::RandomScanner::_nScansPerModel [private]
Definition at line 101 of file RandomScanner.hpp.
The documentation for this class was generated from the following file:
ScannerBit/include/RandomScanner.hpp