GAMBIT: GAMBIT::Event Class Reference
GAMBIT::Event Class Reference
Simple event class, separating into various classes of particle.
#include <Event.hpp>
Public Member Functions
void clear ()
Empty the event's particle, jet and MET collections.
void addParticle (Particle *p)
Add a final state particle to the event.
void addParticles (const std::vector< Particle * > &ps)
Add a collection of final state particles to the event.
std::vector< Particle * > particles () const
Get all final state particles.
std::vector< Particle * > visible_particles () const
Get visible state particles.
const std::vector< Particle * > & invisible_particles () const
Get invisible final state particles.
const std::vector< Particle * > & electrons () const
Get prompt electrons.
const std::vector< Particle * > & muons () const
Get prompt muons.
const std::vector< Particle * > & taus () const
Get prompt (hadronic) taus.
const std::vector< Particle * > & photons () const
Get prompt photons.
Constructors
Todo:
Need separate types of event (subclasses?) for what gets passed to detsim and to analysis?
Todo:
This class should be able to do its own MET and SET calculations, identify photons, electrons, muons, taus, charged and neutral hadrons, B hadrons/quarks, and construct jets (?)
Event ()
Default constructor.
Event (const std::vector< Particle * > &ps)
Constructor from a list of Particles.
~Event ()
Destructor (cleans up all passed Particles and calculated Jets)
Jets
Todo:
Don't do the on the fly calculation, actually: it's up to the filling routine to do that
Todo:
Why the new'ing? Can we use references more?
const std::vector< Jet * > & jets () const
Get anti-kT 0.4 jets (not including charged leptons or photons)
void setJets (const std::vector< Jet * > &jets)
Set the jets collection.
void addJet (Jet *j)
Add a jet to the jets collection.
Missing energy
const P4 & missingMom () const
Get the missing energy vector.
void setMissingMom (const P4 &pmiss)
Set the missing energy vector.
double met () const
Get the missing ET in GeV.
Private Attributes
std::vector< Jet * > _jets
Jets collection (mutable to allow sorting)
P4 _pmiss
Missing momentum vector.
Separate particle collections
std::vector< Particle * > _photons
std::vector< Particle * > _electrons
std::vector< Particle * > _muons
std::vector< Particle * > _taus
std::vector< Particle * > _invisibles
Detailed Description
Simple event class, separating into various classes of particle.
Definition at line 12 of file Event.hpp.
Constructor & Destructor Documentation
GAMBIT::Event::Event () [inline]
Default constructor.
Definition at line 27 of file Event.hpp.
References clear().
{ clear(); }
GAMBIT::Event::Event (const std::vector< Particle * > & ps) [inline]
Constructor from a list of Particles.
Definition at line 30 of file Event.hpp.
References addParticles(), and clear().
{
      clear();
      addParticles(ps);
    }
GAMBIT::Event::~Event () [inline]
Destructor (cleans up all passed Particles and calculated Jets)
Definition at line 36 of file Event.hpp.
References clear().
             {
      clear();
    }
Member Function Documentation
void GAMBIT::Event::addJet (Jet * j) [inline]
Add a jet to the jets collection.
The Jet should be new'd; Event will take ownership.
Definition at line 179 of file Event.hpp.
References _jets.
Referenced by GAMBIT::fillGambitEvent().
{
      _jets.push_back(j);
    }
void GAMBIT::Event::addParticle (Particle * p) [inline]
Add a final state particle to the event.
Todo:
Clarify ownership/lifetimes -- owned by outside code, or *to be cleaned up by the event on deletion*? THE LATTER
What about taus and Bs?
"Lock" at some point so that jet finding etc.
only get done once
Definition at line 69 of file Event.hpp.
References _electrons, _invisibles, _muons, _photons, _taus, GAMBIT::Particle::isPrompt(), and GAMBIT::Particle::pid().
Referenced by addParticles(), and GAMBIT::fillGambitEvent().
{
      if (p->isPrompt()) {
        if (p->pid() == 22) _photons.push_back(p);
        if (abs(p->pid()) == 11) _electrons.push_back(p);
        if (abs(p->pid()) == 13) _muons.push_back(p);
        if (abs(p->pid()) == 15) _taus.push_back(p);
        if (abs(p->pid()) == 12 || abs(p->pid()) == 14 || abs(p->pid()) == 16 || abs(p->pid()) == 1000022) _invisibles.push_back(p);
      }
    }
void GAMBIT::Event::addParticles (const std::vector< Particle * > & ps) [inline]
Add a collection of final state particles to the event.
Todo:
Should be vector<const Particle*>?
Definition at line 82 of file Event.hpp.
References addParticle().
Referenced by Event().
{
      for (size_t i = 0; i < ps.size(); ++i) addParticle(ps[i]);
    }
void GAMBIT::Event::clear () [inline]
Empty the event's particle, jet and MET collections.
Todo:
Prefer this form when we can use C++11's range-for
Todo:
Really need to store invisibles when we have a dedicated MET variable?
Todo:
Prefer this form when we can use C++11's range-for
Definition at line 43 of file Event.hpp.
References _electrons, _invisibles, _jets, _muons, _photons, _pmiss, _taus, GAMBIT::P4::clear(), jets(), and particles().
Referenced by Event(), main(), and ~Event().
                 {
      // for (Particle* p : particles()) delete p;
      std::vector<Particle*> ps = particles();
      for (size_t i = 0; i < particles().size(); ++i) { delete ps[i]; }
      ps.clear();
      _photons.clear();
      _electrons.clear();
      _muons.clear();
      _taus.clear();
      _invisibles.clear();
      // if (!_jets.empty()) for (Jet* j : jets()) delete j;
      if (!_jets.empty()) for (size_t i = 0; i < jets().size(); ++i) delete jets()[i];
      _jets.clear();
      _pmiss.clear();
    }
const std::vector<Particle*>& GAMBIT::Event::electrons () const [inline]
Get prompt electrons.
Definition at line 133 of file Event.hpp.
References _electrons.
{
      return _electrons;
    }
const std::vector<Particle*>& GAMBIT::Event::invisible_particles () const [inline]
Get invisible final state particles.
Definition at line 127 of file Event.hpp.
References _invisibles.
{
      return _invisibles;
    }
const std::vector<Jet*>& GAMBIT::Event::jets () const [inline]
Get anti-kT 0.4 jets (not including charged leptons or photons)
Definition at line 164 of file Event.hpp.
References GAMBIT::_cmpPtDesc(), and _jets.
Referenced by clear(), and setJets().
{
      std::sort(_jets.begin(), _jets.end(), _cmpPtDesc);
      return _jets;
    }
double GAMBIT::Event::met () const [inline]
Get the missing ET in GeV.
Definition at line 204 of file Event.hpp.
References missingMom(), and GAMBIT::P4::pT().
Referenced by main().
                       {
      return missingMom().pT();
    }
const P4& GAMBIT::Event::missingMom () const [inline]
Get the missing energy vector.
Not _necessarily_ the sum over momenta of final state invisibles
Definition at line 192 of file Event.hpp.
References _pmiss.
Referenced by met().
{
      return _pmiss;
    }
const std::vector<Particle*>& GAMBIT::Event::muons () const [inline]
Get prompt muons.
Definition at line 139 of file Event.hpp.
References _muons.
{
      return _muons;
    }
std::vector<Particle*> GAMBIT::Event::particles () const [inline]
Get all final state particles.
Todo:
Note the return by value: it's not efficient yet!
Todo:
Or use Boost range join to iterate over separate containers transparently... I like this
Todo:
Cache, or otherwise think about efficiency since this gets called by the destructor
Definition at line 89 of file Event.hpp.
References _electrons, _invisibles, _muons, _photons, _taus, and APPEND_VEC.
Referenced by clear().
{
      // Add together all the vectors of the different particle types
      std::vector<Particle*> rtn;
      // rtn.reserve(visible_particles().size() + _invisibles.size());
      rtn.reserve(_photons.size() + _electrons.size() + _muons.size() + _taus.size() + _invisibles.size());
      #define APPEND_VEC(vec) rtn.insert(rtn.end(), vec.begin(), vec.end())
      // APPEND_VEC(visible_particles());
      APPEND_VEC(_photons);
      APPEND_VEC(_electrons);
      APPEND_VEC(_muons);
      APPEND_VEC(_taus);
      APPEND_VEC(_invisibles);
      #undef APPEND_VEC
      return rtn;
    }
const std::vector<Particle*>& GAMBIT::Event::photons () const [inline]
Get prompt photons.
Definition at line 151 of file Event.hpp.
References _photons.
{
      return _photons;
    }
void GAMBIT::Event::setJets (const std::vector< Jet * > & jets) [inline]
Set the jets collection.
The Jets should be new'd; Event will take ownership.
Definition at line 172 of file Event.hpp.
References _jets, and jets().
{
      _jets = jets;
    }
void GAMBIT::Event::setMissingMom (const P4 & pmiss) [inline]
Set the missing energy vector.
Not _necessarily_ the sum over momenta of final state invisibles
Definition at line 199 of file Event.hpp.
References _pmiss.
Referenced by GAMBIT::fillGambitEvent().
{
      _pmiss = pmiss;
    }
const std::vector<Particle*>& GAMBIT::Event::taus () const [inline]
Get prompt (hadronic) taus.
Definition at line 145 of file Event.hpp.
References _taus.
{
      return _taus;
    }
std::vector<Particle*> GAMBIT::Event::visible_particles () const [inline]
Get visible state particles.
Todo:
Note the return by value: it's not efficient yet!
Todo:
Add together all the vectors of the different particle types
Todo:
Or use Boost range join to iterate over separate containers transparently... I like this
Definition at line 110 of file Event.hpp.
References _electrons, _muons, _photons, _taus, and APPEND_VEC.
{
      // Add together all the vectors of the different particle types
      std::vector<Particle*> rtn;
      rtn.reserve(_photons.size() + _electrons.size() + _muons.size() + _taus.size());
      #define APPEND_VEC(vec) rtn.insert(rtn.end(), vec.begin(), vec.end() )
      APPEND_VEC(_photons);
      APPEND_VEC(_electrons);
      APPEND_VEC(_muons);
      APPEND_VEC(_taus);
      #undef APPEND_VEC
      return rtn;
    }
Member Data Documentation
std::vector<Particle*> GAMBIT::Event::_electrons [private]
Definition at line 221 of file Event.hpp.
Referenced by addParticle(), clear(), electrons(), particles(), and visible_particles().
std::vector<Particle*> GAMBIT::Event::_invisibles [private]
Definition at line 221 of file Event.hpp.
Referenced by addParticle(), clear(), invisible_particles(), and particles().
std::vector<Jet*> GAMBIT::Event::_jets [mutable, private]
Jets collection (mutable to allow sorting)
Definition at line 225 of file Event.hpp.
Referenced by addJet(), clear(), jets(), and setJets().
std::vector<Particle*> GAMBIT::Event::_muons [private]
Definition at line 221 of file Event.hpp.
Referenced by addParticle(), clear(), muons(), particles(), and visible_particles().
std::vector<Particle*> GAMBIT::Event::_photons [private]
Todo:
Do we really need to store invisibles, since they aren't experimentally resolveable, and are covered by the explicitly-set missing-mom?
Definition at line 221 of file Event.hpp.
Referenced by addParticle(), clear(), particles(), photons(), and visible_particles().
P4 GAMBIT::Event::_pmiss [private]
Missing momentum vector.
Definition at line 228 of file Event.hpp.
Referenced by clear(), missingMom(), and setMissingMom().
std::vector<Particle*> GAMBIT::Event::_taus [private]
Definition at line 221 of file Event.hpp.
Referenced by addParticle(), clear(), particles(), taus(), and visible_particles().
The documentation for this class was generated from the following file:
HEColliderBit/src/Event.hpp