GAMBIT: GAMBIT::dict Class Reference
GAMBIT::dict Class Reference
#include <dictionary.hpp>
Public Member Functions
dict ()
~dict ()
void purge ()
template<typename Type >
void set (str key, Type entry)
template<typename Type >
Type get (str key)
Private Types
typedef std::string str
typedef boost::any any
typedef std::map< str, any > dictmap
typedef
gambit::exceptions::e_configuration gerr
typedef gambit::exceptions::i_text gerr_txt
Private Member Functions
gerr_txt missing (str key)
gerr_txt bad_type_set (str key)
gerr_txt bad_type_get (str key)
Private Attributes
dictmap guts
gerr error
Detailed Description
Definition at line 33 of file dictionary.hpp.
Member Typedef Documentation
typedef boost::any GAMBIT::dict::any [private]
Definition at line 37 of file dictionary.hpp.
typedef std::map<str,any> GAMBIT::dict::dictmap [private]
Definition at line 38 of file dictionary.hpp.
typedef gambit::exceptions::e_configuration GAMBIT::dict::gerr [private]
Definition at line 39 of file dictionary.hpp.
typedef gambit::exceptions::i_text GAMBIT::dict::gerr_txt [private]
Definition at line 40 of file dictionary.hpp.
typedef std::string GAMBIT::dict::str [private]
Definition at line 36 of file dictionary.hpp.
Constructor & Destructor Documentation
GAMBIT::dict::dict () [inline]
Definition at line 62 of file dictionary.hpp.
{}
GAMBIT::dict::~dict () [inline]
Definition at line 63 of file dictionary.hpp.
{}
Member Function Documentation
gerr_txt GAMBIT::dict::bad_type_get (str key) [inline, private]
Definition at line 55 of file dictionary.hpp.
Referenced by get().
{
      return gerr_txt("type requested for key \""+key+"\" "
      "in dictionary does not match type of actual value."); }
gerr_txt GAMBIT::dict::bad_type_set (str key) [inline, private]
Definition at line 52 of file dictionary.hpp.
Referenced by set().
{
      return gerr_txt("actual value being added to dictionary is"
      "not convertible to requested type given for key \""+key+"\"."); }
template<typename Type > Type GAMBIT::dict::get (str key) [inline]
Definition at line 95 of file dictionary.hpp.
References bad_type_get(), error, GAMBIT_THROW_EXCEPTION, gambit::exceptions::get_exception_origin(), gambit::exceptions::get_exception_text(), guts, and missing().
                       {
      // Attempt to retrieve the value using the key
      try{
        try{
          // Check that the key is in the dictionary
          dictmap::iterator it = guts.find(key);
          // If the key is missing, raise an exception
          if (it == guts.end()) { GAMBIT_THROW_EXCEPTION(error << missing(key)); }
          // Otherwise, cast the value back to its original type and return it
          else { return boost::any_cast<Type>(it->second); }
        }
        // Raise an exception if the user asked for a different type to the one the value was saved as
        catch(std::bad_cast& bc) { GAMBIT_THROW_EXCEPTION(error << bad_type_get(key)); }
      }
      // Catch exception [this should later be replaced by a generic app-wide
      // catch and call to e.what() when the exceptions class is fixed up]
      catch(gerr e) {
        std::cout<<std::endl;
        std::cout<<"Error: "<<gambit::exceptions::get_exception_text(e)<<std::endl;
        std::cout<<"Origin: "<<gambit::exceptions::get_exception_origin(e)<<std::endl;
        std::cout<<"Quitting..."<<std::endl<<std::endl;
        exit(0);
      }
    }
gerr_txt GAMBIT::dict::missing (str key) [inline, private]
Definition at line 49 of file dictionary.hpp.
Referenced by get().
{
      return gerr_txt("key \""+key+"\" is not in the dictionary "
      "that you are trying to get it from."); }
void GAMBIT::dict::purge () [inline]
Definition at line 67 of file dictionary.hpp.
References guts.
{ guts.clear(); } // no, Greg
template<typename Type > void GAMBIT::dict::set (str key, Type entry) [inline]
Definition at line 72 of file dictionary.hpp.
References bad_type_set(), error, GAMBIT_THROW_EXCEPTION, gambit::exceptions::get_exception_origin(), gambit::exceptions::get_exception_text(), and guts.
{
      // Attempt to add the new entry with the requested type
      try{
        try{ guts[key] = static_cast<Type>(entry); }
        // Catch the error if the cast to requested type is not possible
        catch(std::bad_cast& bc) { GAMBIT_THROW_EXCEPTION(error << bad_type_set(key)); }
      }
      // Deal with the error
      catch(gerr e) {
        std::cout<<std::endl;
        std::cout<<"Error: "<<gambit::exceptions::get_exception_text(e)<<std::endl;
        std::cout<<"Origin: "<<gambit::exceptions::get_exception_origin(e)<<std::endl;
        std::cout<<"Quitting..."<<std::endl<<std::endl;
        exit(0);
      }
    }
Member Data Documentation
gerr GAMBIT::dict::error [private]
Definition at line 48 of file dictionary.hpp.
Referenced by get(), and set().
dictmap GAMBIT::dict::guts [private]
Definition at line 45 of file dictionary.hpp.
Referenced by get(), purge(), and set().
The documentation for this class was generated from the following file:
Utils/include/dictionary.hpp