GAMBIT: GAMBIT::Analysis Class Reference
GAMBIT::Analysis Class Reference
#include <Analysis.hpp>
Public Member Functions
virtual void init ()
Initialize counters etc.
virtual void analyze (const Event &e)
Analyze the event (accessed by reference)
virtual void analyze (const Event *e)=0
Analyze the event (accessed by pointer)
virtual void finalize ()
Finalize: scale by number of input events, etc.
virtual double logLikelihood ()=0
Return the log likelihood (at the end of the run)
virtual double likelihood ()
Return the likelihood (at the end of the run, via logLikelihood)
Detailed Description
Definition at line 10 of file Analysis.hpp.
Member Function Documentation
virtual void GAMBIT::Analysis::analyze (const Event & e) [inline, virtual]
Analyze the event (accessed by reference)
Definition at line 17 of file Analysis.hpp.
References analyze().
Referenced by analyze(), and main().
{ analyze(&e); }
virtual void GAMBIT::Analysis::analyze (const Event * e) [pure virtual]
Analyze the event (accessed by pointer)
Todo:
Make this the convenience method and the ref version the one to be overridden
Implemented in GAMBIT::Analysis_ATLAS0LEP.
virtual void GAMBIT::Analysis::finalize () [inline, virtual]
Finalize: scale by number of input events, etc.
Reimplemented in GAMBIT::Analysis_ATLAS0LEP.
Definition at line 24 of file Analysis.hpp.
Referenced by main().
{  }
virtual void GAMBIT::Analysis::init () [inline, virtual]
Initialize counters etc.
Reimplemented in GAMBIT::Analysis_ATLAS0LEP.
Definition at line 14 of file Analysis.hpp.
Referenced by main().
{  }
virtual double GAMBIT::Analysis::likelihood () [inline, virtual]
Return the likelihood (at the end of the run, via logLikelihood)
Definition at line 30 of file Analysis.hpp.
References logLikelihood().
{ return std::exp(logLikelihood()); }
virtual double GAMBIT::Analysis::logLikelihood () [pure virtual]
Return the log likelihood (at the end of the run)
Implemented in GAMBIT::Analysis_ATLAS0LEP.
Referenced by likelihood().
The documentation for this class was generated from the following file:
HEColliderBit/src/Analysis.hpp