GAMBIT: gambit::ModelParameters Class Reference
gambit::ModelParameters Class Reference
Model Parameters Base class example.
#include <ModelParameters.hpp>
Public Member Functions
ModelParameters ()
virtual ~ModelParameters ()
virtual double getValue (std::string const &inkey) const
virtual const double & operator[] (std::string const &inkey) const
virtual void setValue (std::string const &inkey, double const &value)
virtual std::vector< std::string > getKeys () const
virtual void print () const
ModelParameters ()
virtual ~ModelParameters ()
virtual double getValue (std::string const &inkey) const
virtual const double & operator[] (std::string const &inkey) const
virtual void getRange (std::string const &inkey, double &rangeLow, double &rangeHigh) const
virtual void setValue (std::string const &inkey, double const &value)
virtual void redefineValue (std::string const &name, double const &v, double const &low, double const &high)
virtual std::vector< std::string > getKeys () const
virtual void print () const
Protected Member Functions
void assert_contains (std::string inkey) const
virtual void _definePar (const std::string &newkey)
virtual void _definePar (std::vector< std::string > const &v)
virtual void _definePar (const char **array)
void assert_contains (std::string inkey) const
virtual void _defineValue (std::string const &newkey, double const &value, double const &rangelow=-1e99, double const &rangehigh=1e99)
Private Attributes
std::map< std::string, double > _values
std::map< std::string, double > _rangelow
std::map< std::string, double > _rangehigh
Friends
std::ostream & operator<< (std::ostream &strm, ModelParameters &me)
std::ostream & operator<< (std::ostream &strm, ModelParameters &me)
Detailed Description
Model Parameters Base class example.
Example and base class for typical model parameters. Not so important how set/get works but the model you want to use must be able to understand it
Author:
Johan Lundberg
Date:
July - August 2011
initially based on 'Model' and 'Parameterset' code from Joachim Ripken.
Definition at line 50 of file ModelParameters.hpp.
Constructor & Destructor Documentation
gambit::ModelParameters::ModelParameters () [inline]
Definition at line 58 of file ModelParameters.hpp.
                     : ModelParametersBase(),_values(){
    }
virtual gambit::ModelParameters::~ModelParameters () [inline, virtual]
Definition at line 60 of file ModelParameters.hpp.
{}
gambit::ModelParameters::ModelParameters () [inline]
Definition at line 34 of file ModelParameters.hpp.
                     : ModelParametersBase(),_values(),_rangelow(),_rangehigh(){
    }
virtual gambit::ModelParameters::~ModelParameters () [inline, virtual]
Definition at line 36 of file ModelParameters.hpp.
{}
Member Function Documentation
virtual void gambit::ModelParameters::_definePar (const std::string & newkey) [inline, protected, virtual]
Definition at line 104 of file ModelParameters.hpp.
References _values, and gambit::ModelParametersBase::updateVersion().
Referenced by _definePar().
{
      this->updateVersion();
      _values[newkey]=0.;
    }
virtual void gambit::ModelParameters::_definePar (std::vector< std::string > const & v) [inline, protected, virtual]
Definition at line 111 of file ModelParameters.hpp.
References _definePar().
{
      for(std::vector<std::string>::const_iterator
            it = v.begin(); it != v.end(); ++it) {
        _definePar(*it);
      }
    }
virtual void gambit::ModelParameters::_definePar (const char ** array) [inline, protected, virtual]
Definition at line 120 of file ModelParameters.hpp.
References _definePar().
{
      int i = 0;
      while (array[i] != 0){
        _definePar(array[i]);
        i++;
      }
    }
virtual void gambit::ModelParameters::_defineValue (std::string const & newkey, double const & value, double const & rangelow = -1e99, double const & rangehigh = 1e99) [inline, protected, virtual]
Definition at line 98 of file ModelParameters.hpp.
References _rangehigh, _rangelow, _values, and gambit::ModelParametersBase::updateVersion().
Referenced by gambit::ModelParameters_CMSSM5::ModelParameters_CMSSM5(), gambit::ModelParameters_pMSSM7::ModelParameters_pMSSM7(), and redefineValue().
{
      this->updateVersion();
      _values[newkey]=value;
      _rangelow[newkey]=rangelow;
      _rangehigh[newkey]=rangehigh;
    }
void gambit::ModelParameters::assert_contains (std::string inkey) const [inline, protected]
Definition at line 28 of file ModelParameters.hpp.
References _values, and GAMBIT_MSG_FATAL.
{
      if(_values.count(inkey)!=1){
        GAMBIT_MSG_FATAL("key not found"+inkey);
      }
    }
void gambit::ModelParameters::assert_contains (std::string inkey) const [inline, protected]
Definition at line 52 of file ModelParameters.hpp.
References _values, and GAMBIT_MSG_FATAL.
Referenced by getRange(), getValue(), operator[](), redefineValue(), and setValue().
{
      if(_values.count(inkey)!=1){
        GAMBIT_MSG_FATAL("key not found"+inkey);
      }
    }
virtual std::vector<std::string> gambit::ModelParameters::getKeys () const [inline, virtual]
Definition at line 64 of file ModelParameters.hpp.
References _values.
{
      std::vector<std::string> tmp;
      for (std::map<std::string,double>::const_iterator it=_values.begin();it!=_values.end();it++){
        tmp.push_back((*it).first);
      }
      return tmp;
    }
virtual std::vector<std::string> gambit::ModelParameters::getKeys () const [inline, virtual]
Definition at line 77 of file ModelParameters.hpp.
References _values.
{
      std::vector<std::string> tmp;
      for (std::map<std::string,double>::const_iterator it=_values.begin();it!=_values.end();it++){
        tmp.push_back((*it).first);
      }
      return tmp;
    }
virtual void gambit::ModelParameters::getRange (std::string const & inkey, double & rangeLow, double & rangeHigh) const [inline, virtual]
Definition at line 46 of file ModelParameters.hpp.
References _rangehigh, _rangelow, and assert_contains().
{
      assert_contains(inkey);
      rangeLow=_rangelow.at(inkey);
      rangeHigh=_rangehigh.at(inkey);
    }
virtual double gambit::ModelParameters::getValue (std::string const & inkey) const [inline, virtual]
Definition at line 62 of file ModelParameters.hpp.
References _values, and assert_contains().
{
      assert_contains(inkey);
      return _values.at(inkey);
    }
virtual double gambit::ModelParameters::getValue (std::string const & inkey) const [inline, virtual]
Definition at line 38 of file ModelParameters.hpp.
References _values, and assert_contains().
{
      assert_contains(inkey);
      return _values.at(inkey);
    }
virtual const double& gambit::ModelParameters::operator[] (std::string const & inkey) const [inline, virtual]
Definition at line 42 of file ModelParameters.hpp.
References _values, and assert_contains().
{
      assert_contains(inkey);
      return _values.at(inkey);
    }
virtual const double& gambit::ModelParameters::operator[] (std::string const & inkey) const [inline, virtual]
Definition at line 66 of file ModelParameters.hpp.
References _values, and assert_contains().
{
      assert_contains(inkey);
      return _values.at(inkey);
    }
virtual void gambit::ModelParameters::print () const [inline, virtual]
Definition at line 72 of file ModelParameters.hpp.
References _rangehigh, _rangelow, and _values.
{
      std::cout << "ModelParameters: Printing: "<<std::endl;
      for (std::map<std::string,double>::const_iterator it=_values.begin();it!=_values.end();it++){
        std::cout << "parameter: " << it->first << " value: "<<it->second ;
        std::cout << " range: [" << _rangelow.at(it->first) << ",";
        std::cout << _rangehigh.at(it->first) << "]"<<std::endl;
      }
    }
virtual void gambit::ModelParameters::print () const [inline, virtual]
Definition at line 85 of file ModelParameters.hpp.
References _values.
{
      std::cout << "ModelParameters: Printing: "<<std::endl;
      for (std::map<std::string,double>::const_iterator it=_values.begin();it!=_values.end();it++){
        std::cout << "parameter: " << it->first << "; value: "<<it->second<<std::endl ;
      }
    }
virtual void gambit::ModelParameters::redefineValue (std::string const & name, double const & v, double const & low, double const & high) [inline, virtual]
Definition at line 58 of file ModelParameters.hpp.
References _defineValue(), and assert_contains().
{
      assert_contains(name);
      _defineValue(name,v,low,high);
    }
virtual void gambit::ModelParameters::setValue (std::string const & inkey, double const & value) [inline, virtual]
Definition at line 70 of file ModelParameters.hpp.
References _values, assert_contains(), and gambit::ModelParametersBase::updateVersion().
{
      assert_contains(inkey);
      this->updateVersion();
      _values[inkey]=value;
    }
virtual void gambit::ModelParameters::setValue (std::string const & inkey, double const & value) [inline, virtual]
Definition at line 51 of file ModelParameters.hpp.
References _values, assert_contains(), and gambit::ModelParametersBase::updateVersion().
{
      assert_contains(inkey);
      this->updateVersion();
      _values[inkey]=value;
    }
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & strm, ModelParameters & me) [friend]
Definition at line 92 of file ModelParameters.hpp.
{
      strm << "ModelParameters: Printing: "<<std::endl;
      for (std::map<std::string,double>::const_iterator it=me._values.begin();it!=me._values.end();it++){
        strm << "parameter: " << it->first << " value: "<<it->second ;
      }
      return strm;
    }
std::ostream& operator<< (std::ostream & strm, ModelParameters & me) [friend]
Definition at line 81 of file ModelParameters.hpp.
{
      strm << "ModelParameters: Printing: "<<std::endl;
      for (std::map<std::string,double>::const_iterator it=me._values.begin();it!=me._values.end();it++){
        strm << "parameter: " << it->first << " value: "<<it->second ;
        strm << " range: [" << me._rangelow.at(it->first) << ",";
        strm << me._rangehigh.at(it->first) << "]"<<std::endl;
      }
      return strm;
    }
Member Data Documentation
std::map<std::string,double> gambit::ModelParameters::_rangehigh [private]
Definition at line 93 of file ModelParameters.hpp.
Referenced by _defineValue(), getRange(), and print().
std::map<std::string,double> gambit::ModelParameters::_rangelow [private]
Definition at line 92 of file ModelParameters.hpp.
Referenced by _defineValue(), getRange(), and print().
std::map< std::string, double > gambit::ModelParameters::_values [private]
Definition at line 100 of file ModelParameters.hpp.
Referenced by _definePar(), _defineValue(), assert_contains(), getKeys(), getValue(), operator[](), print(), and setValue().
The documentation for this class was generated from the following files:
ModelBit/include/ModelParameters.hpp
ModelBit/include/orig_include/ModelParameters.hpp