GAMBIT: GAMBIT::Jet Class Reference
GAMBIT::Jet Class Reference
Simple jet class, encapsulating a momentum 4-vector and with some extra b-tag info.
#include <Jet.hpp>
Public Member Functions
Constructors
Jet (const P4 &mom, bool isB=false)
Constructor for a light jet without explicit constituents.
Jet (double px, double py, double pz, double E, bool isB=false)
"Cartesian" constructor
Momentum
const P4 & mom () const
Get the 4 vector.
void setMom (const P4 &p4)
Set the 4 vector.
Convenience mapping of a few popular momentum properties
double eta () const
double rap () const
double phi () const
double E () const
double pT2 () const
double pT () const
Tagging
bool isBJet () const
Is this particle connected to the hard process or from a hadron/tau decay?
void setBJet (bool isb=true)
Set promptness.
Private Attributes
P4 _p4
Momentum vector.
bool _isB
B tag.
Detailed Description
Simple jet class, encapsulating a momentum 4-vector and with some extra b-tag info.
Definition at line 10 of file Jet.hpp.
Constructor & Destructor Documentation
GAMBIT::Jet::Jet (const P4 & mom, bool isB = false) [inline]
Constructor for a light jet without explicit constituents.
Definition at line 17 of file Jet.hpp.
      : _p4(mom), _isB(isB) {  }
GAMBIT::Jet::Jet (double px, double py, double pz, double E, bool isB = false) [inline]
"Cartesian" constructor
Definition at line 21 of file Jet.hpp.
      : _p4(px, py, pz, E), _isB(isB) {  }
Member Function Documentation
double GAMBIT::Jet::E () const [inline]
Definition at line 39 of file Jet.hpp.
References GAMBIT::P4::E(), and mom().
{ return mom().E(); }
double GAMBIT::Jet::eta () const [inline]
Definition at line 36 of file Jet.hpp.
References GAMBIT::P4::eta(), and mom().
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze().
{ return mom().eta(); }
bool GAMBIT::Jet::isBJet () const [inline]
Is this particle connected to the hard process or from a hadron/tau decay?
Definition at line 51 of file Jet.hpp.
References _isB.
{ return _isB; }
const P4& GAMBIT::Jet::mom () const [inline]
Get the 4 vector.
Definition at line 30 of file Jet.hpp.
References _p4.
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze(), E(), eta(), phi(), pT(), pT2(), and rap().
{ return _p4; }
double GAMBIT::Jet::phi () const [inline]
Definition at line 38 of file Jet.hpp.
References mom(), and GAMBIT::P4::phi().
{ return mom().phi(); }
double GAMBIT::Jet::pT () const [inline]
Definition at line 41 of file Jet.hpp.
References mom(), and GAMBIT::P4::pT().
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze().
{ return mom().pT(); }
double GAMBIT::Jet::pT2 () const [inline]
Definition at line 40 of file Jet.hpp.
References mom(), and GAMBIT::P4::pT2().
Referenced by GAMBIT::_cmpPtDesc().
{ return mom().pT2(); }
double GAMBIT::Jet::rap () const [inline]
Definition at line 37 of file Jet.hpp.
References mom(), and GAMBIT::P4::rap().
{ return mom().rap(); }
void GAMBIT::Jet::setBJet (bool isb = true) [inline]
Set promptness.
Definition at line 53 of file Jet.hpp.
References _isB.
{ _isB = isb; }
void GAMBIT::Jet::setMom (const P4 & p4) [inline]
Set the 4 vector.
Definition at line 32 of file Jet.hpp.
References _p4.
{ _p4 = p4; }
Member Data Documentation
bool GAMBIT::Jet::_isB [private]
B tag.
Definition at line 63 of file Jet.hpp.
Referenced by isBJet(), and setBJet().
P4 GAMBIT::Jet::_p4 [private]
Momentum vector.
Definition at line 61 of file Jet.hpp.
Referenced by mom(), and setMom().
The documentation for this class was generated from the following file:
HEColliderBit/src/Jet.hpp