GAMBIT: GAMBIT::P4 Class Reference
GAMBIT::P4 Class Reference
An alternative 4-momentum class.
#include <Vectors.hpp>
Public Member Functions
Constructors etc.
P4 ()
Default constructor of a null vector.
P4 (double px, double py, double pz, double E)
Constructor from Cartesian/Minkowski coordinates.
P4 (const P4 &v)
Copy constructor.
P4 & operator= (const P4 &v)
Copy assignment operator.
void clear ()
Set the components to zero.
Coordinate setters
void setPx (double px)
Set the px coordinate.
void setPy (double py)
Set the py coordinate.
void setPz (double pz)
Set the pz coordinate.
void setM (double m)
Set the mass.
void setPM (double px, double py, double pz, double m)
Set the p coordinates and mass simultaneously.
void setPE (double px, double py, double pz, double E)
Set the p coordinates and energy simultaneously.
Coordinate getters
double px2 () const
Get px^2.
double px () const
Get px.
double py2 () const
Get py^2.
double py () const
Get py.
double pz2 () const
Get pz^2.
double pz () const
Get pz.
double m2 () const
Get m^2.
double m () const
Get m.
double E2 () const
Get E^2.
double E () const
Get E.
double p2 () const
Get the spatial 3-vector |p|^2.
double p () const
Get the spatial 3-vector |p|.
double rho2 () const
Get the spatial 3-vector |px^2 + py^2|.
double rho () const
Get the spatial 3-vector sqrt|px^2 + py^2|.
double pT2 () const
Get the transverse momentum squared (same as rho2)
double pT () const
Get the transverse momentum (same as rho)
double phi () const
Get the spatial phi.
double theta () const
Get the spatial theta.
double eta () const
Get the spatial vector pseudorapidity.
double rap () const
Get the 4-momentum rapidity.
Calculations w.r.t. other P4 vectors
double dot (const P4 &v) const
Lorentz dot product with the positive metric term on E.
double angleTo (const P4 &v) const
Spatial angle to another P4 vector.
double deltaPhi (const P4 &v) const
Difference in phi between two vectors.
double deltaEta (const P4 &v) const
Difference in pseudorapidity between two vectors.
double deltaRap (const P4 &v) const
Difference in rapidity between two vectors.
double deltaR2_eta (const P4 &v) const
Difference in pseudorapidity-based R^2 between two vectors.
double deltaR_eta (const P4 &v) const
Difference in pseudorapidity-based R between two vectors.
double deltaR2_rap (const P4 &v) const
Difference in rapidity-based R^2 between two vectors.
double deltaR_rap (const P4 &v) const
Difference in rapidity-based R between two vectors.
Self-modifying operators
P4 & operator- ()
P4 & operator+= (const P4 &v)
P4 & operator-= (const P4 &v)
P4 & operator*= (double a)
P4 & operator/= (double a)
Static Public Member Functions
Static methods for vector making
static P4 mkXYZE (double px, double py, double pz, double E)
Make a vector from (px,py,pz,E) coordinates.
static P4 mkXYZM (double px, double py, double pz, double m)
Make a vector from (px,py,pz) coordinates and the mass.
static P4 mkEtaPhiME (double eta, double phi, double mass, double E)
Make a vector from (eta,phi,energy) coordinates and the mass.
static P4 mkRapPhiME (double y, double phi, double mass, double E)
Make a vector from (y,phi,energy) coordinates and the mass.
static P4 mkThetaPhiME (double theta, double phi, double mass, double E)
Make a vector from (theta,phi,energy) coordinates and the mass.
static P4 mkRhoPhiME (double prho, double phi, double mass, double E)
Make a vector from (rho,phi,energy) coordinates and the mass.
Private Attributes
Storage
double _x
double _y
double _z
double _m
Detailed Description
An alternative 4-momentum class.
P4 is a typical 4-momentum class, cf. HepLorentzVector or TLorentzVector with the exception that the data member storage is specifically based on (px, py, pz, m) rather than (px, py, pz, E). This means that there are (or at least should) never be numerical precision problems due to calculations like m^2 = E^2 - p^2 when p^2 >> m^2: m^2 is always well-defined and the "symmetric" calculation is the numerically safe E^2 = p^2 + m^2. This restricts usage to on-shell vectors... which as far as I'm aware is not really a restriction in practice, but please let me know if it is!
Definition at line 78 of file Vectors.hpp.
Constructor & Destructor Documentation
GAMBIT::P4::P4 () [inline]
Default constructor of a null vector.
Definition at line 85 of file Vectors.hpp.
Referenced by mkRapPhiME(), mkRhoPhiME(), mkThetaPhiME(), and mkXYZE().
      : _x(0), _y(0), _z(0), _m(0) {  }
GAMBIT::P4::P4 (double px, double py, double pz, double E) [inline]
Constructor from Cartesian/Minkowski coordinates.
Definition at line 89 of file Vectors.hpp.
References setPE().
{
      setPE(px, py, pz, E);
    }
GAMBIT::P4::P4 (const P4 & v) [inline]
Copy constructor.
Definition at line 94 of file Vectors.hpp.
      : _x(v._x), _y(v._y), _z(v._z), _m(v._m) {  }
Member Function Documentation
double GAMBIT::P4::angleTo (const P4 & v) const [inline]
Spatial angle to another P4 vector.
Definition at line 256 of file Vectors.hpp.
References p(), px(), py(), and pz().
Referenced by GAMBIT::angle().
{ return acos(px()*v.px() + py()*v.py() + pz()*v.pz()) / (p()*v.p()); }
void GAMBIT::P4::clear () [inline]
Set the components to zero.
Definition at line 107 of file Vectors.hpp.
References _m, _x, _y, and _z.
Referenced by GAMBIT::Event::clear().
                 {
      _x = 0;
      _y = 0;
      _z = 0;
      _m = 0;
    }
double GAMBIT::P4::deltaEta (const P4 & v) const [inline]
Difference in pseudorapidity between two vectors.
Definition at line 260 of file Vectors.hpp.
References eta().
Referenced by GAMBIT::deltaEta(), and deltaR2_eta().
{ return fabs(eta() - v.eta()); }
double GAMBIT::P4::deltaPhi (const P4 & v) const [inline]
Difference in phi between two vectors.
Definition at line 258 of file Vectors.hpp.
References phi().
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze(), GAMBIT::deltaPhi(), deltaR2_eta(), and deltaR2_rap().
{ return GAMBIT::deltaPhi(phi(), v.phi()); }
double GAMBIT::P4::deltaR2_eta (const P4 & v) const [inline]
Difference in pseudorapidity-based R^2 between two vectors.
Definition at line 264 of file Vectors.hpp.
References deltaEta(), deltaPhi(), and GAMBIT::sqr().
Referenced by GAMBIT::deltaR2_eta(), and deltaR_eta().
{ return sqr(deltaEta(v)) + sqr(deltaPhi(v)); }
double GAMBIT::P4::deltaR2_rap (const P4 & v) const [inline]
Difference in rapidity-based R^2 between two vectors.
Definition at line 268 of file Vectors.hpp.
References deltaPhi(), deltaRap(), and GAMBIT::sqr().
Referenced by GAMBIT::deltaR2_rap(), and deltaR_rap().
{ return sqr(deltaRap(v)) + sqr(deltaPhi(v)); }
double GAMBIT::P4::deltaR_eta (const P4 & v) const [inline]
Difference in pseudorapidity-based R between two vectors.
Definition at line 266 of file Vectors.hpp.
References deltaR2_eta().
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze(), FastSim::CheckOverlap(), and GAMBIT::deltaR_eta().
{ return sqrt(deltaR2_eta(v)); }
double GAMBIT::P4::deltaR_rap (const P4 & v) const [inline]
Difference in rapidity-based R between two vectors.
Definition at line 270 of file Vectors.hpp.
References deltaR2_rap().
Referenced by GAMBIT::deltaR_rap().
{ return sqrt(deltaR2_rap(v)); }
double GAMBIT::P4::deltaRap (const P4 & v) const [inline]
Difference in rapidity between two vectors.
Definition at line 262 of file Vectors.hpp.
References rap().
Referenced by deltaR2_rap(), and GAMBIT::deltaRap().
{ return fabs(rap() - v.rap()); }
double GAMBIT::P4::dot (const P4 & v) const [inline]
Lorentz dot product with the positive metric term on E.
Definition at line 254 of file Vectors.hpp.
References E(), px(), py(), and pz().
Referenced by GAMBIT::dot().
{ return E()*v.E() - px()*v.px() - py()*v.py() - pz()*v.pz(); }
double GAMBIT::P4::E () const [inline]
Get E.
Definition at line 224 of file Vectors.hpp.
References E2().
Referenced by dot(), GAMBIT::Particle::E(), GAMBIT::Jet::E(), ATLAS_Simple_Response::ElectronResponse(), ATLAS_Simple_Response::MuonResponse(), operator+=(), operator-=(), GAMBIT::p4_to_pseudojet(), ATLAS_Simple_Response::PhotonResponse(), rap(), and GAMBIT::to_str().
{ return sqrt(E2()); }
double GAMBIT::P4::E2 () const [inline]
Get E^2.
Definition at line 222 of file Vectors.hpp.
References _m, p2(), and GAMBIT::sqr().
Referenced by E(), and main().
{ return p2() + sqr(_m); }
double GAMBIT::P4::eta () const [inline]
Get the spatial vector pseudorapidity.
Definition at line 243 of file Vectors.hpp.
References theta().
Referenced by deltaEta(), GAMBIT::Particle::eta(), and GAMBIT::Jet::eta().
{ return -log(tan(0.5 * theta())); } //< Optimise with a trig reln on tan(x/2) to avoid tan(atan(..)/2)?
double GAMBIT::P4::m () const [inline]
Get m.
Definition at line 219 of file Vectors.hpp.
References _m.
Referenced by setM().
{ return _m; }
double GAMBIT::P4::m2 () const [inline]
Get m^2.
Definition at line 217 of file Vectors.hpp.
References _m, and GAMBIT::sqr().
{ return sqr(_m); }
static P4 GAMBIT::P4::mkEtaPhiME (double eta, double phi, double mass, double E) [inline, static]
Make a vector from (eta,phi,energy) coordinates and the mass.
Definition at line 133 of file Vectors.hpp.
References mkThetaPhiME(), and theta().
{
      // eta = -log(tan( 0.5 * theta() ))
      // -> theta = 2 atan(exp(-eta))
      const double theta = 2 * atan(exp(-eta));
      return P4::mkThetaPhiME(theta, phi, mass, E);
    }
static P4 GAMBIT::P4::mkRapPhiME (double y, double phi, double mass, double E) [inline, static]
Make a vector from (y,phi,energy) coordinates and the mass.
Definition at line 141 of file Vectors.hpp.
References P4(), px(), py(), pz(), and GAMBIT::sqr().
{
      // y = 0.5 * (E+pz)/(E-pz)
      // 2y(E-pz) = E + pz
      // -> E = pz (2y + 1)/(2y - 1)
      // -> pz = E (2y - 1)/(2y + 1)
      const double pz = E * (2*y - 1) / (2*y + 1);
      const double prho = sqrt(sqr(E) - sqr(mass) - sqr(pz));
      assert(prho >= 0);
      const double px = prho * cos(phi);
      const double py = prho * sin(phi);
      return P4(px, py, pz, E);
    }
static P4 GAMBIT::P4::mkRhoPhiME (double prho, double phi, double mass, double E) [inline, static]
Make a vector from (rho,phi,energy) coordinates and the mass.
Definition at line 165 of file Vectors.hpp.
References P4(), px(), py(), pz(), and GAMBIT::sqr().
{
      assert(prho >= 0);
      const double px = prho * cos(phi);
      const double py = prho * sin(phi);
      const double pz = sqrt(sqr(E) - sqr(mass) - sqr(prho));
      return P4(px, py, pz, E);
    }
static P4 GAMBIT::P4::mkThetaPhiME (double theta, double phi, double mass, double E) [inline, static]
Make a vector from (theta,phi,energy) coordinates and the mass.
Definition at line 155 of file Vectors.hpp.
References p(), P4(), px(), py(), pz(), and GAMBIT::sqr().
Referenced by mkEtaPhiME().
{
      const double p = sqrt( sqr(E) - sqr(mass) );
      const double pz = p * cos(theta);
      const double prho = p * sin(theta);
      const double px = prho * cos(phi);
      const double py = prho * sin(phi);
      return P4(px, py, pz, E);
    }
static P4 GAMBIT::P4::mkXYZE (double px, double py, double pz, double E) [inline, static]
Make a vector from (px,py,pz,E) coordinates.
Definition at line 121 of file Vectors.hpp.
References P4().
{
      return P4(px, py, pz, E);
    }
static P4 GAMBIT::P4::mkXYZM (double px, double py, double pz, double m) [inline, static]
Make a vector from (px,py,pz) coordinates and the mass.
Definition at line 126 of file Vectors.hpp.
References setPM().
{
      P4 rtn;
      rtn.setPM(px, py, pz, m);
      return rtn;
    }
P4& GAMBIT::P4::operator*= (double a) [inline]
Definition at line 279 of file Vectors.hpp.
References _m, _x, _y, and _z.
{ _x *= a; _y *= a; _z *= a; _m *= a; return *this; }
P4& GAMBIT::P4::operator+= (const P4 & v) [inline]
Definition at line 277 of file Vectors.hpp.
References _m, _x, _y, _z, E(), p2(), px(), py(), pz(), and GAMBIT::sqr().
{ double e = E() + v.E(); _x += v.px(); _y += v.py(); _z += v.pz(); _m = sqrt(sqr(e) - p2()); return *this; }
P4& GAMBIT::P4::operator- () [inline]
Definition at line 276 of file Vectors.hpp.
References _x, _y, and _z.
{ _x = -_x; _y = -_y; _z = -_z; return *this; }
P4& GAMBIT::P4::operator-= (const P4 & v) [inline]
Definition at line 278 of file Vectors.hpp.
References _m, _x, _y, _z, E(), p2(), px(), py(), pz(), and GAMBIT::sqr().
{ double e = E() - v.E(); _x -= v.px(); _y -= v.py(); _z -= v.pz(); _m = sqrt(sqr(e) - p2()); return *this; }
P4& GAMBIT::P4::operator/= (double a) [inline]
Definition at line 280 of file Vectors.hpp.
References _m, _x, _y, and _z.
{ _x /= a; _y /= a; _z /= a; _m /= a; return *this; }
P4& GAMBIT::P4::operator= (const P4 & v) [inline]
Copy assignment operator.
Definition at line 98 of file Vectors.hpp.
References _m, _x, _y, and _z.
{
      _x = v._x;
      _y = v._y;
      _z = v._z;
      _m = v._m;
      return *this;
    }
double GAMBIT::P4::p () const [inline]
Get the spatial 3-vector |p|.
Definition at line 228 of file Vectors.hpp.
References p2().
Referenced by angleTo(), mkThetaPhiME(), and setPE().
{ return sqrt(p2()); }
double GAMBIT::P4::p2 () const [inline]
Get the spatial 3-vector |p|^2.
Definition at line 226 of file Vectors.hpp.
References px(), py(), pz(), and GAMBIT::sqr().
Referenced by E2(), main(), operator+=(), operator-=(), p(), and theta().
{ return sqr(px()) + sqr(py()) + sqr(pz()); }
double GAMBIT::P4::phi () const [inline]
Get the spatial phi.
Definition at line 239 of file Vectors.hpp.
References px(), py(), and rho2().
Referenced by deltaPhi(), GAMBIT::Particle::phi(), and GAMBIT::Jet::phi().
{ if (rho2() == 0) return 0; else return atan(py()/px()); }
double GAMBIT::P4::pT () const [inline]
Get the transverse momentum (same as rho)
Definition at line 236 of file Vectors.hpp.
References rho().
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze(), GAMBIT::Event::met(), GAMBIT::Particle::pT(), and GAMBIT::Jet::pT().
{ return rho(); }
double GAMBIT::P4::pT2 () const [inline]
Get the transverse momentum squared (same as rho2)
Definition at line 234 of file Vectors.hpp.
References rho2().
Referenced by GAMBIT::Particle::pT2(), and GAMBIT::Jet::pT2().
{ return rho2(); }
double GAMBIT::P4::px () const [inline]
Get px.
Definition at line 207 of file Vectors.hpp.
References _x.
Referenced by angleTo(), dot(), ATLAS_Simple_Response::ElectronResponse(), mkRapPhiME(), mkRhoPhiME(), mkThetaPhiME(), ATLAS_Simple_Response::MuonResponse(), operator+=(), operator-=(), p2(), GAMBIT::p4_to_pseudojet(), phi(), ATLAS_Simple_Response::PhotonResponse(), rho2(), setPx(), and GAMBIT::to_str().
{ return _x; }
double GAMBIT::P4::px2 () const [inline]
Get px^2.
Definition at line 205 of file Vectors.hpp.
References _x, and GAMBIT::sqr().
{ return sqr(_x); }
double GAMBIT::P4::py () const [inline]
Get py.
Definition at line 211 of file Vectors.hpp.
References _y.
Referenced by angleTo(), dot(), ATLAS_Simple_Response::ElectronResponse(), mkRapPhiME(), mkRhoPhiME(), mkThetaPhiME(), ATLAS_Simple_Response::MuonResponse(), operator+=(), operator-=(), p2(), GAMBIT::p4_to_pseudojet(), phi(), ATLAS_Simple_Response::PhotonResponse(), rho2(), setPy(), and GAMBIT::to_str().
{ return _y; }
double GAMBIT::P4::py2 () const [inline]
Get py^2.
Definition at line 209 of file Vectors.hpp.
References _y, and GAMBIT::sqr().
{ return sqr(_y); }
double GAMBIT::P4::pz () const [inline]
Get pz.
Definition at line 215 of file Vectors.hpp.
References _z.
Referenced by angleTo(), dot(), ATLAS_Simple_Response::ElectronResponse(), mkRapPhiME(), mkRhoPhiME(), mkThetaPhiME(), ATLAS_Simple_Response::MuonResponse(), operator+=(), operator-=(), p2(), GAMBIT::p4_to_pseudojet(), ATLAS_Simple_Response::PhotonResponse(), rap(), setPz(), theta(), and GAMBIT::to_str().
{ return _z; }
double GAMBIT::P4::pz2 () const [inline]
Get pz^2.
Definition at line 213 of file Vectors.hpp.
References _z, and GAMBIT::sqr().
{ return sqr(_z); }
double GAMBIT::P4::rap () const [inline]
Get the 4-momentum rapidity.
Definition at line 245 of file Vectors.hpp.
References E(), and pz().
Referenced by deltaRap(), GAMBIT::Particle::rap(), and GAMBIT::Jet::rap().
{ return 0.5 * (E() + pz()) / (E() - pz()); }
double GAMBIT::P4::rho () const [inline]
Get the spatial 3-vector sqrt|px^2 + py^2|.
Definition at line 232 of file Vectors.hpp.
References rho2().
Referenced by ATLAS_Simple_Response::MuonResponse(), pT(), and theta().
{ return sqrt(rho2()); }
double GAMBIT::P4::rho2 () const [inline]
Get the spatial 3-vector |px^2 + py^2|.
Definition at line 230 of file Vectors.hpp.
References px(), py(), and GAMBIT::sqr().
Referenced by phi(), pT2(), and rho().
{ return sqr(px()) + sqr(py()); }
void GAMBIT::P4::setM (double m) [inline]
Set the mass.
Definition at line 186 of file Vectors.hpp.
References _m, and m().
Referenced by setPE(), and setPM().
{ _m = m; }
void GAMBIT::P4::setPE (double px, double py, double pz, double E) [inline]
Set the p coordinates and energy simultaneously.
Definition at line 193 of file Vectors.hpp.
References p(), setM(), setPx(), setPy(), setPz(), and GAMBIT::sqr().
Referenced by P4().
{
      setPx(px); setPy(py); setPz(pz);
      setM(sqrt( sqr(E) - sqr(p()) ));
    }
void GAMBIT::P4::setPM (double px, double py, double pz, double m) [inline]
Set the p coordinates and mass simultaneously.
Definition at line 188 of file Vectors.hpp.
References setM(), setPx(), setPy(), and setPz().
Referenced by mkXYZM().
{
      setPx(px); setPy(py); setPz(pz);
      setM(m);
    }
void GAMBIT::P4::setPx (double px) [inline]
Set the px coordinate.
Definition at line 180 of file Vectors.hpp.
References _x, and px().
Referenced by setPE(), and setPM().
{ _x = px; }
void GAMBIT::P4::setPy (double py) [inline]
Set the py coordinate.
Definition at line 182 of file Vectors.hpp.
References _y, and py().
Referenced by setPE(), and setPM().
{ _y = py; }
void GAMBIT::P4::setPz (double pz) [inline]
Set the pz coordinate.
Definition at line 184 of file Vectors.hpp.
References _z, and pz().
Referenced by setPE(), and setPM().
{ _z = pz; }
double GAMBIT::P4::theta () const [inline]
Get the spatial theta.
Definition at line 241 of file Vectors.hpp.
References p2(), pz(), and rho().
Referenced by eta(), and mkEtaPhiME().
{ if (p2() == 0) return 0; else if (pz() == 0) return M_PI; else return atan(rho()/pz()); }
Member Data Documentation
double GAMBIT::P4::_m [private]
Definition at line 287 of file Vectors.hpp.
Referenced by clear(), E2(), m(), m2(), operator*=(), operator+=(), operator-=(), operator/=(), operator=(), and setM().
double GAMBIT::P4::_x [private]
Definition at line 287 of file Vectors.hpp.
Referenced by clear(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), px(), px2(), and setPx().
double GAMBIT::P4::_y [private]
Definition at line 287 of file Vectors.hpp.
Referenced by clear(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), py(), py2(), and setPy().
double GAMBIT::P4::_z [private]
Definition at line 287 of file Vectors.hpp.
Referenced by clear(), operator*=(), operator+=(), operator-(), operator-=(), operator/=(), operator=(), pz(), pz2(), and setPz().
The documentation for this class was generated from the following file:
HEColliderBit/src/Vectors.hpp