GAMBIT: GAMBIT::Backend::BackendBitBase Class Reference
GAMBIT::Backend::BackendBitBase Class Reference
Base class for interface with external codes.
#include <backend-common.hpp>
Public Member Functions
BackendBitBase ()
virtual ~BackendBitBase ()
virtual void loadLib ()=0
virtual void unLoadLib ()=0
virtual void initialize ()=0
virtual void finalize ()=0
template<typename TagT >
FortranFunctor< TagT > & Function ()
template<typename TagT >
void SetUserVariable (typename VarType< TagT >::type const &value)
template<typename TagT >
VarType< TagT >::type const & GetUserVariable () const
Protected Attributes
bool _libState
string _libName
void * pHandle
Private Member Functions
virtual void checkDLStatus () const =0
Detailed Description
Base class for interface with external codes.
Author:
Are Raklev
Anders Kvellestad 2012-11-08
Definition at line 35 of file backend-common.hpp.
Constructor & Destructor Documentation
GAMBIT::Backend::BackendBitBase::BackendBitBase () [inline]
Definition at line 39 of file backend-common.hpp.
: _libState(false) {}
virtual GAMBIT::Backend::BackendBitBase::~BackendBitBase () [inline, virtual]
Definition at line 42 of file backend-common.hpp.
{}
Member Function Documentation
virtual void GAMBIT::Backend::BackendBitBase::checkDLStatus () const [private, pure virtual]
Referenced by GetUserVariable(), and SetUserVariable().
virtual void GAMBIT::Backend::BackendBitBase::finalize () [pure virtual]
template<typename TagT > FortranFunctor<TagT>& GAMBIT::Backend::BackendBitBase::Function () [inline]
Definition at line 58 of file backend-common.hpp.
References pHandle.
{
            return FortranFunctor<TagT>::instance(pHandle);
          }
template<typename TagT > VarType<TagT>::type const& GAMBIT::Backend::BackendBitBase::GetUserVariable () const [inline]
Definition at line 74 of file backend-common.hpp.
References checkDLStatus(), and pHandle.
{
                std::string symbolName = FortranFunctor<TagT>::FortranSymbolName(VarName<TagT>::name(), VarName<TagT>::module());
                cout << symbolName << endl;
                typename VarType<TagT>::type * varPtr = static_cast<typename VarType<TagT>::type *>(dlsym(pHandle, symbolName.c_str()));
                checkDLStatus();
                return *varPtr;
          }
virtual void GAMBIT::Backend::BackendBitBase::initialize () [pure virtual]
virtual void GAMBIT::Backend::BackendBitBase::loadLib () [pure virtual]
template<typename TagT > void GAMBIT::Backend::BackendBitBase::SetUserVariable (typename VarType< TagT >::type const & value) [inline]
Definition at line 64 of file backend-common.hpp.
References checkDLStatus(), and pHandle.
{
                std::string symbolName = FortranFunctor<TagT>::FortranSymbolName(VarName<TagT>::name(), VarName<TagT>::module());
                cout << symbolName << endl;
                typename VarType<TagT>::type * varPtr = static_cast<typename VarType<TagT>::type *>(dlsym(pHandle, symbolName.c_str()));
                checkDLStatus();
                *varPtr = value;
          }
virtual void GAMBIT::Backend::BackendBitBase::unLoadLib () [pure virtual]
Member Data Documentation
string GAMBIT::Backend::BackendBitBase::_libName [protected]
Definition at line 85 of file backend-common.hpp.
bool GAMBIT::Backend::BackendBitBase::_libState [protected]
Definition at line 84 of file backend-common.hpp.
void* GAMBIT::Backend::BackendBitBase::pHandle [protected]
Definition at line 86 of file backend-common.hpp.
Referenced by Function(), GetUserVariable(), and SetUserVariable().
The documentation for this class was generated from the following file:
Utils/include/backend-common.hpp