GAMBIT: GAMBIT::Particle Class Reference
GAMBIT::Particle Class Reference
Simple particle class, encapsulating a momentum 4-vector and adding some extra ID info.
#include <Particle.hpp>
Public Member Functions
Constructors
Particle ()
Default constructor.
Particle (double px, double py, double pz, double E, int pdgid)
"Cartesian" constructor
Particle (const P4 &mom, int pdgid)
4-mom + PDG ID constructor
Particle (const Particle &p)
Copy constructor.
Particle (const Particle *p)
Copy constructor from a pointer.
Particle & operator= (const Particle &p)
Copy assignment operator.
Momentum
const P4 & mom () const
Get the 4 vector.
void setMom (const P4 &p4)
Set the 4 vector.
Convenience mapping of a few popular momentum properties
double eta () const
double rap () const
double phi () const
double E () const
double pT2 () const
double pT () const
Promptness
bool isPrompt () const
Is this particle connected to the hard process or from a hadron/tau decay?
void setPrompt (bool isprompt=true)
Set promptness.
Particle ID
int pid () const
Get PDG ID code.
void setPid (int pid)
Set PDG ID code.
Private Attributes
P4 _p4
Momentum vector.
int _pdgId
PDG ID code.
int _prompt
Promptness flag.
Detailed Description
Simple particle class, encapsulating a momentum 4-vector and adding some extra ID info.
Definition at line 10 of file Particle.hpp.
Constructor & Destructor Documentation
GAMBIT::Particle::Particle () [inline]
Default constructor.
Definition at line 17 of file Particle.hpp.
      : _pdgId(0) {  }
GAMBIT::Particle::Particle (double px, double py, double pz, double E, int pdgid) [inline]
"Cartesian" constructor
Definition at line 21 of file Particle.hpp.
      : _p4(px, py, pz, E), _pdgId(pdgid) {  }
GAMBIT::Particle::Particle (const P4 & mom, int pdgid) [inline]
4-mom + PDG ID constructor
Definition at line 25 of file Particle.hpp.
      : _p4(mom), _pdgId(pdgid) {  }
GAMBIT::Particle::Particle (const Particle & p) [inline]
Copy constructor.
Definition at line 29 of file Particle.hpp.
      : _p4(p.mom()), _pdgId(p.pid()) {  }
GAMBIT::Particle::Particle (const Particle * p) [inline]
Copy constructor from a pointer.
Definition at line 33 of file Particle.hpp.
      : _p4(p->mom()), _pdgId(p->pid()) {  }
Member Function Documentation
double GAMBIT::Particle::E () const [inline]
Definition at line 59 of file Particle.hpp.
References GAMBIT::P4::E(), and mom().
{ return mom().E(); }
double GAMBIT::Particle::eta () const [inline]
Definition at line 56 of file Particle.hpp.
References GAMBIT::P4::eta(), and mom().
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze().
{ return mom().eta(); }
bool GAMBIT::Particle::isPrompt () const [inline]
Is this particle connected to the hard process or from a hadron/tau decay?
Definition at line 71 of file Particle.hpp.
References _prompt.
Referenced by GAMBIT::Event::addParticle().
{ return _prompt; }
const P4& GAMBIT::Particle::mom () const [inline]
Get the 4 vector.
Definition at line 50 of file Particle.hpp.
References _p4.
Referenced by FastSim::CheckOverlap(), E(), ATLAS_Simple_Response::ElectronResponse(), eta(), main(), ATLAS_Simple_Response::MuonResponse(), operator=(), phi(), ATLAS_Simple_Response::PhotonResponse(), pT(), pT2(), and rap().
{ return _p4; }
Particle& GAMBIT::Particle::operator= (const Particle & p) [inline]
Copy assignment operator.
Definition at line 37 of file Particle.hpp.
References _p4, _pdgId, mom(), and pid().
{
      _p4 = p.mom();
      _pdgId = p.pid();
      return *this;
    }
double GAMBIT::Particle::phi () const [inline]
Definition at line 58 of file Particle.hpp.
References mom(), and GAMBIT::P4::phi().
{ return mom().phi(); }
int GAMBIT::Particle::pid () const [inline]
Get PDG ID code.
Definition at line 82 of file Particle.hpp.
References _pdgId.
Referenced by GAMBIT::Event::addParticle(), operator=(), and setPid().
{ return _pdgId; }
double GAMBIT::Particle::pT () const [inline]
Definition at line 61 of file Particle.hpp.
References mom(), and GAMBIT::P4::pT().
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze().
{ return mom().pT(); }
double GAMBIT::Particle::pT2 () const [inline]
Definition at line 60 of file Particle.hpp.
References mom(), and GAMBIT::P4::pT2().
{ return mom().pT2(); }
double GAMBIT::Particle::rap () const [inline]
Definition at line 57 of file Particle.hpp.
References mom(), and GAMBIT::P4::rap().
{ return mom().rap(); }
void GAMBIT::Particle::setMom (const P4 & p4) [inline]
Set the 4 vector.
Definition at line 52 of file Particle.hpp.
References _p4.
Referenced by ATLAS_Simple_Response::ElectronResponse(), ATLAS_Simple_Response::MuonResponse(), and ATLAS_Simple_Response::PhotonResponse().
{ _p4 = p4; }
void GAMBIT::Particle::setPid (int pid) [inline]
Set PDG ID code.
Definition at line 84 of file Particle.hpp.
References _pdgId, and pid().
{ _pdgId = pid; }
void GAMBIT::Particle::setPrompt (bool isprompt = true) [inline]
Set promptness.
Definition at line 73 of file Particle.hpp.
References _prompt.
{ _prompt = isprompt; }
Member Data Documentation
P4 GAMBIT::Particle::_p4 [private]
Momentum vector.
Definition at line 92 of file Particle.hpp.
Referenced by mom(), operator=(), and setMom().
int GAMBIT::Particle::_pdgId [private]
PDG ID code.
Definition at line 94 of file Particle.hpp.
Referenced by operator=(), pid(), and setPid().
int GAMBIT::Particle::_prompt [private]
Promptness flag.
Definition at line 96 of file Particle.hpp.
Referenced by isPrompt(), and setPrompt().
The documentation for this class was generated from the following file:
HEColliderBit/src/Particle.hpp