GAMBIT: gambit::ModelParametersBase Class Reference
gambit::ModelParametersBase Class Reference
virtual base class for model parameters.
#include <ModelParametersBase.hpp>
Public Member Functions
u_longlong getVersion () const
ModelParametersBase ()
u_longlong getVersion () const
ModelParametersBase ()
Protected Member Functions
virtual ~ModelParametersBase ()
void updateVersion ()
virtual ~ModelParametersBase ()
void updateVersion ()
Private Attributes
u_longlong _paramversion
Detailed Description
virtual base class for model parameters.
This class is only taking care of the version
Author:
Johan Lundberg
Date:
July-September 2011
Definition at line 16 of file ModelParametersBase.hpp.
Constructor & Destructor Documentation
gambit::ModelParametersBase::ModelParametersBase () [inline]
Definition at line 21 of file ModelParametersBase.hpp.
References GAMBIT_MSG_DEBUG.
:_paramversion(1) {GAMBIT_MSG_DEBUG("hi.");}
virtual gambit::ModelParametersBase::~ModelParametersBase () [inline, protected, virtual]
Definition at line 23 of file ModelParametersBase.hpp.
References GAMBIT_MSG_DEBUG.
{GAMBIT_MSG_DEBUG("bye.");}
gambit::ModelParametersBase::ModelParametersBase () [inline]
Definition at line 21 of file ModelParametersBase.hpp.
References GAMBIT_MSG_DEBUG.
:_paramversion(1) {GAMBIT_MSG_DEBUG("hi.");}
virtual gambit::ModelParametersBase::~ModelParametersBase () [inline, protected, virtual]
Definition at line 23 of file ModelParametersBase.hpp.
References GAMBIT_MSG_DEBUG.
{GAMBIT_MSG_DEBUG("bye.");}
Member Function Documentation
u_longlong gambit::ModelParametersBase::getVersion () const [inline]
Definition at line 18 of file ModelParametersBase.hpp.
References _paramversion.
{
      return _paramversion ;
    }
u_longlong gambit::ModelParametersBase::getVersion () const [inline]
Definition at line 18 of file ModelParametersBase.hpp.
References _paramversion.
{
      return _paramversion ;
    }
void gambit::ModelParametersBase::updateVersion () [inline, protected]
Definition at line 24 of file ModelParametersBase.hpp.
References _paramversion.
{ _paramversion++;}
void gambit::ModelParametersBase::updateVersion () [inline, protected]
Definition at line 24 of file ModelParametersBase.hpp.
References _paramversion.
Referenced by gambit::ModelParameters::_definePar(), gambit::ModelParameters::_defineValue(), and gambit::ModelParameters::setValue().
{ _paramversion++;}
Member Data Documentation
u_longlong gambit::ModelParametersBase::_paramversion [private]
Definition at line 26 of file ModelParametersBase.hpp.
Referenced by getVersion(), and updateVersion().
The documentation for this class was generated from the following files:
ModelBit/include/ModelParametersBase.hpp
ModelBit/include/orig_include/ModelParametersBase.hpp