GAMBIT: GAMBIT::functor Class Reference
GAMBIT::functor Class Reference
Function wrapper (functor) base class.
#include <functors.hpp>
Public Member Functions
virtual ~functor ()
Empty virtual destructor to make polymorphic.
virtual void calculate ()
Empty virtual calculate()
void setVersion (str ver)
Set method for version.
void setStatus (int stat)
Set method for status.
std::vector< sspair > backend_conditional_dependencies (str req, str type, str be, str ver)
Getter for backend-specific conditional dependencies (4-string version)
std::vector< sspair > backend_conditional_dependencies (str req, str type, str be)
Getter for backend-specific conditional dependencies (3-string version)
std::vector< sspair > backend_conditional_dependencies (functor *be_functor)
Getter for backend-specific conditional dependencies (backend functor pointer version)
std::vector< sspair > model_conditional_dependencies (str model)
Getter for model-specific conditional dependencies.
void resolveDependency (functor *dep_functor)
Resolve a dependency using a pointer to another functor object.
void resolveBackendReq (functor *be_functor)
Resolve a backend requirement using a pointer to another functor object.
str name ()
Identification methods.
str capability ()
str type ()
str origin ()
str version ()
int status ()
sspair quantity ()
std::vector< sspair > dependencies ()
Getters for unconditional dependencies, backend requirements and permitted backends.
std::vector< sspair > backendreqs ()
std::vector< sspair > backendspermitted (sspair quant)
Public Attributes
bool needs_recalculating
Needs recalculating or not? (Externally modifiable)
Protected Attributes
str myName
str myCapability
str myType
str myOrigin
str myVersion
std::vector< sspair > myDependencies
std::vector< sspair > myBackendReqs
int myStatus
Status: 0 disabled, 1 available (default), 2 active (required for dependency resolution)
std::map< std::vector< str >
, std::vector< sspair > > myBackendConditionalDependencies
Map from (vector with 4 strings: backend req, type, backend, version) to (vector of {conditional dependency-type} pairs)
std::map< str, std::vector
< sspair > > myModelConditionalDependencies
Map from models to (vector of {conditional dependency-type} pairs)
std::map< str, str > backendreq_types
Map from backend requirements to their required types.
std::map< sspair, void(*)(functor *)> dependency_map
Map from (dependency-type pairs) to (pointers to templated void functions that set dependency functor pointers)
std::map< sspair, void(*)(functor *)> backendreq_map
Map from (backend requirement-type pairs) to (pointers to templated void functions that set backend requirement functor pointers)
std::map< sspair, std::vector
< sspair > > permitted_map
Map from (backend requirement-type pairs) to (vector of permitted {backend-version} pairs)
Detailed Description
Function wrapper (functor) base class.
Definition at line 39 of file functors.hpp.
Constructor & Destructor Documentation
virtual GAMBIT::functor::~functor () [inline, virtual]
Empty virtual destructor to make polymorphic.
Definition at line 45 of file functors.hpp.
{}
Member Function Documentation
std::vector<sspair> GAMBIT::functor::backend_conditional_dependencies (str req, str type, str be, str ver) [inline]
Getter for backend-specific conditional dependencies (4-string version)
Definition at line 87 of file functors.hpp.
References myBackendConditionalDependencies.
Referenced by backend_conditional_dependencies().
      {
        std::vector<sspair> generic_deps, specific_deps, total_deps;
        std::vector<str> quad;
        quad.push_back(req);
        quad.push_back(type);
        quad.push_back(be);
        quad.push_back(ver);
        //Check first what conditional dependencies exist for all versions of this backend
        if (ver != "any")
        {
          generic_deps = backend_conditional_dependencies(req, type, be, "any");
        }
        //Now see if there are any for this specific version
        if (myBackendConditionalDependencies.find(quad) != myBackendConditionalDependencies.end())
        {
          specific_deps = myBackendConditionalDependencies[quad];
        }
        //Now put them together
        total_deps.reserve(generic_deps.size() + specific_deps.size());
        total_deps.insert(total_deps.end(), generic_deps.begin(), generic_deps.end());
        total_deps.insert(total_deps.end(), specific_deps.begin(), specific_deps.end());
        return total_deps;
      }
std::vector<sspair> GAMBIT::functor::backend_conditional_dependencies (functor * be_functor) [inline]
Getter for backend-specific conditional dependencies (backend functor pointer version)
Definition at line 119 of file functors.hpp.
References backend_conditional_dependencies(), capability(), origin(), type(), and version().
      {
        return backend_conditional_dependencies (be_functor->capability(), be_functor->type(),
         be_functor->origin(), be_functor->version());
      }
std::vector<sspair> GAMBIT::functor::backend_conditional_dependencies (str req, str type, str be) [inline]
Getter for backend-specific conditional dependencies (3-string version)
Definition at line 113 of file functors.hpp.
References backend_conditional_dependencies().
      {
        return backend_conditional_dependencies(req, type, be, "any");
      }
std::vector<sspair> GAMBIT::functor::backendreqs () [inline]
Definition at line 72 of file functors.hpp.
References myBackendReqs.
{ return myBackendReqs; }
std::vector<sspair> GAMBIT::functor::backendspermitted (sspair quant) [inline]
Definition at line 73 of file functors.hpp.
References permitted_map.
      {
        if (permitted_map.find(quant) != permitted_map.end())
        {
          return permitted_map[quant];
        }
        else
        {
          std::vector<sspair> empty;
          return empty;
        }
      }
virtual void GAMBIT::functor::calculate () [inline, virtual]
Empty virtual calculate()
Reimplemented in GAMBIT::module_functor< TYPE >.
Definition at line 48 of file functors.hpp.
{}
str GAMBIT::functor::capability () [inline]
Definition at line 56 of file functors.hpp.
References myCapability.
Referenced by backend_conditional_dependencies().
{ return myCapability; }
std::vector<sspair> GAMBIT::functor::dependencies () [inline]
Getters for unconditional dependencies, backend requirements and permitted backends.
Definition at line 71 of file functors.hpp.
References myDependencies.
{ return myDependencies; }
std::vector<sspair> GAMBIT::functor::model_conditional_dependencies (str model) [inline]
Getter for model-specific conditional dependencies.
Definition at line 126 of file functors.hpp.
References myModelConditionalDependencies.
      {
        if (myModelConditionalDependencies.find(model) != myModelConditionalDependencies.end())
        {
          return myModelConditionalDependencies[model];
        }
        else
        {
          std::vector<sspair> empty;
          return empty;
        }
      }
str GAMBIT::functor::name () [inline]
Identification methods.
Definition at line 55 of file functors.hpp.
References myName.
Referenced by GAMBIT::module_functor< TYPE >::setBackendConditionalDependencySingular(), and GAMBIT::module_functor< TYPE >::setPermittedBackendSingular().
{ return myName;       }
str GAMBIT::functor::origin () [inline]
Definition at line 58 of file functors.hpp.
References myOrigin.
Referenced by backend_conditional_dependencies(), resolveBackendReq(), GAMBIT::module_functor< TYPE >::setBackendConditionalDependencySingular(), and GAMBIT::module_functor< TYPE >::setPermittedBackendSingular().
{ return myOrigin;     }
sspair GAMBIT::functor::quantity () [inline]
Definition at line 61 of file functors.hpp.
References myCapability, and myType.
Referenced by resolveBackendReq(), and resolveDependency().
{ return std::make_pair(myCapability, myType); }
void GAMBIT::functor::resolveBackendReq (functor * be_functor) [inline]
Resolve a backend requirement using a pointer to another functor object.
FIXME
Todo:
throw a real error here
FIXME
Todo:
throw a real error here
Definition at line 157 of file functors.hpp.
References backendreq_map, myName, myOrigin, origin(), permitted_map, quantity(), and version().
      {
        sspair key (be_functor->quantity());
        //First make sure that the proposed backend function fulfills a known requirement of the module function.
        if (backendreq_map.find(key) != backendreq_map.end())
        {
          sspair proposal (be_functor->origin(), be_functor->version());  //Proposed backend-version pair
          sspair generic_proposal (be_functor->origin(), "any");          //Proposed backend, any version
          if ( //Check for a condition under which the proposed backend function is an acceptable fit for this requirement.
           //Check whether there are have been any permitted backends stated for this requirement (if not, anything goes).
           (permitted_map.find(key) == permitted_map.end()) ||
           //Iterate over the vector of backend-version pairs for this requirement to see if all versions of the
           //proposed backend have been explicitly permitted.
           (std::find(permitted_map[key].begin(), permitted_map[key].end(), generic_proposal) != permitted_map[key].end()) ||
           //Iterate over the vector of backend-version pairs again to see if the specific backend version
           //proposed had been explicitly permitted.
           (std::find(permitted_map[key].begin(), permitted_map[key].end(), proposal) != permitted_map[key].end()) )
          {
            (*backendreq_map[key])(be_functor);   //One of the conditions was met, so do the resolution
          }
          else
          {
            cout << "Error whilst attempting to resolve backend requirement:" << endl;
            cout << "Backend capability " << key.first << " with type " << key.second << "." << endl;
            cout << "required by function "<< myName << " in " << myOrigin << " is not permitted " << endl;
            cout << "to use "<< proposal.first << ", version " << proposal.second << "." << endl;
          }
        }
        else
        {
          cout << "Error whilst attempting to resolve backend requirement:" << endl;
          cout << "Function "<< myName << " in " << myOrigin << " does not require " << endl;
          cout << "backend capability " << key.first << " with type " << key.second << "." << endl;
        }
      }
void GAMBIT::functor::resolveDependency (functor * dep_functor) [inline]
Resolve a dependency using a pointer to another functor object.
FIXME
Todo:
throw a real error here
Definition at line 143 of file functors.hpp.
References dependency_map, myName, myOrigin, and quantity().
      {
        sspair key (dep_functor->quantity());
        if (dependency_map.find(key) == dependency_map.end())
        {
          cout << "Error whilst attempting to resolve dependency:" << endl;
          cout << "Function "<< myName << " in " << myOrigin << " does not depend on " << endl;
          cout << "capability " << key.first << " with type " << key.second << "." << endl;
        }
        else { (*dependency_map[key])(dep_functor); }
      }
void GAMBIT::functor::setStatus (int stat) [inline]
Set method for status.
Definition at line 68 of file functors.hpp.
References myStatus.
{ myStatus = stat; }
void GAMBIT::functor::setVersion (str ver) [inline]
Set method for version.
Definition at line 65 of file functors.hpp.
References myVersion.
{ myVersion = ver; }
int GAMBIT::functor::status () [inline]
Definition at line 60 of file functors.hpp.
References myStatus.
{ return myStatus;     }
str GAMBIT::functor::type () [inline]
Definition at line 57 of file functors.hpp.
References myType.
Referenced by backend_conditional_dependencies(), and GAMBIT::module_functor< TYPE >::setBackendReq().
{ return myType;       }
str GAMBIT::functor::version () [inline]
Definition at line 59 of file functors.hpp.
References myVersion.
Referenced by backend_conditional_dependencies(), and resolveBackendReq().
{ return myVersion;    }
Member Data Documentation
std::map<sspair, void(*)(functor*)> GAMBIT::functor::backendreq_map [protected]
Map from (backend requirement-type pairs) to (pointers to templated void functions that set backend requirement functor pointers)
Definition at line 224 of file functors.hpp.
Referenced by resolveBackendReq(), and GAMBIT::module_functor< TYPE >::setBackendReq().
std::map<str, str> GAMBIT::functor::backendreq_types [protected]
Map from backend requirements to their required types.
Definition at line 216 of file functors.hpp.
Referenced by GAMBIT::module_functor< TYPE >::setBackendConditionalDependencySingular(), GAMBIT::module_functor< TYPE >::setBackendReq(), and GAMBIT::module_functor< TYPE >::setPermittedBackendSingular().
std::map<sspair, void(*)(functor*)> GAMBIT::functor::dependency_map [protected]
Map from (dependency-type pairs) to (pointers to templated void functions that set dependency functor pointers)
Definition at line 220 of file functors.hpp.
Referenced by resolveDependency(), GAMBIT::module_functor< TYPE >::setBackendConditionalDependencySingular(), GAMBIT::module_functor< TYPE >::setDependency(), and GAMBIT::module_functor< TYPE >::setModelConditionalDependency().
std::map< std::vector<str>, std::vector<sspair> > GAMBIT::functor::myBackendConditionalDependencies [protected]
Map from (vector with 4 strings: backend req, type, backend, version) to (vector of {conditional dependency-type} pairs)
Definition at line 210 of file functors.hpp.
Referenced by backend_conditional_dependencies(), and GAMBIT::module_functor< TYPE >::setBackendConditionalDependencySingular().
std::vector<sspair> GAMBIT::functor::myBackendReqs [protected]
Definition at line 204 of file functors.hpp.
Referenced by backendreqs(), and GAMBIT::module_functor< TYPE >::setBackendReq().
str GAMBIT::functor::myCapability [protected]
Definition at line 198 of file functors.hpp.
Referenced by GAMBIT::backend_functor_common< void, ARGS...>::backend_functor_common(), capability(), GAMBIT::module_functor< TYPE >::module_functor(), and quantity().
std::vector<sspair> GAMBIT::functor::myDependencies [protected]
Definition at line 203 of file functors.hpp.
Referenced by dependencies(), and GAMBIT::module_functor< TYPE >::setDependency().
std::map< str, std::vector<sspair> > GAMBIT::functor::myModelConditionalDependencies [protected]
Map from models to (vector of {conditional dependency-type} pairs)
Definition at line 213 of file functors.hpp.
Referenced by model_conditional_dependencies(), and GAMBIT::module_functor< TYPE >::setModelConditionalDependency().
str GAMBIT::functor::myName [protected]
Definition at line 197 of file functors.hpp.
Referenced by GAMBIT::backend_functor_common< void, ARGS...>::backend_functor_common(), GAMBIT::module_functor< TYPE >::module_functor(), name(), resolveBackendReq(), and resolveDependency().
str GAMBIT::functor::myOrigin [protected]
Definition at line 200 of file functors.hpp.
Referenced by GAMBIT::backend_functor_common< void, ARGS...>::backend_functor_common(), GAMBIT::module_functor< TYPE >::module_functor(), origin(), resolveBackendReq(), and resolveDependency().
int GAMBIT::functor::myStatus [protected]
Status: 0 disabled, 1 available (default), 2 active (required for dependency resolution)
Definition at line 207 of file functors.hpp.
Referenced by GAMBIT::backend_functor_common< void, ARGS...>::backend_functor_common(), GAMBIT::module_functor< TYPE >::module_functor(), setStatus(), and status().
str GAMBIT::functor::myType [protected]
Definition at line 199 of file functors.hpp.
Referenced by GAMBIT::backend_functor_common< void, ARGS...>::backend_functor_common(), GAMBIT::module_functor< TYPE >::module_functor(), quantity(), and type().
str GAMBIT::functor::myVersion [protected]
Definition at line 201 of file functors.hpp.
Referenced by GAMBIT::backend_functor_common< void, ARGS...>::backend_functor_common(), setVersion(), and version().
bool GAMBIT::functor::needs_recalculating
Needs recalculating or not? (Externally modifiable)
Definition at line 140 of file functors.hpp.
Referenced by GAMBIT::backend_functor_common< void, ARGS...>::backend_functor_common(), GAMBIT::module_functor< TYPE >::calculate(), GAMBIT::module_functor< TYPE >::module_functor(), GAMBIT::backend_functor< void, ARGS...>::operator()(), and GAMBIT::backend_functor< TYPE, ARGS >::operator()().
std::map< sspair, std::vector<sspair> > GAMBIT::functor::permitted_map [protected]
Map from (backend requirement-type pairs) to (vector of permitted {backend-version} pairs)
Definition at line 227 of file functors.hpp.
Referenced by backendspermitted(), resolveBackendReq(), and GAMBIT::module_functor< TYPE >::setPermittedBackendSingular().
The documentation for this class was generated from the following file:
Utils/include/functors.hpp