GAMBIT: ATLAS_Simple_Response Class Reference
ATLAS_Simple_Response Class Reference
#include <DetectorResponse.hpp>
Public Member Functions
ATLAS_Simple_Response ()
void MuonResponse (Particle &muon)
void PhotonResponse (Particle &ph)
void ElectronResponse (Particle &ele)
void JetResponse (Particle &jet)
Detailed Description
Definition at line 28 of file DetectorResponse.hpp.
Constructor & Destructor Documentation
ATLAS_Simple_Response::ATLAS_Simple_Response ()
Definition at line 13 of file DetectorResponse.cpp.
References DetectorResponse::_electron_resolution, DetectorResponse::_jet_resolution, DetectorResponse::_muon_resolution, and DetectorResponse::_photon_resolution.
{
  _muon_resolution = 0.0005;
  _electron_resolution = 0.12;
  _photon_resolution = 0.1;
  _jet_resolution = 0.5;
}
Member Function Documentation
void ATLAS_Simple_Response::ElectronResponse (Particle & ele) [virtual]
Reimplemented from DetectorResponse.
Definition at line 71 of file DetectorResponse.cpp.
References DetectorResponse::_electron_resolution, DetectorResponse::_rndm, GAMBIT::P4::E(), GAMBIT::Particle::mom(), GAMBIT::P4::px(), GAMBIT::P4::py(), GAMBIT::P4::pz(), and GAMBIT::Particle::setMom().
{
  // smears the momemtum of a electron
  double newpx,newpy,newpz,newe; //,newpt;
  if (electron.mom().E() <= 0)
    return;
  double distr = _rndm.Gaus(0,1);
  double sigma = distr*_electron_resolution*1.0/sqrt(electron.mom().E());
  newpx = electron.mom().px()/(1+sigma);
  newpy = electron.mom().py()/(1+sigma);
  newpz = electron.mom().pz()/(1+sigma);
  newe = electron.mom().E()/(1+sigma);
  P4 newp(newpx,newpy,newpz,newe);
  electron.setMom(newp);
//  electron.mom().setPM(newpx,newpy,newpz,0.0);
//  Particle newelectron(newpx,newpy,newpz,0.0,electron.pid());
//  return newelectron;
}
void ATLAS_Simple_Response::JetResponse (Particle & jet) [virtual]
Reimplemented from DetectorResponse.
Definition at line 96 of file DetectorResponse.cpp.
{
}
void ATLAS_Simple_Response::MuonResponse (Particle & muon) [virtual]
Reimplemented from DetectorResponse.
Definition at line 23 of file DetectorResponse.cpp.
References DetectorResponse::_muon_resolution, DetectorResponse::_rndm, GAMBIT::P4::E(), GAMBIT::Particle::mom(), GAMBIT::P4::px(), GAMBIT::P4::py(), GAMBIT::P4::pz(), GAMBIT::P4::rho(), and GAMBIT::Particle::setMom().
{
  // smears the momemtum of a muon
  double newpx,newpy,newpz,newe; //,newpt;
  double distr = _rndm.Gaus(0,1);
  double sigma = distr*_muon_resolution*muon.mom().rho();
  newpx = muon.mom().px()/(1+sigma);
  newpy = muon.mom().py()/(1+sigma);
  newpz = muon.mom().pz()/(1+sigma);
  newe = muon.mom().E()/(1+sigma);
  P4 newp(newpx,newpy,newpz,newe);
  muon.setMom(newp);
//  muon.mom().setPM(newpx,newpy,newpz,0.1057);
//  Particle newmuon(newpx,newpy,newpz,0.0,muon.pid());
//  return newmuon;
}
void ATLAS_Simple_Response::PhotonResponse (Particle & ph) [virtual]
Reimplemented from DetectorResponse.
Definition at line 47 of file DetectorResponse.cpp.
References DetectorResponse::_photon_resolution, DetectorResponse::_rndm, GAMBIT::P4::E(), GAMBIT::Particle::mom(), GAMBIT::P4::px(), GAMBIT::P4::py(), GAMBIT::P4::pz(), and GAMBIT::Particle::setMom().
{
  // smears the momemtum of a photon
  double newpx,newpy,newpz,newe; //,newpt;
  if (photon.mom().E() <= 0)
    return ;
  double distr = _rndm.Gaus(0,1);
  double sigma = distr*_photon_resolution/sqrt(photon.mom().E());
  newpx = photon.mom().px()/(1+sigma);
  newpy = photon.mom().py()/(1+sigma);
  newpz = photon.mom().pz()/(1+sigma);
  newe = photon.mom().E()/(1+sigma);
  P4 newp(newpx,newpy,newpz,newe);
  photon.setMom(newp);
//  photon.mom().setPM(newpx,newpy,newpz,0.0);
//  Particle newphoton(newpx,newpy,newpz,0.0,photon.pid());
//  return newphoton;
}
The documentation for this class was generated from the following files:
HEColliderBit/src/DetectorResponse.hpp
HEColliderBit/src/DetectorResponse.cpp