GAMBIT: GAMBIT::Backend::Particle Class Reference
GAMBIT::Backend::Particle Class Reference
Particle class.
#include <particle.hpp>
Public Member Functions
Particle (Vector4 momentum, int pdg)
double px () const
double py () const
double pz () const
double e () const
int pdg () const
double m () const
double m2 () const
double pT () const
double theta () const
double phi () const
Private Attributes
Vector4 _p
int _pdg
Detailed Description
Particle class.
Author:
Are Raklev
Anders Kvellestad 2012-11-08
Definition at line 60 of file particle.hpp.
Constructor & Destructor Documentation
GAMBIT::Backend::Particle::Particle (Vector4 momentum, int pdg) [inline]
Definition at line 62 of file particle.hpp.
References _p, _pdg, and pdg().
{
                  _p = momentum;
                  _pdg = pdg;
                }
Member Function Documentation
double GAMBIT::Backend::Particle::e () const [inline]
Definition at line 71 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::e().
{return _p.e();}
double GAMBIT::Backend::Particle::m () const [inline]
Definition at line 74 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::m().
{return _p.m();}
double GAMBIT::Backend::Particle::m2 () const [inline]
Definition at line 75 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::m2().
{return _p.m2();}
int GAMBIT::Backend::Particle::pdg () const [inline]
Definition at line 72 of file particle.hpp.
References _pdg.
Referenced by Particle().
{return _pdg;}
double GAMBIT::Backend::Particle::phi () const [inline]
Definition at line 78 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::phi().
{return _p.phi();}
double GAMBIT::Backend::Particle::pT () const [inline]
Definition at line 76 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::pT().
{return _p.pT();}
double GAMBIT::Backend::Particle::px () const [inline]
Definition at line 68 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::px().
{return _p.px();}
double GAMBIT::Backend::Particle::py () const [inline]
Definition at line 69 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::py().
{return _p.py();}
double GAMBIT::Backend::Particle::pz () const [inline]
Definition at line 70 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::pz().
{return _p.pz();}
double GAMBIT::Backend::Particle::theta () const [inline]
Definition at line 77 of file particle.hpp.
References _p, and GAMBIT::Backend::Vector4::theta().
{return _p.theta();}
Member Data Documentation
Vector4 GAMBIT::Backend::Particle::_p [private]
Definition at line 82 of file particle.hpp.
Referenced by e(), m(), m2(), Particle(), phi(), pT(), px(), py(), pz(), and theta().
int GAMBIT::Backend::Particle::_pdg [private]
Definition at line 83 of file particle.hpp.
Referenced by Particle(), and pdg().
The documentation for this class was generated from the following file:
Utils/include/particle.hpp