GAMBIT: HEColliderBit/src/example-fastsim.cpp File Reference
example-fastsim.cpp File Reference
#include "FastSim.hpp"
#include <iostream>
Functions
int main ()
Function Documentation
int main ()
Todo:
This new'ing is silly... can we rework FastSim to use references?
Todo:
Why not p->mom().m2() in the second case?
Definition at line 5 of file example-fastsim.cpp.
References ACERDET, GAMBIT::P4::E2(), FastSim::InitSimulation(), GAMBIT::Particle::mom(), FastSim::MuonResponse(), FastSim::NMuons(), GAMBIT::P4::p2(), FastSim::PrintMuons(), and FastSim::SetMuons().
            {
  FastSim sim;
  sim.InitSimulation(ACERDET);
  GAMBIT::Particle* p = new GAMBIT::Particle(10.0, 10.0, 10.0, 17.320826, 13);
  GAMBIT::Particle* p2 = new GAMBIT::Particle(10.0, 10.0, 10.0, 17.320826, 13);
  cout << "p " << p->mom().p2() << ", " << p->mom().E2() - p->mom().p2() << endl;
  vector<GAMBIT::Particle*> list;
  list.push_back(p);
  list.push_back(p2);
  sim.SetMuons(list);
  cout << "Number of muons = " << sim.NMuons() << endl;
  sim.PrintMuons();
  sim.MuonResponse();
  cout << "Number of muons = " << sim.NMuons() << endl;
  sim.PrintMuons();
  // Memory clean-up, thanks to the heap allocation...
  for (size_t i = 0; i < list.size(); ++i) delete list[i];
}