GAMBIT: GAMBIT::ExampleBit_B Namespace Reference
GAMBIT::ExampleBit_B Namespace Reference
Functions
void initialize ()
void xsection (double &result)
void exampleCharge (int &result)
void identity (str &result)
void nevents (int &result)
void nevents_postcuts (int &result)
Function Documentation
void GAMBIT::ExampleBit_B::exampleCharge (int & result)
Definition at line 45 of file ExampleBit_B.cpp.
{ result = 1; }
void GAMBIT::ExampleBit_B::identity (str & result)
Definition at line 46 of file ExampleBit_B.cpp.
{ result = "rabbiton"; }
void GAMBIT::ExampleBit_B::initialize ()
Definition at line 35 of file ExampleBit_B.cpp.
    {
      cout << endl;
      cout << "********************************************" << endl;
      cout << "***       Initializing ExampleBit_B      ***" << endl;
      cout << "********************************************" << endl;
    }
void GAMBIT::ExampleBit_B::nevents (int & result)
Definition at line 47 of file ExampleBit_B.cpp.
Referenced by GAMBIT::ExampleBit_A::nevents_int(), and nevents_postcuts().
{ result = 2; }
void GAMBIT::ExampleBit_B::nevents_postcuts (int & result)
Definition at line 48 of file ExampleBit_B.cpp.
References GET_BE_FUNCNAME, GET_BE_PACKAGE, GET_BE_RESULT, GET_BE_VERSION, GET_DEP, GET_DEP_FUNCNAME, GET_DEP_MODULE, and nevents().
Referenced by main().
    {
      cout << endl << "My dependency on nevents has been filled by " <<
       GET_DEP_FUNCNAME(nevents_postcuts::nevents) << " from " <<
       GET_DEP_MODULE(nevents_postcuts::nevents) << "." << endl;
      cout << "Its value is: ";
      double nevents = GET_DEP(nevents_postcuts::nevents);
      cout << nevents << endl << endl;
      cout << "My backend requirement of awesomeness has been filled by " <<
       GET_BE_FUNCNAME(nevents_postcuts::awesomeness) << " from " <<
       GET_BE_PACKAGE(nevents_postcuts::awesomeness) << ", v" <<
       GET_BE_VERSION(nevents_postcuts::awesomeness) << "." << endl;
      cout << "Its value is: ";
      double doall_local = GET_BE_RESULT(nevents_postcuts::awesomeness, 2);
      cout << doall_local << endl << endl;
      result = (int) (nevents + doall_local);
    }
void GAMBIT::ExampleBit_B::xsection (double & result)
Definition at line 44 of file ExampleBit_B.cpp.
{ result = 5.e10; }