GAMBIT: GAMBIT::TinyDarkBit Namespace Reference
GAMBIT::TinyDarkBit Namespace Reference
Functions
void initDS (int &result)
void CMSSM_definition (double &result)
void SLHA (double &result)
void Wstruct (GAMBIT::types::Wstruct &result)
void Weff (double &result)
void omega_DM (double &result)
Variables
GAMBIT::Backend::DarkSUSY myDarkSUSY
Function Documentation
void GAMBIT::TinyDarkBit::CMSSM_definition (double & result)
Definition at line 78 of file TinyDarkBit.cpp.
Referenced by main(), and SLHA().
    {
      result = 0.5;
    }
void GAMBIT::TinyDarkBit::initDS (int & result)
Definition at line 56 of file TinyDarkBit.cpp.
References myDarkSUSY.
    {
      std::cout << std::endl;
      std::cout << "********************************************" << std::endl;
      std::cout << "***       Initializing DarkSUSY          ***" << std::endl;
      std::cout << "********************************************" << std::endl;
      // Example for how to run backend functions and retrieve results
      TinyDarkBit::myDarkSUSY.initialize();
      TinyDarkBit::myDarkSUSY.model(500, 1000, 3500, 400, 1000, 10);
      std::cout << "The relic density is: " << TinyDarkBit::myDarkSUSY.rdomega() << std::endl;
      std::cout << "**********************************************" << std::endl;
      std::cout << "*** Initialization of DarkSUSY complete    ***" << std::endl;
      std::cout << "**********************************************" << std::endl << std::endl;
    }
void GAMBIT::TinyDarkBit::omega_DM (double & result)
Definition at line 98 of file TinyDarkBit.cpp.
References GET_DEP, GAMBIT::types::Wstruct::valA, GAMBIT::types::Wstruct::valB, Weff(), and Wstruct().
Referenced by main().
    {
      GAMBIT::types::Wstruct Wstruct = GET_DEP(omega_DM::Wstruct);
      double Weff = GET_DEP(omega_DM::Weff);
      result = Wstruct.valA + Wstruct.valB + Weff;
    }
void GAMBIT::TinyDarkBit::SLHA (double & result)
Definition at line 82 of file TinyDarkBit.cpp.
References CMSSM_definition(), and GET_DEP.
Referenced by main(), Weff(), and Wstruct().
    {
      double CMSSM_definition = GET_DEP(SLHA::CMSSM_definition);
      result = CMSSM_definition * 0.5;
    }
void GAMBIT::TinyDarkBit::Weff (double & result)
Definition at line 93 of file TinyDarkBit.cpp.
References GET_DEP, and SLHA().
Referenced by main(), and omega_DM().
    {
      double SLHA = GET_DEP(Weff::SLHA);
      result = SLHA * 2.0;
    }
void GAMBIT::TinyDarkBit::Wstruct (GAMBIT::types::Wstruct & result)
Definition at line 87 of file TinyDarkBit.cpp.
References GET_DEP, SLHA(), GAMBIT::types::Wstruct::valA, and GAMBIT::types::Wstruct::valB.
Referenced by main(), and omega_DM().
    {
      double SLHA = GET_DEP(Wstruct::SLHA);
      result.valA = SLHA * 0.5;
      result.valB = SLHA * 1.5;
    }
Variable Documentation
GAMBIT::Backend::DarkSUSY GAMBIT::TinyDarkBit::myDarkSUSY
Definition at line 36 of file TinyDarkBit_rollcall.hpp.
Referenced by initDS().