GAMBIT: GAMBIT Namespace Reference
GAMBIT Namespace Reference
Namespaces
namespace Backend
namespace ExampleBit_A
namespace ExampleBit_B
namespace Graphs
namespace HEColliderBit
namespace PID
namespace TinyDarkBit
namespace types
Classes
class dict
class functor
Function wrapper (functor) base class.
class module_functor
Functor derived class for module functions with result type TYPE.
class backend_functor_common
Backend functor class for functions with result type TYPE and argumentlist ARGS.
class backend_functor
Actual backend functor type for all but TYPE=void.
class backend_functor< void, ARGS...>
Template specialisation of backend functor type for TYPE=void.
struct ini_code
class Analysis
class Analysis_ATLAS0LEP
class Event
Simple event class, separating into various classes of particle.
class Jet
Simple jet class, encapsulating a momentum 4-vector and with some extra b-tag info.
class Particle
Simple particle class, encapsulating a momentum 4-vector and adding some extra ID info.
class P4
An alternative 4-momentum class.
Typedefs
typedef std::basic_ostream
< char, std::char_traits< char > > stream
typedef std::string str
typedef std::pair< str, str > sspair
Functions
std::vector< std::string > delimiterSplit (std::string s, std::string delim)
template<typename OUTTYPE , typename... ARGS>
backend_functor< OUTTYPE, ARGS...> makeBackendFunctor (OUTTYPE(*f_in)(ARGS...), str func_name, str func_capab, str ret_type, str origin_name, str origin_ver)
Function for creating backend functor objects.
std::string spacing (int len, int maxlen)
stream & operator<< (stream &os, const std::map< std::string, std::string > &map)
stream & operator<< (stream &os, const std::map< std::string, int > &map)
home pat gambit hepforge
modules HEColliderBit src
Analysis cpp home pat gambit
hepforge modules HEColliderBit
src Analysis cpp Analysis * mkAnalysis (const std::string &name)
Create a new analysis based on a name string.
std::vector< fastjet::PseudoJet > get_jets (const std::vector< fastjet::PseudoJet > &particles, double R, double ptmin, fastjet::JetAlgorithm alg=fastjet::antikt_algorithm)
Construct pT-sorted jets using the alg measure with jet R parameter, and min pT ptmin (in MeV)
double deltaPhi (const fastjet::PseudoJet &a, const fastjet::PseudoJet &b)
double deltaR (const fastjet::PseudoJet &a, const fastjet::PseudoJet &b)
bool _cmpPtDesc (const Jet *a, const Jet *b)
Function/functor for container<const Jet*> sorting (cf. std::less)
void fillGambitEvent (const Pythia8::Event &pevt, GAMBIT::Event &gevt)
Fill a GAMBIT::Event from a Pythia8 event.
Converters to/from the Gambit 4-vector
fastjet::PseudoJet p4_to_pseudojet (const P4 &p)
P4 pseudojet_to_p4 (const fastjet::PseudoJet &p)
Numerical helpers
double sqr (double val)
Convenience function for squaring (better than repeating long expressions)
double add_quad (double a, double b)
Convenience function for adding two numbers in quadrature.
double add_quad (double a, double b, double c)
Convenience function for adding three numbers in quadrature.
Range helpers
bool inRange (double val, double low, double high)
Boolean function to determine if value is within the given floating point range.
bool inRange (int val, int low, int high)
Boolean function to determine if value is within the given integer range.
std::vector< double > linspace (size_t nbins, double start, double end)
Make a list of nbins + 1 values linearly spaced between start and end inclusive.
std::vector< double > logspace (size_t nbins, double start, double end, double offset=0)
Make a list of nbins + 1 values exponentially spaced between start and end inclusive.
Physics maths utils
double deltaPhi (double a, double b)
PID stuff
Todo:
Move to PIDUtils
template<size_t D>
unsigned int digit (unsigned int val)
template<>
unsigned int digit< 1 > (unsigned int val)
bool hasQuark (unsigned int qid, int pid)
bool hasCharm (int pid)
bool hasBottom (int pid)
Converters to/from Pythia8's native 4-vector
fastjet::PseudoJet vec4_to_pseudojet (const Pythia8::Vec4 &p)
P4 vec4_to_p4 (const Pythia8::Vec4 &p)
Pythia8::Vec4 pseudojet_to_vec4 (const fastjet::PseudoJet &p)
Convenience functions on Py8 objects
double deltaPhi (const Pythia8::Vec4 &a, const Pythia8::Vec4 &b)
double deltaR (const Pythia8::Vec4 &a, const Pythia8::Vec4 &b)
Detailed Pythia8 event record walking/mangling functions
bool fromBottom (int n, const Pythia8::Event &evt)
bool fromTau (int n, const Pythia8::Event &evt)
bool isReplica (int n, const Pythia8::Event &evt)
void finalDescendants (int n, const Pythia8::Event &evt, vector< int > &rtn)
bool isFinalB (int n, const Pythia8::Event &evt)
bool isFinalTau (int n, const Pythia8::Event &evt)
String representations
std::string to_str (const P4 &p4)
Make a string representation of the vector.
std::ostream & operator<< (std::ostream &ostr, const P4 &p4)
Write a string representation of the vector to the provided stream.
double dot (const P4 &a, const P4 &b)
Convenience "external" functions.
double angle (const P4 &a, const P4 &b)
Angle between two vectors.
double deltaPhi (const P4 &a, const P4 &b)
Difference in phi between two vectors.
double deltaEta (const P4 &a, const P4 &b)
Difference in pseudorapidity between two vectors.
double deltaRap (const P4 &a, const P4 &b)
Difference in rapidity between two vectors.
double deltaR2_eta (const P4 &a, const P4 &b)
Difference in pseudorapidity-based R^2 between two vectors.
double deltaR_eta (const P4 &a, const P4 &b)
Difference in pseudorapidity-based R between two vectors.
double deltaR2_rap (const P4 &a, const P4 &b)
Difference in rapidity-based R^2 between two vectors.
double deltaR_rap (const P4 &a, const P4 &b)
Difference in rapidity-based R between two vectors.
Operators taking two vectors
P4 operator+ (const P4 &a, const P4 &b)
P4 operator- (const P4 &a, const P4 &b)
P4 operator* (const P4 &a, double f)
P4 operator* (double f, const P4 &a)
P4 operator/ (const P4 &a, double f)
Variables
bool safe_mode = true
Typedef Documentation
typedef std::pair<str, str> GAMBIT::sspair
Definition at line 29 of file util_classes.hpp.
typedef std::string GAMBIT::str
Definition at line 28 of file util_classes.hpp.
typedef std::basic_ostream<char, std::char_traits<char> > GAMBIT::stream
Definition at line 29 of file map_extensions.hpp.
Function Documentation
bool GAMBIT::_cmpPtDesc (const Jet * a, const Jet * b) [inline]
Function/functor for container<const Jet*> sorting (cf. std::less)
Definition at line 69 of file Jet.hpp.
References GAMBIT::Jet::pT2().
Referenced by GAMBIT::Event::jets().
{
    return a->pT2() >= b->pT2();
  }
double GAMBIT::add_quad (double a, double b) [inline]
Convenience function for adding two numbers in quadrature.
Todo:
Template and SFINAE on numerical types?
Definition at line 24 of file MathUtils.hpp.
{
    return sqrt(a*a + b*b);
  }
double GAMBIT::add_quad (double a, double b, double c) [inline]
Convenience function for adding three numbers in quadrature.
Todo:
Template and SFINAE on numerical types?
Definition at line 31 of file MathUtils.hpp.
{
    return sqrt(a*a + b*b + c*c);
  }
double GAMBIT::angle (const P4 & a, const P4 & b) [inline]
Angle between two vectors.
Definition at line 322 of file Vectors.hpp.
References GAMBIT::P4::angleTo().
{
    return a.angleTo(b);
  }
std::vector< std::string > GAMBIT::delimiterSplit (std::string s, std::string delim)
Definition at line 25 of file util_functions.cpp.
Referenced by GAMBIT::module_functor< TYPE >::setBackendConditionalDependency(), and GAMBIT::module_functor< TYPE >::setPermittedBackend().
  {
    std::vector<std::string> vec;
    // Get rid of any whitespace around the delimiters
    #if GAMBIT_CONFIG_FLAG_use_std_regex     // Using std::regex :D
      std::regex rgx1("\\s+"+delim), rgx2(delim+"\\s+");
      s = std::regex_replace(s, rgx1, delim);
      s = std::regex_replace(s, rgx2, delim);
    #elif GAMBIT_CONFIG_FLAG_use_boost_regex // Using boost::regex :|
      boost::regex rgx1("\\s+"+delim), rgx2(delim+"\\s+");
      s = boost::regex_replace(s, rgx1, delim);
      s = boost::regex_replace(s, rgx2, delim);
    #else                                    // Using lame-o methods >:(
      const char* whitespaces[] = {" ", "\t", "\n", "\f", "\r"};
      std::string previous = s+".";
      while (s != previous)
      {
        previous = s;
        for (int i = 0; i != 5; i++)
        {
          boost::replace_all(s, whitespaces[i]+delim, delim);
          boost::replace_all(s, delim+whitespaces[i], delim);
        }
      }
    #endif
    // Split up the list of versions by the delimiters
    boost::split(vec, s, boost::is_any_of(delim), boost::token_compress_on);
    return vec;
  }
double GAMBIT::deltaEta (const P4 & a, const P4 & b) [inline]
Difference in pseudorapidity between two vectors.
Definition at line 334 of file Vectors.hpp.
References GAMBIT::P4::deltaEta().
{
    return a.deltaEta(b);
  }
double GAMBIT::deltaPhi (const fastjet::PseudoJet & a, const fastjet::PseudoJet & b) [inline]
Definition at line 36 of file FastJetUtils.hpp.
Referenced by GAMBIT::Analysis_ATLAS0LEP::analyze(), FastSim::Clustering(), deltaPhi(), deltaR(), and main().
{
    return deltaPhi(a.phi(), b.phi());
  }
double GAMBIT::deltaPhi (double a, double b) [inline]
Definition at line 104 of file MathUtils.hpp.
{
    double rtn = a - b;
    rtn = fmod(rtn, 2*M_PI);
    if (rtn == 0) return 0;
    assert(rtn >= -2*M_PI && rtn <= 2*M_PI);
    rtn = (rtn >   M_PI ? rtn-2*M_PI :
           rtn <= -M_PI ? rtn+2*M_PI : rtn);
    assert(rtn > -M_PI && rtn <= M_PI);
    if (rtn < 0) rtn += M_PI;
    assert(rtn > 0 && rtn <= M_PI);
    return rtn;
  }
double GAMBIT::deltaPhi (const P4 & a, const P4 & b) [inline]
Difference in phi between two vectors.
Definition at line 328 of file Vectors.hpp.
References GAMBIT::P4::deltaPhi().
{
    return a.deltaPhi(b);
  }
double GAMBIT::deltaPhi (const Pythia8::Vec4 & a, const Pythia8::Vec4 & b) [inline]
Definition at line 42 of file Py8Utils.hpp.
References deltaPhi().
{
    return deltaPhi(a.phi(), b.phi());
  }
double GAMBIT::deltaR (const fastjet::PseudoJet & a, const fastjet::PseudoJet & b) [inline]
Definition at line 41 of file FastJetUtils.hpp.
References deltaPhi().
Referenced by main().
{
    const double deta = fabs(a.eta() - b.eta());
    const double dphi = deltaPhi(a, b);
    return deta*deta + dphi*dphi;
  }
double GAMBIT::deltaR (const Pythia8::Vec4 & a, const Pythia8::Vec4 & b) [inline]
Definition at line 46 of file Py8Utils.hpp.
References deltaPhi().
{
    const double deta = fabs(a.eta() - b.eta());
    const double dphi = deltaPhi(a, b);
    return deta*deta + dphi*dphi;
  }
double GAMBIT::deltaR2_eta (const P4 & a, const P4 & b) [inline]
Difference in pseudorapidity-based R^2 between two vectors.
Definition at line 346 of file Vectors.hpp.
References GAMBIT::P4::deltaR2_eta().
{
    return a.deltaR2_eta(b);
  }
double GAMBIT::deltaR2_rap (const P4 & a, const P4 & b) [inline]
Difference in rapidity-based R^2 between two vectors.
Definition at line 356 of file Vectors.hpp.
References GAMBIT::P4::deltaR2_rap().
{
    return a.deltaR2_rap(b);
  }
double GAMBIT::deltaR_eta (const P4 & a, const P4 & b) [inline]
Difference in pseudorapidity-based R between two vectors.
Definition at line 350 of file Vectors.hpp.
References GAMBIT::P4::deltaR_eta().
{
    return a.deltaR_eta(b);
  }
double GAMBIT::deltaR_rap (const P4 & a, const P4 & b) [inline]
Difference in rapidity-based R between two vectors.
Definition at line 360 of file Vectors.hpp.
References GAMBIT::P4::deltaR_rap().
{
    return a.deltaR_rap(b);
  }
double GAMBIT::deltaRap (const P4 & a, const P4 & b) [inline]
Difference in rapidity between two vectors.
Definition at line 340 of file Vectors.hpp.
References GAMBIT::P4::deltaRap().
{
    return a.deltaRap(b);
  }
template<size_t D> unsigned int GAMBIT::digit (unsigned int val)
Definition at line 19 of file MCUtils.hpp.
{ return digit<D-1>(val/10); }
template<> unsigned int GAMBIT::digit< 1 > (unsigned int val)
Definition at line 20 of file MCUtils.hpp.
{ return val % 10; }
double GAMBIT::dot (const P4 & a, const P4 & b) [inline]
Convenience "external" functions.
Lorentz inner product between two vectors
Definition at line 316 of file Vectors.hpp.
References GAMBIT::P4::dot().
{
    return a.dot(b);
  }
void GAMBIT::fillGambitEvent (const Pythia8::Event & pevt, GAMBIT::Event & gevt) [inline]
Fill a GAMBIT::Event from a Pythia8 event.
Todo:
Promptness: need an isPrompt function that walks back up the tree
Todo:
taus... and include hadronically decaying ones only?
Todo:
Don't exclude tau decay products, apparently: ATLAS treats them as jets
Todo:
b-tagging
Definition at line 152 of file Py8Utils.hpp.
References GAMBIT::Event::addJet(), GAMBIT::Event::addParticle(), pseudojet_to_p4(), GAMBIT::Event::setMissingMom(), vec4_to_p4(), and vec4_to_pseudojet().
Referenced by main().
{
    Pythia8::Vec4 ptot;
    std::vector<fastjet::PseudoJet> jetparticles;
    for (int i = 0; i < pevt.size(); ++i) {
      if (!pevt[i].isFinal()) continue;
      if (pevt[i].eta() > 5.0) continue;
      const Pythia8::Particle& p = pevt[i];
      bool prompt = false;
      if (prompt) {
        Particle* gp = new Particle(vec4_to_p4(p.p()), p.id());
        gevt.addParticle(gp); // will be automatically categorised, including invisibles
      } else {
        // Choose jet constituents (should include neutrinos?)
        jetparticles.push_back(vec4_to_pseudojet(p.p()));
      }
      // Add to total momentum
      ptot += p.p();
    }
    // Jets
    const fastjet::JetDefinition jet_def(fastjet::antikt_algorithm, 0.4);
    fastjet::ClusterSequence cseq(jetparticles, jet_def);
    vector<fastjet::PseudoJet> pjets = sorted_by_pt(cseq.inclusive_jets(30));
    foreach (const fastjet::PseudoJet& pj, pjets) {
      bool isB = false;
      gevt.addJet(new Jet(pseudojet_to_p4(pj), isB));
    }
    // MET
    gevt.setMissingMom(-vec4_to_p4(ptot));
  }
void GAMBIT::finalDescendants (int n, const Pythia8::Event & evt, vector< int > & rtn)
Definition at line 87 of file Py8Utils.hpp.
References GAMBIT::PID::n.
{
    const Pythia8::Particle& p = evt[n];
    //assert(!p.isParton());
    if (p.isParton()) cerr << "PARTON IN DESCENDANT CHAIN FROM HADRON! NUM, ID = " << n << ", " << p.id() << endl;
    foreach (int m, evt.daughterList(n)) {
      if (evt[m].isFinal()) {
        rtn.push_back(m);
      } else {
        finalDescendants(m, evt, rtn);
      }
    }
  }
bool GAMBIT::fromBottom (int n, const Pythia8::Event & evt)
Todo:
What about partonic decays?
Definition at line 58 of file Py8Utils.hpp.
References GAMBIT::PID::hasBottom(), and GAMBIT::PID::n.
{
    const Pythia8::Particle& p = evt[n];
    if (abs(p.id()) == 5 || PID::hasBottom(p.id())) return true;
    if (p.isParton()) return false; // stop the walking at hadron level
    foreach (int m, evt.motherList(n)) {
      if (fromBottom(m, evt)) return true;
    }
    return false;
  }
bool GAMBIT::fromTau (int n, const Pythia8::Event & evt)
Definition at line 70 of file Py8Utils.hpp.
References GAMBIT::PID::n.
{
    const Pythia8::Particle& p = evt[n];
    if (abs(p.id()) == 15) return true;
    if (p.isParton()) return false; // stop the walking at hadron level
    foreach (int m, evt.motherList(n)) {
      if (fromTau(m, evt)) return true;
    }
    return false;
  }
std::vector<fastjet::PseudoJet> GAMBIT::get_jets (const std::vector< fastjet::PseudoJet > & particles, double R, double ptmin, fastjet::JetAlgorithm alg = fastjet::antikt_algorithm) [inline]
Construct pT-sorted jets using the alg measure with jet R parameter, and min pT ptmin (in MeV)
Definition at line 27 of file FastJetUtils.hpp.
{
    const fastjet::JetDefinition jet_def(alg, R);
    fastjet::ClusterSequence cseq(particles, jet_def);
    return fastjet::sorted_by_pt(cseq.inclusive_jets(ptmin));
  }
bool GAMBIT::hasBottom (int pid) [inline]
Definition at line 30 of file MCUtils.hpp.
References hasQuark().
Referenced by isFinalB().
{ return hasQuark(5, pid); }
bool GAMBIT::hasCharm (int pid) [inline]
Definition at line 29 of file MCUtils.hpp.
References hasQuark().
{ return hasQuark(4, pid); }
bool GAMBIT::hasQuark (unsigned int qid, int pid) [inline]
Definition at line 22 of file MCUtils.hpp.
Referenced by hasBottom(), and hasCharm().
{
    const unsigned int apid = std::abs(pid);
    if (apid == qid) return true;
    if (apid < 100 || std::abs(pid) > 10000) return false;
    return digit<2>(apid) == qid || digit<3>(apid) == qid || digit<4>(apid) == qid;
  }
bool GAMBIT::inRange (int val, int low, int high) [inline]
Boolean function to determine if value is within the given integer range.
NB. The interval is closed (inclusive) at the low end, and open (exclusive) at the high end.
Todo:
Would be nice to include val == high if all args are integers, but dangerous due to implicit conversion...
SFINAE and template for integer types
Definition at line 57 of file MathUtils.hpp.
{
    return val >= low && val < high;
  }
bool GAMBIT::inRange (double val, double low, double high) [inline]
Boolean function to determine if value is within the given floating point range.
NB. The interval is closed (inclusive) at the low end, and open (exclusive) at the high end.
Todo:
Would be nice to include val == high if all args are integers, but dangerous due to implicit conversion...
SFINAE and template for FP types
Definition at line 47 of file MathUtils.hpp.
Referenced by GAMBIT::PID::isGenSpecific(), GAMBIT::PID::isQuark(), and linspace().
{
    return val >= low && val < high;
  }
bool GAMBIT::isFinalB (int n, const Pythia8::Event & evt)
Definition at line 101 of file Py8Utils.hpp.
References GAMBIT::PID::hasBottom().
{
    // *This* particle must be a b or b-hadron
    if (!PID::hasBottom(evt[n].id())) return false;
    // Daughters must *not* include a b or b-hadron
    foreach (int m, evt.daughterList(n)) {
      if (PID::hasBottom(evt[m].id())) return false;
    }
    return true;
  }
bool GAMBIT::isFinalTau (int n, const Pythia8::Event & evt)
Definition at line 112 of file Py8Utils.hpp.
{
    // *This* particle must be a b or b-hadron
    if (abs(evt[n].id()) != 15) return false;
    // Daughters must *not* include a tau
    foreach (int m, evt.daughterList(n)) {
      if (abs(evt[m].id()) == 15) return false;
    }
    return true;
  }
bool GAMBIT::isReplica (int n, const Pythia8::Event & evt)
Definition at line 81 of file Py8Utils.hpp.
References GAMBIT::PID::n.
{
    const Pythia8::Particle& p = evt[n];
    return p.daughter1() != 0 && p.daughter1() == p.daughter2();
  }
std::vector<double> GAMBIT::linspace (size_t nbins, double start, double end) [inline]
Make a list of nbins + 1 values linearly spaced between start and end inclusive.
Definition at line 63 of file MathUtils.hpp.
References inRange().
Referenced by logspace().
{
    assert(end >= start);
    assert(nbins > 0);
    std::vector<double> rtn;
    const double interval = (end-start)/static_cast<double>(nbins);
    // Add all edges except the last
    double edge = start;
    while (inRange(edge, start, end)) {
      rtn.push_back(edge);
      edge += interval;
    }
    // Add the last edge
    rtn.push_back(edge);
    assert(rtn.size() == nbins+1);
    return rtn;
  }
std::vector<double> GAMBIT::logspace (size_t nbins, double start, double end, double offset = 0) [inline]
Make a list of nbins + 1 values exponentially spaced between start and end inclusive.
Definition at line 82 of file MathUtils.hpp.
References linspace().
{
    assert(end >= start);
    assert(start+offset > 0);
    assert(nbins > 0);
    const double logstart = std::log(start+offset);
    const double logend = std::log(end+offset);
    const std::vector<double> logvals = linspace(nbins, logstart, logend);
    assert(logvals.size() == nbins+1);
    std::vector<double> rtn;
    for (size_t i = 0; i < logvals.size(); ++i) {
      rtn.push_back(std::exp(logvals[i]) - offset);
    }
    assert(rtn.size() == nbins+1);
    return rtn;
  }
template<typename OUTTYPE , typename... ARGS> backend_functor<OUTTYPE,ARGS...> GAMBIT::makeBackendFunctor (OUTTYPE(*)(ARGS...) f_in, str func_name, str func_capab, str ret_type, str origin_name, str origin_ver)
Function for creating backend functor objects.
This is needed due to the way the BE_FUNCTION / BE_VARIABLE macros in backend_general.hpp works at the moment...
Definition at line 508 of file functors.hpp.
  {
    return backend_functor<OUTTYPE,ARGS...>(f_in, func_name,func_capab,ret_type,origin_name,origin_ver);
  }
Analysis * GAMBIT::mkAnalysis (const std::string & name)
Create a new analysis based on a name string.
The caller is responsible for deleting the returned analysis object.
Definition at line 12 of file Analysis.cpp.
Referenced by main().
           {
      throw std::runtime_error(name + " isn't a known collider analysis, you idiot");
    }
  }
P4 GAMBIT::operator* (const P4 & a, double f) [inline]
Definition at line 371 of file Vectors.hpp.
{ P4 rtn = a; return rtn *= f; }
P4 GAMBIT::operator* (double f, const P4 & a) [inline]
Definition at line 372 of file Vectors.hpp.
{ P4 rtn = a; return rtn *= f; }
P4 GAMBIT::operator+ (const P4 & a, const P4 & b) [inline]
Definition at line 369 of file Vectors.hpp.
{ P4 rtn = a; return rtn += b; }
P4 GAMBIT::operator- (const P4 & a, const P4 & b) [inline]
Definition at line 370 of file Vectors.hpp.
{ P4 rtn = a; return rtn -= b; }
P4 GAMBIT::operator/ (const P4 & a, double f) [inline]
Definition at line 373 of file Vectors.hpp.
{ P4 rtn = a; return rtn /= f; }
stream& GAMBIT::operator<< (stream & os, const std::map< std::string, int > & map)
Definition at line 63 of file map_extensions.hpp.
References spacing().
{
    unsigned int maxlen = 0;
    std::map<std::string,int>::const_iterator it;
    for (it = map.begin(); it != map.end(); it++) {
      if ((*it).first.length() > maxlen) maxlen = (*it).first.length();
    }
    for (it = map.begin(); it != map.end(); it++) {
      if (it != map.begin()) {os << std::endl;}
      os << " " << (*it).first << spacing((*it).first.length(), maxlen) << "(" << (*it).second << ")";
    }
    return os;
  }
std::ostream& GAMBIT::operator<< (std::ostream & ostr, const P4 & p4) [inline]
Write a string representation of the vector to the provided stream.
Definition at line 304 of file Vectors.hpp.
References to_str().
{
    ostr << to_str(p4);
    return ostr;
  }
stream& GAMBIT::operator<< (stream & os, const std::map< std::string, std::string > & map)
Definition at line 43 of file map_extensions.hpp.
References spacing().
{
    unsigned int maxlen = 0;
    std::map<std::string,std::string>::const_iterator it;
    for (it = map.begin(); it != map.end(); it++) {
      if ((*it).first.length() > maxlen) maxlen = (*it).first.length();
    }
    for (it = map.begin(); it != map.end(); it++) {
      if (it != map.begin()) {os << std::endl;}
      os << " " << (*it).first << spacing((*it).first.length(), maxlen) << "(" << (*it).second << ")";
    }
    return os;
  }
fastjet::PseudoJet GAMBIT::p4_to_pseudojet (const P4 & p) [inline]
Definition at line 15 of file FastJetUtils.hpp.
References GAMBIT::P4::E(), GAMBIT::P4::px(), GAMBIT::P4::py(), and GAMBIT::P4::pz().
{
    return fastjet::PseudoJet(p.px(), p.py(), p.pz(), p.E());
  }
P4 GAMBIT::pseudojet_to_p4 (const fastjet::PseudoJet & p) [inline]
Definition at line 19 of file FastJetUtils.hpp.
Referenced by fillGambitEvent().
{
    return P4(p.px(), p.py(), p.pz(), p.e());
  }
Pythia8::Vec4 GAMBIT::pseudojet_to_vec4 (const fastjet::PseudoJet & p) [inline]
Definition at line 30 of file Py8Utils.hpp.
Referenced by main().
{
    Pythia8::Vec4 rtn;
    rtn.p(p.px(), p.py(), p.pz(), p.e());
    return rtn;
  }
std::string GAMBIT::spacing (int len, int maxlen)
Definition at line 33 of file map_extensions.hpp.
Referenced by operator<<().
{
    int offset = 0;
    if (len < maxlen) {offset=maxlen-len;}
    return std::string(offset+5,' ');
  }
double GAMBIT::sqr (double val) [inline]
Convenience function for squaring (better than repeating long expressions)
Todo:
Template and SFINAE on numerical types?
Definition at line 17 of file MathUtils.hpp.
Referenced by GAMBIT::P4::deltaR2_eta(), GAMBIT::P4::deltaR2_rap(), GAMBIT::P4::E2(), GAMBIT::P4::m2(), GAMBIT::P4::mkRapPhiME(), GAMBIT::P4::mkRhoPhiME(), GAMBIT::P4::mkThetaPhiME(), GAMBIT::P4::operator+=(), GAMBIT::P4::operator-=(), GAMBIT::P4::p2(), GAMBIT::P4::px2(), GAMBIT::P4::py2(), GAMBIT::P4::pz2(), GAMBIT::P4::rho2(), and GAMBIT::P4::setPE().
{
    return val * val;
  }
std::string GAMBIT::to_str (const P4 & p4) [inline]
Make a string representation of the vector.
Definition at line 297 of file Vectors.hpp.
References GAMBIT::P4::E(), GAMBIT::P4::px(), GAMBIT::P4::py(), and GAMBIT::P4::pz().
Referenced by operator<<().
{
    std::stringstream ss;
    ss << "(" << p4.px() << ", " << p4.py() << ", " << p4.pz() << "; " << p4.E() << ")";
    return ss.str();
  }
P4 GAMBIT::vec4_to_p4 (const Pythia8::Vec4 & p) [inline]
Definition at line 26 of file Py8Utils.hpp.
Referenced by fillGambitEvent().
{
    return P4(p.px(), p.py(), p.pz(), p.e());
  }
fastjet::PseudoJet GAMBIT::vec4_to_pseudojet (const Pythia8::Vec4 & p) [inline]
Definition at line 22 of file Py8Utils.hpp.
Referenced by fillGambitEvent(), and main().
{
    return fastjet::PseudoJet(p.px(), p.py(), p.pz(), p.e());
  }
Variable Documentation
bool GAMBIT::safe_mode = true
Definition at line 28 of file globals.hpp.