GAMBIT: gambit::logsetup Namespace Reference
gambit::logsetup Namespace Reference
Logging facility.
Enumerations
enum severity_t {
sFATAL = 100, sERROR = 50, sWARNING = 10, sLOG = 5,
sINFO = 2, sDEBUG = 0, sDEBUG1 = -1, sDEBUG2 = -2,
sDEBUG3 = -3, sDEBUG4 = -4
}
log severity
Functions
std::string stacktrace () throw ()
Generate string containing stacktrace.
std::string demangle_traceline (const char *name) throw ()
function to demangle stacktrace strings.
void setLogLevel (severity_t s)
set log level for writing to files
void setLogLevel (int s)
void setEchoLevel (severity_t s)
set log level for writing to screen. File logging level will be raised to the same if lower.
void setEchoLevel (int s)
void setfile_range (std::string name, int lowedge=INT_MIN, int highedge=INT_MAX)
change logfile name for all outputs from severity lowedge to and including highedge
void setfile (std::string name)
change logfile name for all outputs
void setfile_upto_LOG (std::string name)
change logfile name for all outputs of severity LOG orb less important
void setfile_upto_DEBUG (std::string name, unsigned int deblevel=0)
change logfile name for all outputs of severity DEBUG or less important
void setfile_upto_INFO (std::string name)
change logfile name for all outputs of severity INFO or less important
void setfile_upto_WARNING (std::string name)
change logfile name for all outputs of severity WARNING or less important
void setfile_upto_ERROR (std::string name)
change logfile name for all outputs of severity ERROR or less important
void setfile_downto_LOG (std::string name)
change logfile name for all outputs of severity LOG or worse
void setfile_downto_DEBUG (std::string name)
change logfile name for all outputs of severity DEBUG or worse
void setfile_downto_INFO (std::string name)
change logfile name for all outputs of severity INFO or worse
void setfile_downto_WARNING (std::string name)
change logfile name for all outputs of severity WARNING or worse
void setfile_downto_ERROR (std::string name)
change logfile name for all outputs of severity ERROR or worse
void __priv_debug (std::string filename, int linenno, std::string fnme, std::string message, unsigned int dblevel=0)
helper for debug macro
void __priv_info (std::string filename, int linenno, std::string fnme, std::string message)
helper for debug macro
void __priv_log (std::string filename, int linenno, std::string fnme, std::string message)
helper for debug macro
void __priv_warning (std::string filename, int linenno, std::string fnme, std::string message)
helper for debug macro
void __priv_error (std::string filename, int linenno, std::string fnme, std::string message)
helper for debug macro
void __priv_fatal (std::string filename, int linenno, std::string fnme, std::string message)
helper for debug macro
std::string _default_errfile ()
default log filename for errors
std::string _default_logfile ()
default log filename for non-errors
Detailed Description
Logging facility.
The logsetup defines only static methods and no object can be made.
The main user interface are the _macros_ listed in logcore.h
The list above is in order of severity. A fatal message terminates the execution by calling exit() after the message is handled.
The logcore supports logging each type of message to its own or common files.
To log all messages of severity WARNING or higher to the file errors.txt, do:
 gambit::logsetup::setfile_downto_WARNING("errors.txt")
The logcore supports independent logging to stdout/stderr and files.
For example: To set the level threshold to LOG for printing to stdout/stderr:
 gambit::logsetup::setEchoLevel(gambit::logsetup::sLOG);
For example: To set the level threshold to DEBUG for writing to files:
 gambit::logsetup::setLogLevel(gambit::logsetup::sDEBUG);
Note: the use of the setfile_... methods do not modify the logging level. Files are automatically open and closed as required. Note: setting EchoLevel also sets Log level so that any message Echoed is also logged to file. If needed, this can be sidestepped by setting LogLevel after EchoLevel.
Date:
2011-08-17 -- 2011-08-19
Author:
Johan Lundberg
A note on the implementation: Internally the logcore setup is using a singleton of a class declared in the .cxx file. Flushing, closing of the logfile are done in the destructor, which is registered using 'atexit()'.
Enumeration Type Documentation
enum gambit::logsetup::severity_t
log severity
Enumerator:
sFATAL
sERROR
sWARNING
sLOG
sINFO
sDEBUG
sDEBUG1
sDEBUG2
sDEBUG3
sDEBUG4
Definition at line 160 of file logcore.hpp.
{ sFATAL=100,sERROR=50,sWARNING=10,sLOG=5,sINFO=2,sDEBUG=0,sDEBUG1=-1,sDEBUG2=-2,sDEBUG3=-3,sDEBUG4=-4};
Function Documentation
void gambit::logsetup::__priv_debug (std::string filename, int linenno, std::string prettyf, std::string message, unsigned int level)
helper for debug macro
Definition at line 331 of file logcore.cpp.
References sDEBUG.
{
      if(level==0) level=sDEBUG;
      logcore_imp::instance()->__priv_gambit_message(-abs(level) ,filename,linenno,prettyf,message);
    }
void gambit::logsetup::__priv_error (std::string filename, int linenno, std::string prettyf, std::string message)
helper for debug macro
Definition at line 344 of file logcore.cpp.
References sERROR.
{
      logcore_imp::instance()->__priv_gambit_message(sERROR   ,filename,linenno,prettyf,message);
    }
void gambit::logsetup::__priv_fatal (std::string filename, int linenno, std::string prettyf, std::string message)
helper for debug macro
Definition at line 347 of file logcore.cpp.
References sFATAL.
{
      logcore_imp::instance()->__priv_gambit_message(sFATAL ,filename,linenno,prettyf,message);
      logcore_imp::instance()->__priv_gambit_message(sFATAL ,"",0,"logcore","calling 'exit' now!");
      exit(1);
    }
void gambit::logsetup::__priv_info (std::string filename, int linenno, std::string prettyf, std::string message)
helper for debug macro
Definition at line 335 of file logcore.cpp.
References sINFO.
{
      logcore_imp::instance()->__priv_gambit_message(sINFO  ,filename,linenno,prettyf,message);
    }
void gambit::logsetup::__priv_log (std::string filename, int linenno, std::string prettyf, std::string message)
helper for debug macro
Definition at line 338 of file logcore.cpp.
References sLOG.
{
      logcore_imp::instance()->__priv_gambit_message(sLOG   ,filename,linenno,prettyf,message);
    }
void gambit::logsetup::__priv_warning (std::string filename, int linenno, std::string prettyf, std::string message)
helper for debug macro
Definition at line 341 of file logcore.cpp.
References sWARNING.
{
      logcore_imp::instance()->__priv_gambit_message(sWARNING  ,filename,linenno,prettyf,message);
    }
std::string gambit::logsetup::_default_errfile () [inline]
default log filename for errors
Definition at line 201 of file logcore.hpp.
{ return "_gambit.logs.err" ;};
std::string gambit::logsetup::_default_logfile () [inline]
default log filename for non-errors
Definition at line 203 of file logcore.hpp.
{ return "_gambit.logs.log" ;};
std::string gambit::logsetup::demangle_traceline (const char * name) throw ()
function to demangle stacktrace strings.
convert symbols in stacktrace line
For example, it turns this string: ./exeption.bin(_ZN5gambit8logsetup10stacktraceEv+0x4c) [0x805c61a]
into this string: ./exeption.bin(gambit::stacktrace()+0x4c) [0x805c61a]
Date:
2011 Aug 23
Author:
Johan Lundberg
Definition at line 235 of file logcore.cpp.
Referenced by stacktrace().
    {
      const int maxfuncname=400; // some c++ names are long
      int maxind=std::min(maxfuncname,int (strlen(name)));
      int begin=0;
      int end=0;
      int begin2=0;
      int end2=0;
      while(name[begin]!='(' &&begin<maxind){
        begin++;
      }
      begin++;
      end=begin+1;
      while(name[end]!='+'&&end<maxind){
        end++;
      }
      begin2=end;
      end2=begin2;
      while(name[end2]!=')'&&end2<maxind){
        end2++;
      }
      char tmpstr0[maxfuncname+1];
      char tmpstr[maxfuncname+1];
      char tmpstr2[maxfuncname+1];
      // raw function mame
      for(int i=0;i<(end-begin)&&i<maxind-1;i++){
        tmpstr[i+1]=0;
        tmpstr[i]=name[i+begin];
      }
      // part before first (
      for(int i=0;i<begin&&i<maxind-1;i++){
        tmpstr0[i+1]=0;
        tmpstr0[i]=name[i];
      }
      // part after function name
      for(int i=0;i+end+1<maxind&&i<maxind-1;i++){
        tmpstr2[i+1]=0;
        tmpstr2[i]=name[i+end+1];
      }
      std::size_t len;
      int         stat;
      char*realname=0;
      std::string out;
      try{
        if ((realname = abi::__cxa_demangle(tmpstr,NULL,&len,&stat))){
          out=std::string(tmpstr0)+std::string(realname)+"+"+std::string(tmpstr2);
        }
      }catch(...){}
      if(realname){
        std::free(realname);
        realname=0;
        return out;
      }else{
        return name;
      }
    }
void gambit::logsetup::setEchoLevel (severity_t s)
set log level for writing to screen. File logging level will be raised to the same if lower.
Definition at line 299 of file logcore.cpp.
Referenced by main().
{
      logcore_imp::instance()->_setEchoLevel(s);
    }
void gambit::logsetup::setEchoLevel (int s)
Definition at line 302 of file logcore.cpp.
{
      logcore_imp::instance()->_setEchoLevel(s);
    }
void gambit::logsetup::setfile (std::string name)
change logfile name for all outputs
Definition at line 309 of file logcore.cpp.
Referenced by main().
{ logcore_imp::instance()->setfile_range(name); }
void gambit::logsetup::setfile_downto_DEBUG (std::string name)
change logfile name for all outputs of severity DEBUG or worse
Definition at line 323 of file logcore.cpp.
References sDEBUG.
{ logcore_imp::instance()->setfile_range(name,sDEBUG,INT_MAX); }
void gambit::logsetup::setfile_downto_ERROR (std::string name)
change logfile name for all outputs of severity ERROR or worse
Definition at line 329 of file logcore.cpp.
References sERROR.
{ logcore_imp::instance()->setfile_range(name,sERROR,INT_MAX); }
void gambit::logsetup::setfile_downto_INFO (std::string name)
change logfile name for all outputs of severity INFO or worse
Definition at line 325 of file logcore.cpp.
References sINFO.
{ logcore_imp::instance()->setfile_range(name,sINFO,INT_MAX); }
void gambit::logsetup::setfile_downto_LOG (std::string name)
change logfile name for all outputs of severity LOG or worse
Definition at line 321 of file logcore.cpp.
References sLOG.
{ logcore_imp::instance()->setfile_range(name,sLOG,INT_MAX); }
void gambit::logsetup::setfile_downto_WARNING (std::string name)
change logfile name for all outputs of severity WARNING or worse
Definition at line 327 of file logcore.cpp.
References sWARNING.
{ logcore_imp::instance()->setfile_range(name,sWARNING,INT_MAX); }
void gambit::logsetup::setfile_range (std::string name, int lowedge, int highedge)
change logfile name for all outputs from severity lowedge to and including highedge
Definition at line 305 of file logcore.cpp.
{
      logcore_imp::instance()->_setfile_range(name, lowedge,highedge);
    }
void gambit::logsetup::setfile_upto_DEBUG (std::string name, unsigned int deblevel)
change logfile name for all outputs of severity DEBUG or less important
Definition at line 313 of file logcore.cpp.
Referenced by main().
{ logcore_imp::instance()->setfile_range(name,INT_MIN,-abs(deblevel)); }
void gambit::logsetup::setfile_upto_ERROR (std::string name)
change logfile name for all outputs of severity ERROR or less important
Definition at line 319 of file logcore.cpp.
References sERROR.
{ logcore_imp::instance()->setfile_range(name,INT_MIN,sERROR); }
void gambit::logsetup::setfile_upto_INFO (std::string name)
change logfile name for all outputs of severity INFO or less important
Definition at line 315 of file logcore.cpp.
References sINFO.
{ logcore_imp::instance()->setfile_range(name,INT_MIN,sINFO); }
void gambit::logsetup::setfile_upto_LOG (std::string name)
change logfile name for all outputs of severity LOG orb less important
Definition at line 311 of file logcore.cpp.
References sLOG.
Referenced by main().
{ logcore_imp::instance()->setfile_range(name,INT_MIN,sLOG); }
void gambit::logsetup::setfile_upto_WARNING (std::string name)
change logfile name for all outputs of severity WARNING or less important
Definition at line 317 of file logcore.cpp.
References sWARNING.
{ logcore_imp::instance()->setfile_range(name,INT_MIN,sWARNING); }
void gambit::logsetup::setLogLevel (int s)
Definition at line 296 of file logcore.cpp.
{
      logcore_imp::instance()->_setLogLevel(s);
    }
void gambit::logsetup::setLogLevel (severity_t s)
set log level for writing to files
Definition at line 293 of file logcore.cpp.
Referenced by main().
{
      logcore_imp::instance()->_setLogLevel(s);
    }
std::string gambit::logsetup::stacktrace () throw ()
Generate string containing stacktrace.
get strcktrace string of current state
Date:
2011 Aug 23
Author:
Johan Lundberg
Definition at line 199 of file logcore.cpp.
References demangle_traceline().
Referenced by gambit::exceptions::i_trace_do().
{
      std::stringstream result;
      void *array[25]; // up to 25 calls deep
      size_t size;
      size = backtrace(array, 25);
      // print out all the frames:
      char ** symbols=0;
      try{
        if((symbols=backtrace_symbols(array, size))){
          for (unsigned int i=0;i<size;i++){
            result<<"@:"<<i<< " "<<demangle_traceline(symbols[i]);
            if(i+1<size) result<<std::endl;
          }
        }
      }catch(...){ }
      if(symbols) {
        std::free(symbols);
        return result.str();
      }else{
        std::cerr<<"logcore.cpp: stacktrace method failed. Going on anyway"<<std::endl;
        return "(Stack Trace Failed). "+result.str();
      }
    }