GAMBIT: gambit::exceptions Namespace Reference
gambit::exceptions Namespace Reference
gambit exceptions
Classes
class gambit_exception_base
gambit exception base class
class e_configuration
configuraton exception
class e_incalculable
incalculable exception
class e_unphysical
unphysical exception
class e_limitation
unphysical exception
Typedefs
typedef boost::error_info
< struct
tag_gambit_exception_info,
std::string > i_text
object for adding a text description to a thrown boost exception
typedef boost::error_info
< struct
tag_gambit_exception_trace,
std::string > i_trace
object for adding a stacktrace (as text) to a thrown boost exception
Functions
i_trace i_trace_do () throw ()
function returning an i_trace object containing the current stacktrace
std::string get_exception_origin (boost::exception const &e)
extract exception origin (file, function, line number)
std::string get_exception_trace (boost::exception const &e)
extract detailed backtrace, as stored with the i_trace type
std::string get_exception_text (boost::exception const &e)
extract exception text as stored with the i_text type
std::string get_exception_name (boost::exception const &e)
std::string get_exception_dump (boost::exception const &e, unsigned int level=0)
extract full details from exception.
template<class T >
void Compiletime_Cast_Test (T const &)
Method for compile time test of type. If cast does not work, it does not compile compiles if there is any conversion is possible.
Detailed Description
gambit exceptions
gambit static/public exception related methods and classes.
Note that the throwing macro GAMBIT_THROW_EXCEPTION(e) is also defined in exceptions.hpp. Please read its documentation first.
Author:
Johan Lundberg
Date:
2011 Aug
Typedef Documentation
typedef boost::error_info<struct tag_gambit_exception_info,std::string> gambit::exceptions::i_text
object for adding a text description to a thrown boost exception
Definition at line 104 of file exceptions.hpp.
typedef boost::error_info<struct tag_gambit_exception_trace,std::string> gambit::exceptions::i_trace
object for adding a stacktrace (as text) to a thrown boost exception
Definition at line 106 of file exceptions.hpp.
Function Documentation
template<class T > void gambit::exceptions::Compiletime_Cast_Test (T const &) [inline]
Method for compile time test of type. If cast does not work, it does not compile compiles if there is any conversion is possible.
example: Compiletime_Cast_Test<std::string>(32) fails to compile Compiletime_Cast_Test<std::string>("hello") compiles Compiletime_Cast_Test<SomeBaseClass>(SomeDerivedClass()) compiles Compiletime_Cast_Test<SomeBaseClass>(SomeBaseClass) compiles
This is probably only useful in macros where there's no type information available.
Definition at line 120 of file exceptions.hpp.
{} // this is the whole thing.
std::string gambit::exceptions::get_exception_dump (boost::exception const & e, unsigned int level = 0)
extract full details from exception.
detail levels:
0: type and message text 1: also source file, function, line nr 2: also stack trace 3: also full dump of internal exception object data
a raw dump using boost methods is also included.
Definition at line 51 of file exceptions.cpp.
References get_exception_origin(), get_exception_text(), and get_exception_trace().
Referenced by main().
{
      std::stringstream out;
      bool needendl=0;
      std::string tmp;
      if(const gambit_exception_base *tmp=dynamic_cast<const gambit_exception_base*>(&e)){
        out<<tmp->getName();
        needendl=1;
      }
      tmp=get_exception_text(e);
      if(!tmp.empty()) {
        if(needendl) out<<std::endl;
        out<<tmp;
        needendl=1;
      }
      if(detail>0){
        tmp=get_exception_origin(e);
        if(!tmp.empty()) {
          if(needendl) out<<std::endl;
          out<<tmp;
          needendl=1;
        }
      }
      if(detail>1){
        tmp=get_exception_trace(e);
        if(!tmp.empty()) {
          if(needendl) out<<std::endl;
          out<<tmp;
          needendl=1;
        }
      }
      if(detail>2){
        if(needendl) out<<std::endl;
        out<<tmp;
        out<<"full diagnostic dump:"<<boost::diagnostic_information(e);
      }
      return out.str();
    }
std::string gambit::exceptions::get_exception_name (boost::exception const & e)
Definition at line 45 of file exceptions.cpp.
{
      if( std::string const * mi=boost::get_error_info<i_text>(e) )
        return *mi;
      return std::string("");
    }
std::string gambit::exceptions::get_exception_origin (boost::exception const & e)
extract exception origin (file, function, line number)
or empty string if not available
Definition at line 21 of file exceptions.cpp.
Referenced by GAMBIT::dict::get(), get_exception_dump(), and GAMBIT::dict::set().
{
      std::stringstream tmp;
      if ( char const*const *mi =boost::get_error_info<boost::throw_file>(e) ) {
        tmp<<std::string(*mi);
      }
      if ( int const* mi =boost::get_error_info<boost::throw_line>(e) ) {
        tmp<<"#"<<int(*mi)<<" ";
      }
      if ( char const*const *mi =boost::get_error_info<boost::throw_function>(e) ) {
        tmp<<std::string(*mi);
      }
      return tmp.str();
    }
std::string gambit::exceptions::get_exception_text (boost::exception const & e)
extract exception text as stored with the i_text type
or empty string if not available
Definition at line 40 of file exceptions.cpp.
Referenced by GAMBIT::dict::get(), get_exception_dump(), and GAMBIT::dict::set().
{
      if( std::string const * mi=boost::get_error_info<i_text>(e) )
        return *mi;
      return std::string("");
    }
std::string gambit::exceptions::get_exception_trace (boost::exception const & e)
extract detailed backtrace, as stored with the i_trace type
or empty string if not available
Definition at line 35 of file exceptions.cpp.
Referenced by get_exception_dump().
{
      if( std::string const * mi=boost::get_error_info<i_trace>(e) )
        return *mi;
      return std::string("");
    }
i_trace gambit::exceptions::i_trace_do () throw ()
function returning an i_trace object containing the current stacktrace
Example use:
 using namespace gambit::exceptions;
 GAMBIT_THROW_EXCEPTION(e_unphysical << i_trace_do() << i_text("mass is negative"));
Definition at line 17 of file exceptions.cpp.
References gambit::logsetup::stacktrace().
{
      return i_trace(logsetup::stacktrace());
    }