GAMBIT: GAMBIT::ExampleBit_A Namespace Reference
GAMBIT::ExampleBit_A Namespace Reference
Functions
void initialize ()
void nevents_dbl (double &result)
void nevents_int (int &result)
void nevents_like (double &result)
void identity (str &result)
Variables
double count = 3.5
Function Documentation
void GAMBIT::ExampleBit_A::identity (str & result)
Definition at line 47 of file ExampleBit_A.cpp.
Referenced by main().
{ result = "turkion"; }
void GAMBIT::ExampleBit_A::initialize ()
Definition at line 35 of file ExampleBit_A.cpp.
Referenced by BE_F_VARIABLE().
    {
      std::cout << std::endl;
      std::cout << "********************************************" << std::endl;
      std::cout << "***       Initializing ExampleBit_A      ***" << std::endl;
      std::cout << "********************************************" << std::endl;
    }
void GAMBIT::ExampleBit_A::nevents_dbl (double & result)
Definition at line 44 of file ExampleBit_A.cpp.
References count.
{ result = count++; }
void GAMBIT::ExampleBit_A::nevents_int (int & result)
Definition at line 45 of file ExampleBit_A.cpp.
References GET_DEP, and GAMBIT::ExampleBit_B::nevents().
{ result = (int) (GET_DEP(nevents_int::nevents)); }
void GAMBIT::ExampleBit_A::nevents_like (double & result)
Definition at line 46 of file ExampleBit_A.cpp.
Referenced by main().
{ result = 1.5; }
Variable Documentation
double GAMBIT::ExampleBit_A::count = 3.5
Definition at line 32 of file ExampleBit_A.cpp.
Referenced by nevents_dbl().