GAMBIT: GAMBIT::Graphs Namespace Reference
GAMBIT::Graphs Namespace Reference
Classes
struct Edge
Typedefs
typedef adjacency_list< vecS,
vecS, directedS, functor
*, Edge > MasterGraphType
typedef graph_traits
< MasterGraphType >
::vertex_descriptor VertexID
typedef graph_traits
< MasterGraphType >
::edge_descriptor EdgeID
Functions
void fill_parQueue (queue< pair< sspair, Graphs::VertexID > > *parQueue, Graphs::VertexID vertex)
multimap< sspair,
Graphs::VertexID > initialize_capMap ()
void initialize_edges (queue< pair< sspair, Graphs::VertexID > > parQueue, multimap< sspair, Graphs::VertexID > capMap)
list< int > run_topological_sort ()
void list_functions (list< int > topo_order)
void execute_functions (list< int > topo_order)
void execute_functions ()
void list_graphs_content ()
void dependency_resolution (std::vector< int > &pars)
Variables
list< int > function_order
MasterGraphType masterGraph
Typedef Documentation
typedef graph_traits<MasterGraphType>::edge_descriptor GAMBIT::Graphs::EdgeID
Definition at line 52 of file graphs.hpp.
typedef adjacency_list<vecS, vecS, directedS, functor*, Edge> GAMBIT::Graphs::MasterGraphType
Definition at line 50 of file graphs.hpp.
typedef graph_traits<MasterGraphType>::vertex_descriptor GAMBIT::Graphs::VertexID
Definition at line 51 of file graphs.hpp.
Function Documentation
void GAMBIT::Graphs::dependency_resolution (std::vector< int > & pars)
Definition at line 161 of file graphs.cpp.
References fill_parQueue(), function_order, initialize_capMap(), initialize_edges(), list_functions(), list_graphs_content(), masterGraph, and run_topological_sort().
Referenced by main().
    {
      list_graphs_content();
      queue<pair<sspair, Graphs::VertexID> > parQueue;
      multimap<sspair, Graphs::VertexID> capMap;
      capMap = initialize_capMap();
      for (std::vector<int>::iterator it = pars.begin() ; it != pars.end(); ++it)
      {
        fill_parQueue(&parQueue, vertex(*it, Graphs::masterGraph));
      }
      initialize_edges(parQueue, capMap);
      function_order = run_topological_sort();
      list_functions(function_order);
    };
void GAMBIT::Graphs::execute_functions (list< int > topo_order)
Definition at line 130 of file graphs.cpp.
References masterGraph.
Referenced by execute_functions(), and main().
{
      cout << "Dependency resolver says: now I will actually run them." << endl;
      for(list<int>::const_iterator i = topo_order.begin();
          i != topo_order.end();
          ++i)
      {
        if ( (*Graphs::masterGraph[*i]).status() == 2 )
        {
          (*Graphs::masterGraph[*i]).calculate();
        }
      }
    }
void GAMBIT::Graphs::execute_functions ()
Definition at line 144 of file graphs.cpp.
References execute_functions(), and function_order.
{ execute_functions(function_order); }
void GAMBIT::Graphs::fill_parQueue (queue< pair< sspair, Graphs::VertexID > > * parQueue, Graphs::VertexID vertex)
Definition at line 36 of file graphs.cpp.
References masterGraph.
Referenced by dependency_resolution(), and initialize_edges().
{
      (*Graphs::masterGraph[vertex]).setStatus(2);
      cout << "Adding " << (*Graphs::masterGraph[vertex]).name()
        << " to parameter queue, with dependencies" << endl;
      vector<sspair> vec = (*Graphs::masterGraph[vertex]).dependencies();
      for (vector<sspair>::iterator it = vec.begin(); it != vec.end(); ++it) {
        cout << "  " << (*it).first << " (" << (*it).second << ")" << endl;
        (*parQueue).push(*(new pair<sspair, Graphs::VertexID> (*it, vertex)));
      }
    }
multimap<sspair, Graphs::VertexID> GAMBIT::Graphs::initialize_capMap ()
Definition at line 49 of file graphs.cpp.
References masterGraph.
Referenced by dependency_resolution().
{
      cout << endl << "Filling capability map with" << endl;
      multimap<sspair, Graphs::VertexID> capMap;
      graph_traits<Graphs::MasterGraphType>::vertex_iterator vi, vi_end;
      pair<sspair, Graphs::VertexID> ins;
      for (tie(vi, vi_end) = vertices(Graphs::masterGraph); vi != vi_end; ++vi) {
        ins.first.first = (*Graphs::masterGraph[*vi]).capability();
        ins.first.second = (*Graphs::masterGraph[*vi]).type();
        ins.second = *vi;
        cout << "  " << ins.first.first << " (" << ins.first.second << ")" << endl;
        capMap.insert(ins);
      };
      return capMap;
    }
void GAMBIT::Graphs::initialize_edges (queue< pair< sspair, Graphs::VertexID > > parQueue, multimap< sspair, Graphs::VertexID > capMap)
Definition at line 71 of file graphs.cpp.
References fill_parQueue(), and masterGraph.
Referenced by dependency_resolution().
{
      cout << endl << "Setting up edges/dependencies:" << endl;
      int key_multiplicity;
      bool ok;
      Graphs::VertexID fromVertex, toVertex;
      sspair var;
      Graphs::EdgeID current_edge;
      while (not parQueue.empty()) {
        var = parQueue.front().first;
        toVertex = parQueue.front().second;
        cout << var.first << " (" << var.second << ")" << ": ";
        key_multiplicity = capMap.count(var);
        if ( key_multiplicity == 0 ) {
          cout << "Cannot resolve dependency." << endl;
          cout << "---> QUIT" << endl;
        }
        if ( key_multiplicity > 1 ) {
          cout << "Non-unique dependency resolution." << endl;
          // TODO: Dependency resolution
          exit(0);
        }
        fromVertex = (*capMap.find(var)).second;
        cout << "resolved." << endl;
        if ( (*Graphs::masterGraph[fromVertex]).status() != 2 ) {
          fill_parQueue(&parQueue, fromVertex);
        }
        cout << "Adding edge: ";
        cout << (*Graphs::masterGraph[fromVertex]).name() << " --> ";
        cout << (*Graphs::masterGraph[toVertex]).name() << endl;
        tie(current_edge, ok) = add_edge(fromVertex, toVertex, Graphs::masterGraph);
        (*Graphs::masterGraph[toVertex]).resolveDependency(Graphs::masterGraph[fromVertex]);
        Graphs::masterGraph[current_edge].variable = var;
        parQueue.pop();
      }
      cout << endl;
    }
void GAMBIT::Graphs::list_functions (list< int > topo_order)
Definition at line 116 of file graphs.cpp.
References masterGraph.
Referenced by dependency_resolution().
{
      cout << "Dependency resolver says:  I will run the module functions in this order (and only the active ones):" << endl;
      for(list<int>::const_iterator i = topo_order.begin();
          i != topo_order.end();
          ++i)
      {
        cout << "  " << (*Graphs::masterGraph[*i]).name() ;
        if ( (*Graphs::masterGraph[*i]).status() == 0 ) cout << " (disabled)" << endl;
        if ( (*Graphs::masterGraph[*i]).status() == 1 ) cout << " (available)" << endl;
        if ( (*Graphs::masterGraph[*i]).status() == 2 ) cout << " (ACTIVE)" << endl;
      }
    }
void GAMBIT::Graphs::list_graphs_content ()
Definition at line 147 of file graphs.cpp.
References masterGraph.
Referenced by dependency_resolution().
    {
      graph_traits<Graphs::MasterGraphType>::vertex_iterator vi, vi_end;
      cout << "List of registered vertices" << endl;
      for (tie(vi, vi_end) = vertices(Graphs::masterGraph); vi != vi_end; ++vi) {
        cout << "  " << (*Graphs::masterGraph[*vi]).name() << endl;
        cout << "    Capability: " << (*Graphs::masterGraph[*vi]).capability();
        cout << " (" << (*Graphs::masterGraph[*vi]).type() << ")" << endl;
        cout << "    Module: " << (*Graphs::masterGraph[*vi]).origin();
        cout << " (" << (*Graphs::masterGraph[*vi]).version() << ")" << endl;
      };
    };
list<int> GAMBIT::Graphs::run_topological_sort ()
Definition at line 109 of file graphs.cpp.
References masterGraph.
Referenced by dependency_resolution().
{
      list<int> topo_order;
      topological_sort(Graphs::masterGraph, front_inserter(topo_order));
      return topo_order;
    }
Variable Documentation
list<int> GAMBIT::Graphs::function_order
Definition at line 33 of file graphs.cpp.
Referenced by dependency_resolution(), and execute_functions().
MasterGraphType GAMBIT::Graphs::masterGraph
Definition at line 60 of file graphs.hpp.
Referenced by dependency_resolution(), execute_functions(), fill_parQueue(), initialize_capMap(), initialize_edges(), list_functions(), list_graphs_content(), and run_topological_sort().