GAMBIT: GAMBIT::PID Namespace Reference
GAMBIT::PID Namespace Reference
Functions
bool isGenSpecific (int pid)
Determine if the PID is in the generator-specific range.
bool isResonance (int pid)
Determine if the PID is that of an EW scale resonance.
bool isTransportable (int pid)
Check the PID for usability in transport codes like Geant4.
General PID-based classifier functions
bool isCharged (int pid)
Determine if the particle is electrically charged.
bool isNeutral (int pid)
Determine if the particle is electrically neutral.
Fundamental particles
bool isQuark (int pid)
Determine if the PID is that of a quark.
bool isParton (int pid)
Determine if the PID is that of a parton (quark or gluon)
bool isPhoton (int pid)
Determine if the PID is that of a photon.
bool isWplus (int pid)
Determine if the PID is that of a W+.
bool isWminus (int pid)
Determine if the PID is that of a W-.
bool isW (int pid)
Determine if the PID is that of a W+-.
bool isZ (int pid)
Determine if the PID is that of a Z0.
bool isHiggs (int pid)
Determine if the PID is that of an SM/lightest SUSY Higgs.
bool isTop (int pid)
Determine if the PID is that of a t/tbar.
Hadrons
bool isHeavyHadron (int pid)
Determine if the PID is that of a heavy flavour (b or c) hadron.
bool isStrangeHadron (int pid)
Determine if the PID is that of a strange hadron.
bool isLightHadron (int pid)
Determine if the PID is that of a light flavour (not b or c) hadron.
bool isBMeson (int pid)
Determine if the PID is that of a b-meson.
bool isBBaryon (int pid)
Determine if the PID is that of a b-baryon.
bool isBHadron (int pid)
Determine if the PID is that of a b-hadron.
bool isCMeson (int pid)
Determine if the PID is that of a c-meson.
bool isCBaryon (int pid)
Determine if the PID is that of a c-baryon.
bool isCHadron (int pid)
Determine if the PID is that of a c-hadron.
Functions taken from HepPID/Rivet
enum Location {
nj = 1, nq3, nq2, nq1,
nl, nr, n, n8,
n9, n10
}
PID digits (base 10) are: n nr nl nq1 nq2 nq3 nj The Location enum provides a convenient index into the PID.
unsigned short digit (Location loc, const int &pid)
return the digit at a named location in the PID
int fundamentalID (const int &pid)
extract fundamental ID (1-100) if this is a "fundamental" particle
int extraBits (const int &pid)
if this is a fundamental particle, does it have a valid antiparticle?
int abspid (const int &pid)
bool isNucleus (const int &pid)
int Z (const int &pid)
int A (const int &pid)
int lambda (const int &pid)
bool isMeson (const int &pid)
bool isBaryon (const int &pid)
bool isDiQuark (const int &pid)
bool isPentaquark (const int &pid)
bool isHadron (const int &pid)
bool isLepton (const int &pid)
bool isSUSY (const int &pid)
bool isRhadron (const int &pid)
bool hasUp (const int &pid)
bool hasDown (const int &pid)
bool hasStrange (const int &pid)
bool hasCharm (const int &pid)
bool hasBottom (const int &pid)
bool hasTop (const int &pid)
bool isValid (const int &pid)
int jSpin (const int &pid)
int sSpin (const int &pid)
int lSpin (const int &pid)
int threeCharge (const int &pid)
double charge (const int &pid)
return the charge
Enumeration Type Documentation
enum GAMBIT::PID::Location
PID digits (base 10) are: n nr nl nq1 nq2 nq3 nj The Location enum provides a convenient index into the PID.
Enumerator:
nj
nq3
nq2
nq1
nl
nr
n
n8
n9
n10
Definition at line 18 of file PIDUtils.hpp.
{ nj=1, nq3, nq2, nq1, nl, nr, n, n8, n9, n10 };
Function Documentation
int GAMBIT::PID::A (const int & pid) [inline]
Definition at line 90 of file PIDUtils.hpp.
References abspid(), and isNucleus().
Referenced by main().
{
        // a proton can also be a Hydrogen nucleus
        if( abspid(pid) == 2212 ) { return 1; }
        if( isNucleus(pid) ) return (abspid(pid)/10)%1000;
        return 0;
    }
int GAMBIT::PID::abspid (const int & pid) [inline]
Definition at line 34 of file PIDUtils.hpp.
Referenced by A(), digit(), extraBits(), fundamentalID(), isBaryon(), isDiQuark(), isMeson(), isNucleus(), jSpin(), lambda(), threeCharge(), and Z().
{
      return (pid < 0) ? -pid : pid;
    }
double GAMBIT::PID::charge (const int & pid) [inline]
return the charge
Definition at line 455 of file PIDUtils.hpp.
References threeCharge().
Referenced by threeCharge().
{ return threeCharge(pid)/3.0; }
unsigned short GAMBIT::PID::digit (Location loc, const int & pid) [inline]
return the digit at a named location in the PID
Definition at line 44 of file PIDUtils.hpp.
References abspid().
Referenced by fundamentalID(), hasBottom(), hasCharm(), hasDown(), hasStrange(), hasTop(), hasUp(), isBaryon(), isCBaryon(), isCMeson(), isDiQuark(), isMeson(), isNucleus(), isPentaquark(), isRhadron(), isSUSY(), lambda(), lSpin(), sSpin(), and threeCharge().
{
        //  PID digits (base 10) are: n nr nl nq1 nq2 nq3 nj (cf. Location)
        int numerator = (int) std::pow(10.0,(loc-1));
        return (abspid(pid)/numerator)%10;
    }
int GAMBIT::PID::extraBits (const int & pid) [inline]
if this is a fundamental particle, does it have a valid antiparticle?
returns everything beyond the 7th digit (e.g. outside the standard numbering scheme)
Definition at line 39 of file PIDUtils.hpp.
References abspid().
Referenced by fundamentalID(), hasBottom(), hasCharm(), hasDown(), hasStrange(), hasTop(), hasUp(), isBaryon(), isDiQuark(), isHadron(), isLepton(), isMeson(), isPentaquark(), isRhadron(), isSUSY(), isValid(), jSpin(), and threeCharge().
{
        return abspid(pid)/10000000;
    }
int GAMBIT::PID::fundamentalID (const int & pid) [inline]
extract fundamental ID (1-100) if this is a "fundamental" particle
Definition at line 52 of file PIDUtils.hpp.
References abspid(), digit(), extraBits(), nq1, and nq2.
Referenced by hasBottom(), hasCharm(), hasDown(), hasStrange(), hasTop(), hasUp(), isBaryon(), isDiQuark(), isLepton(), isMeson(), isSUSY(), isValid(), jSpin(), and threeCharge().
{
        if( extraBits(pid) > 0 ) return 0;
        if( digit(nq2,pid) == 0 && digit(nq1,pid) == 0) {
            return abspid(pid)%10000;
        } else if( abspid(pid) <= 100 ) {
            return abspid(pid);
        } else {
            return 0;
        }
    }
bool GAMBIT::PID::hasBottom (const int & pid) [inline]
Definition at line 267 of file PIDUtils.hpp.
References digit(), extraBits(), fundamentalID(), nq1, nq2, and nq3.
Referenced by GAMBIT::fromBottom(), isBBaryon(), isBHadron(), isBMeson(), GAMBIT::isFinalB(), isHeavyHadron(), and isLightHadron().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( fundamentalID(pid) > 0 ) { return false; }
        if( digit(nq3,pid) == 5 || digit(nq2,pid) == 5 || digit(nq1,pid) == 5 ) { return true; }
        return false;
    }
bool GAMBIT::PID::hasCharm (const int & pid) [inline]
Definition at line 260 of file PIDUtils.hpp.
References digit(), extraBits(), fundamentalID(), nq1, nq2, and nq3.
Referenced by isHeavyHadron(), and isLightHadron().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( fundamentalID(pid) > 0 ) { return false; }
        if( digit(nq3,pid) == 4 || digit(nq2,pid) == 4 || digit(nq1,pid) == 4 ) { return true; }
        return false;
    }
bool GAMBIT::PID::hasDown (const int & pid) [inline]
Definition at line 246 of file PIDUtils.hpp.
References digit(), extraBits(), fundamentalID(), nq1, nq2, and nq3.
{
        if( extraBits(pid) > 0 ) { return false; }
        if( fundamentalID(pid) > 0 ) { return false; }
        if( digit(nq3,pid) == 1 || digit(nq2,pid) == 1 || digit(nq1,pid) == 1 ) { return true; }
        return false;
    }
bool GAMBIT::PID::hasStrange (const int & pid) [inline]
Definition at line 253 of file PIDUtils.hpp.
References digit(), extraBits(), fundamentalID(), nq1, nq2, and nq3.
Referenced by isStrangeHadron().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( fundamentalID(pid) > 0 ) { return false; }
        if( digit(nq3,pid) == 3 || digit(nq2,pid) == 3 || digit(nq1,pid) == 3 ) { return true; }
        return false;
    }
bool GAMBIT::PID::hasTop (const int & pid) [inline]
Definition at line 274 of file PIDUtils.hpp.
References digit(), extraBits(), fundamentalID(), nq1, nq2, and nq3.
{
        if( extraBits(pid) > 0 ) { return false; }
        if( fundamentalID(pid) > 0 ) { return false; }
        if( digit(nq3,pid) == 6 || digit(nq2,pid) == 6 || digit(nq1,pid) == 6 ) { return true; }
        return false;
    }
bool GAMBIT::PID::hasUp (const int & pid) [inline]
Definition at line 239 of file PIDUtils.hpp.
References digit(), extraBits(), fundamentalID(), nq1, nq2, and nq3.
{
        if( extraBits(pid) > 0 ) { return false; }
        if( fundamentalID(pid) > 0 ) { return false; }
        if( digit(nq3,pid) == 2 || digit(nq2,pid) == 2 || digit(nq1,pid) == 2 ) { return true; }
        return false;
    }
bool GAMBIT::PID::isBaryon (const int & pid) [inline]
Definition at line 147 of file PIDUtils.hpp.
References abspid(), digit(), extraBits(), fundamentalID(), nj, nq1, nq2, and nq3.
Referenced by isBBaryon(), isCBaryon(), isHadron(), isValid(), and threeCharge().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( abspid(pid) <= 100 ) { return false; }
        if( fundamentalID(pid) <= 100 && fundamentalID(pid) > 0 ) { return false; }
        if( abspid(pid) == 2110 || abspid(pid) == 2210 ) { return true; }
        if(    digit(nj,pid) > 0  && digit(nq3,pid) > 0
            && digit(nq2,pid) > 0 && digit(nq1,pid) > 0 ) { return true; }
        return false;
    }
bool GAMBIT::PID::isBBaryon (int pid) [inline]
Determine if the PID is that of a b-baryon.
Definition at line 551 of file PIDUtils.hpp.
References hasBottom(), and isBaryon().
{
          return hasBottom(pid) && isBaryon(pid);
        }
bool GAMBIT::PID::isBHadron (int pid) [inline]
Determine if the PID is that of a b-hadron.
Definition at line 556 of file PIDUtils.hpp.
References hasBottom(), and isHadron().
{
          return hasBottom(pid) && isHadron(pid);
        }
bool GAMBIT::PID::isBMeson (int pid) [inline]
Determine if the PID is that of a b-meson.
Definition at line 546 of file PIDUtils.hpp.
References hasBottom(), and isMeson().
{
          return hasBottom(pid) && isMeson(pid);
        }
bool GAMBIT::PID::isCBaryon (int pid) [inline]
Determine if the PID is that of a c-baryon.
Specifically, the _heaviest_ quark is a c: a baryon containing a b & c is a b-baryon and NOT a c-baryon. To test for the simpler case, just use a combination of hasCharm() and isBaryon().
Definition at line 573 of file PIDUtils.hpp.
References digit(), isBaryon(), and nq1.
Referenced by isCHadron().
{
          return isBaryon(pid) && (digit(nq1,pid) == 4);
        }
bool GAMBIT::PID::isCHadron (int pid) [inline]
Determine if the PID is that of a c-hadron.
Definition at line 578 of file PIDUtils.hpp.
References isCBaryon(), and isCMeson().
{
          return isCMeson(pid) || isCBaryon(pid);
        }
bool GAMBIT::PID::isCharged (int pid) [inline]
Determine if the particle is electrically charged.
Definition at line 464 of file PIDUtils.hpp.
References threeCharge().
{
      return threeCharge(pid) != 0;
    }
bool GAMBIT::PID::isCMeson (int pid) [inline]
Determine if the PID is that of a c-meson.
Specifically, the _heaviest_ quark is a c: a B_c is a b-meson and NOT a c-meson. Charmonia (closed charm) are counted as c-mesons here.
Definition at line 564 of file PIDUtils.hpp.
References digit(), isMeson(), and nq2.
Referenced by isCHadron().
{
          return isMeson(pid) && (digit(nq2,pid) == 4);
        }
bool GAMBIT::PID::isDiQuark (const int & pid) [inline]
Definition at line 158 of file PIDUtils.hpp.
References abspid(), digit(), extraBits(), fundamentalID(), nj, nq1, nq2, and nq3.
Referenced by isValid(), and threeCharge().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( abspid(pid) <= 100 ) { return false; }
        if( fundamentalID(pid) <= 100 && fundamentalID(pid) > 0 ) { return false; }
        if(    digit(nj,pid) > 0  && digit(nq3,pid) == 0
            && digit(nq2,pid) > 0 && digit(nq1,pid) > 0 ) {  // diquark signature
           // EvtGen uses the diquarks for quark pairs, so, for instance,
           //   5501 is a valid "diquark" for EvtGen
           //if( digit(nj) == 1 && digit(nq2) == digit(nq1) ) {         // illegal
           //   return false;
           //} else {
              return true;
           //}
        }
        return false;
    }
bool GAMBIT::PID::isGenSpecific (int pid) [inline]
Determine if the PID is in the generator-specific range.
Definition at line 586 of file PIDUtils.hpp.
References GAMBIT::inRange().
{
      return inRange(pid, 80, 101);
    }
bool GAMBIT::PID::isHadron (const int & pid) [inline]
Definition at line 196 of file PIDUtils.hpp.
References extraBits(), isBaryon(), isMeson(), and isPentaquark().
Referenced by isBHadron(), isHeavyHadron(), isLightHadron(), isStrangeHadron(), and isTransportable().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( isMeson(pid) )   { return true; }
        if( isBaryon(pid) )  { return true; }
        if( isPentaquark(pid) ) { return true; }
        return false;
    }
bool GAMBIT::PID::isHeavyHadron (int pid) [inline]
Determine if the PID is that of a heavy flavour (b or c) hadron.
Definition at line 531 of file PIDUtils.hpp.
References hasBottom(), hasCharm(), and isHadron().
{
      return PID::isHadron(pid) && (PID::hasCharm(pid) || PID::hasBottom(pid));
    }
bool GAMBIT::PID::isHiggs (int pid) [inline]
Determine if the PID is that of an SM/lightest SUSY Higgs.
Definition at line 515 of file PIDUtils.hpp.
Referenced by isResonance().
{
      return pid == HIGGSBOSON || pid == 26; //< @todo Check on 26 still needed? (used in HERWIG SUSY, for example)
    }
bool GAMBIT::PID::isLepton (const int & pid) [inline]
Definition at line 204 of file PIDUtils.hpp.
References extraBits(), and fundamentalID().
Referenced by isTransportable().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( fundamentalID(pid) >= 11 && fundamentalID(pid) <= 18 ) { return true; }
        return false;
    }
bool GAMBIT::PID::isLightHadron (int pid) [inline]
Determine if the PID is that of a light flavour (not b or c) hadron.
Definition at line 541 of file PIDUtils.hpp.
References hasBottom(), hasCharm(), and isHadron().
{
      return PID::isHadron(pid) && !(PID::hasCharm(pid) || PID::hasBottom(pid));
    }
bool GAMBIT::PID::isMeson (const int & pid) [inline]
Definition at line 124 of file PIDUtils.hpp.
References abspid(), digit(), extraBits(), fundamentalID(), nj, nq1, nq2, and nq3.
Referenced by isBMeson(), isCMeson(), isHadron(), isValid(), lSpin(), sSpin(), and threeCharge().
{
        if( extraBits(pid) > 0 ) { return false; }
        if( abspid(pid) <= 100 ) { return false; }
        if( fundamentalID(pid) <= 100 && fundamentalID(pid) > 0 ) { return false; }
        int aid = abspid(pid);
        if( aid == 130 || aid == 310 || aid == 210 ) { return true; }
        // EvtGen uses some odd numbers
        if( aid == 150 || aid == 350 || aid == 510 || aid == 530 ) { return true; }
        // pomeron, etc.
        if( pid == 110 || pid == 990 || pid == 9990 ) { return true; }
        if(    digit(nj,pid) > 0 && digit(nq3,pid) > 0
            && digit(nq2,pid) > 0 && digit(nq1,pid) == 0 ) {
            // check for illegal antiparticles
            if( digit(nq3,pid) == digit(nq2,pid) && pid < 0 ) {
                return false;
            } else {
                return true;
            }
        }
        return false;
    }
bool GAMBIT::PID::isNeutral (int pid) [inline]
Determine if the particle is electrically neutral.
Definition at line 469 of file PIDUtils.hpp.
References threeCharge().
{
      return threeCharge(pid) == 0;
    }
bool GAMBIT::PID::isNucleus (const int & pid) [inline]
Definition at line 69 of file PIDUtils.hpp.
References abspid(), digit(), n10, and n9.
Referenced by A(), isValid(), lambda(), and Z().
{
         // a proton can also be a Hydrogen nucleus
         if( abspid(pid) == 2212 ) { return true; }
         // new standard: +/- 10LZZZAAAI
         if( ( digit(n10,pid) == 1 ) && ( digit(n9,pid) == 0 ) ) {
            // charge should always be less than or equal to baryon number
        // the following line is A >= Z
            if( (abspid(pid)/10)%1000 >= (abspid(pid)/10000)%1000 ) { return true; }
         }
         return false;
    }
bool GAMBIT::PID::isParton (int pid) [inline]
Determine if the PID is that of a parton (quark or gluon)
Definition at line 483 of file PIDUtils.hpp.
References isQuark().
{
      return pid == GLUON || isQuark(pid);
    }
bool GAMBIT::PID::isPentaquark (const int & pid) [inline]
Definition at line 176 of file PIDUtils.hpp.
References digit(), extraBits(), n, nj, nl, nq1, nq2, nq3, and nr.
Referenced by isHadron(), and isValid().
{
        // a pentaquark is of the form 9abcdej,
        // where j is the spin and a, b, c, d, and e are quarks
        if( extraBits(pid) > 0 ) { return false; }
        if( digit(n,pid) != 9 )  { return false; }
        if( digit(nr,pid) == 9 || digit(nr,pid) == 0 )  { return false; }
        if( digit(nj,pid) == 9 || digit(nl,pid) == 0 )  { return false; }
        if( digit(nq1,pid) == 0 )  { return false; }
        if( digit(nq2,pid) == 0 )  { return false; }
        if( digit(nq3,pid) == 0 )  { return false; }
        if( digit(nj,pid) == 0 )  { return false; }
        // check ordering
        if( digit(nq2,pid) > digit(nq1,pid) )  { return false; }
        if( digit(nq1,pid) > digit(nl,pid) )  { return false; }
        if( digit(nl,pid) > digit(nr,pid) )  { return false; }
        return true;
    }
bool GAMBIT::PID::isPhoton (int pid) [inline]
Determine if the PID is that of a photon.
Definition at line 488 of file PIDUtils.hpp.
Referenced by isTransportable().
{
      return pid == PHOTON;
    }
bool GAMBIT::PID::isQuark (int pid) [inline]
Determine if the PID is that of a quark.
Definition at line 478 of file PIDUtils.hpp.
References GAMBIT::inRange().
Referenced by isParton().
{
      return inRange(abs(pid), 1, 7);
    }
bool GAMBIT::PID::isResonance (int pid) [inline]
Determine if the PID is that of an EW scale resonance.
Todo:
Also include SUSY, technicolor, etc. etc.? Maybe via a isStandardModel(pid) function, but there are stable BSM particles (in principle)
Definition at line 593 of file PIDUtils.hpp.
References isHiggs(), isTop(), isW(), and isZ().
{
      return isW(pid) || isZ(pid) || isHiggs(pid) || isTop(pid);
    }
bool GAMBIT::PID::isRhadron (const int & pid) [inline]
Definition at line 223 of file PIDUtils.hpp.
References digit(), extraBits(), isSUSY(), n, nj, nq2, nq3, and nr.
Referenced by isValid().
{
        // an R-hadron is of the form 10abcdj,
        // where j is the spin and a, b, c, and d are quarks or gluons
        if( extraBits(pid) > 0 ) { return false; }
        if( digit(n,pid) != 1 )  { return false; }
        if( digit(nr,pid) != 0 )  { return false; }
        // make sure this isn't a SUSY particle
        if( isSUSY(pid) ) { return false; }
        // All R-hadrons have at least 3 core digits
        if( digit(nq2,pid) == 0 )  { return false; }
        if( digit(nq3,pid) == 0 )  { return false; }
        if( digit(nj,pid) == 0 )  { return false; }
        return true;
    }
bool GAMBIT::PID::isStrangeHadron (int pid) [inline]
Determine if the PID is that of a strange hadron.
Definition at line 536 of file PIDUtils.hpp.
References hasStrange(), and isHadron().
{
      return PID::isHadron(pid) && PID::hasStrange(pid);
    }
bool GAMBIT::PID::isSUSY (const int & pid) [inline]
Definition at line 212 of file PIDUtils.hpp.
References digit(), extraBits(), fundamentalID(), n, and nr.
Referenced by isRhadron(), and isValid().
{
        // fundamental SUSY particles have n = 1 or 2
        if( extraBits(pid) > 0 ) { return false; }
        if( digit(n,pid) != 1 && digit(n,pid) != 2 )  { return false; }
        if( digit(nr,pid) != 0 )  { return false; }
        // check fundamental part
        if( fundamentalID(pid) == 0 )  { return false; }
        return true;
    }
bool GAMBIT::PID::isTop (int pid) [inline]
Determine if the PID is that of a t/tbar.
Definition at line 520 of file PIDUtils.hpp.
Referenced by isResonance().
{
      return abs(pid) == 6;
    }
bool GAMBIT::PID::isTransportable (int pid) [inline]
Check the PID for usability in transport codes like Geant4.
Todo:
Should exclude neutrinos/LSP, since the ATLAS G4 interface deletes them immediately?
Definition at line 600 of file PIDUtils.hpp.
References isHadron(), isLepton(), and isPhoton().
{
      // return !isResonance(pid) && !isParton(pid) && !isGenSpecific(pid);
      return isPhoton(pid) || isHadron(pid) || isLepton(pid);
    }
bool GAMBIT::PID::isValid (const int & pid) [inline]
Definition at line 283 of file PIDUtils.hpp.
References extraBits(), fundamentalID(), isBaryon(), isDiQuark(), isMeson(), isNucleus(), isPentaquark(), isRhadron(), and isSUSY().
{
        if( extraBits(pid) > 0 ) {
            if( isNucleus(pid) )   { return true; }
            return false;
        }
        if( isSUSY(pid) ) { return true; }
        if( isRhadron(pid) ) { return true; }
        // Meson signature
        if( isMeson(pid) )   { return true; }
        // Baryon signature
        if( isBaryon(pid) )  { return true; }
        // DiQuark signature
        if( isDiQuark(pid) ) { return true; }
        // fundamental particle
        if( fundamentalID(pid) > 0 ) {
          if(pid > 0 ) {
            return true;
          } else {
            // AB - disabled this to remove need for PID -> name lookup.
            //if( hasFundamentalAnti(pid) ) { return true; }
            return false;
          }
        }
        // pentaquark
        if( isPentaquark(pid) ) { return true; }
        // don't recognize this number
        return false;
    }
bool GAMBIT::PID::isW (int pid) [inline]
Determine if the PID is that of a W+-.
Definition at line 505 of file PIDUtils.hpp.
Referenced by isResonance().
{
      return abs(pid) == WPLUSBOSON;
    }
bool GAMBIT::PID::isWminus (int pid) [inline]
Determine if the PID is that of a W-.
Definition at line 500 of file PIDUtils.hpp.
{
      return pid == WMINUSBOSON;
    }
bool GAMBIT::PID::isWplus (int pid) [inline]
Determine if the PID is that of a W+.
Todo:
Add isElectron, Muon, Tau (and +- specific versions?)... and is(Anti)Proton?
Definition at line 495 of file PIDUtils.hpp.
{
      return pid == WPLUSBOSON;
    }
bool GAMBIT::PID::isZ (int pid) [inline]
Determine if the PID is that of a Z0.
Definition at line 510 of file PIDUtils.hpp.
Referenced by isResonance().
{
      return pid == Z0BOSON;
    }
int GAMBIT::PID::jSpin (const int & pid) [inline]
Definition at line 316 of file PIDUtils.hpp.
References abspid(), extraBits(), and fundamentalID().
{
        if( fundamentalID(pid) > 0 ) {
        // some of these are known
        int fund = fundamentalID(pid);
        if( fund > 0 && fund < 7 ) return 2;
        if( fund == 9 ) return 3;
        if( fund > 10 && fund < 17 ) return 2;
        if( fund > 20 && fund < 25 ) return 3;
            return 0;
        } else if( extraBits(pid) > 0 ) {
            return 0;
        }
        return abspid(pid)%10;
    }
int GAMBIT::PID::lambda (const int & pid) [inline]
Definition at line 99 of file PIDUtils.hpp.
References abspid(), digit(), isNucleus(), and n8.
{
        // a proton can also be a Hydrogen nucleus
        if( abspid(pid) == 2212 ) { return 0; }
        if( isNucleus(pid) ) return digit(n8,pid);
        return 0;
    }
int GAMBIT::PID::lSpin (const int & pid) [inline]
Definition at line 355 of file PIDUtils.hpp.
References digit(), isMeson(), n, nj, and nl.
{
        if( !isMeson(pid) ) { return 0; }
        int inl = digit(nl,pid);
        //int tent = digit(n,pid);
        int js = digit(nj,pid);
        if( digit(n,pid) == 9 ) { return 0; }   // tentative ID
        if( inl == 0 && js == 3 ) {
            return 0;
        } else if( inl == 0 && js == 5 ) {
            return 1;
        } else if( inl == 0 && js == 7 ) {
            return 2;
        } else if( inl == 0 && js == 9 ) {
            return 3;
        } else if( inl == 0  && js == 1 ) {
            return 0;
        } else if( inl == 1  && js == 3 ) {
            return 1;
        } else if( inl == 1  && js == 5 ) {
            return 2;
        } else if( inl == 1  && js == 7 ) {
            return 3;
        } else if( inl == 1  && js == 9 ) {
            return 4;
        } else if( inl == 2  && js == 3 ) {
            return 1;
        } else if( inl == 2  && js == 5 ) {
            return 2;
        } else if( inl == 2  && js == 7 ) {
            return 3;
        } else if( inl == 2  && js == 9 ) {
            return 4;
        } else if( inl == 1  && js == 1 ) {
            return 1;
        } else if( inl == 3  && js == 3 ) {
            return 2;
        } else if( inl == 3  && js == 5 ) {
            return 3;
        } else if( inl == 3  && js == 7 ) {
            return 4;
        } else if( inl == 3  && js == 9 ) {
            return 5;
        }
        // default to zero
        return 0;
    }
int GAMBIT::PID::sSpin (const int & pid) [inline]
Definition at line 331 of file PIDUtils.hpp.
References digit(), isMeson(), n, nj, and nl.
{
        if( !isMeson(pid) ) { return 0; }
        int inl = digit(nl,pid);
        //int tent = digit(n,pid);
        int js = digit(nj,pid);
        if( digit(n,pid) == 9 ) { return 0; }   // tentative ID
        //if( tent == 9 ) { return 0; } // tentative assignment
        if( inl == 0 && js >= 3 ) {
            return 1;
        } else if( inl == 0  && js == 1 ) {
            return 0;
        } else if( inl == 1  && js >= 3 ) {
            return 0;
        } else if( inl == 2  && js >= 3 ) {
            return 1;
        } else if( inl == 1  && js == 1 ) {
            return 1;
        } else if( inl == 3  && js >= 3 ) {
            return 1;
        }
        // default to zero
        return 0;
    }
int GAMBIT::PID::threeCharge (const int & pid) [inline]
Definition at line 403 of file PIDUtils.hpp.
References abspid(), charge(), digit(), extraBits(), fundamentalID(), isBaryon(), isDiQuark(), isMeson(), nj, nq1, nq2, and nq3.
Referenced by charge(), isCharged(), and isNeutral().
{
        int charge=0;
        int ida, sid;
        unsigned short q1, q2, q3;
        static int ch100[100] = { -1, 2,-1, 2,-1, 2,-1, 2, 0, 0,
                           -3, 0,-3, 0,-3, 0,-3, 0, 0, 0,
                            0, 0, 0, 3, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 3, 0, 0, 3, 0, 0, 0,
                            0, -1, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 6, 3, 6, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
                            0, 0, 0, 0, 0, 0, 0, 0, 0, 0 };
        q1 = digit(nq1,pid);
        q2 = digit(nq2,pid);
        q3 = digit(nq3,pid);
        ida = abspid(pid);
        sid = fundamentalID(pid);
        if( ida == 0 || extraBits(pid) > 0 ) {      // ion or illegal
            return 0;
        } else if( sid > 0 && sid <= 100 ) {    // use table
            charge = ch100[sid-1];
            if(ida==1000017 || ida==1000018) { charge = 0; }
            if(ida==1000034 || ida==1000052) { charge = 0; }
            if(ida==1000053 || ida==1000054) { charge = 0; }
            if(ida==5100061 || ida==5100062) { charge = 6; }
        } else if( digit(nj,pid) == 0 ) {               // KL, Ks, or undefined
            return 0;
        } else if( isMeson(pid) ) {                     // mesons
                if( q2 == 3 || q2 == 5 ) {
                    charge = ch100[q3-1] - ch100[q2-1];
                } else {
                    charge = ch100[q2-1] - ch100[q3-1];
                }
        } else if( isDiQuark(pid) ) {                   // diquarks
            charge = ch100[q2-1] + ch100[q1-1];
        } else if( isBaryon(pid) ) {                    // baryons
            charge = ch100[q3-1] + ch100[q2-1] + ch100[q1-1];
        } else {                // unknown
            return 0;
        }
        if( charge == 0 ) {
            return 0;
        } else if( pid < 0 ) {
            charge = -charge;
        }
        return charge;
    }
int GAMBIT::PID::Z (const int & pid) [inline]
Definition at line 82 of file PIDUtils.hpp.
References abspid(), and isNucleus().
{
        // a proton can also be a Hydrogen nucleus
        if( abspid(pid) == 2212 ) { return 1; }
        if( isNucleus(pid) ) return (abspid(pid)/10000)%1000;
        return 0;
    }