GAMBIT: Utils/include/rngs.h File Reference
rngs.h File Reference
Functions
double Random (void)
void PlantSeeds (long x)
void GetSeed (long *x)
void PutSeed (long x)
void SelectStream (int index)
void TestRandom (void)
Function Documentation
void GetSeed (long * x)
Definition at line 132 of file rngs.c.
Referenced by TestRandom().
{
  *x = seed[stream];
}
void PlantSeeds (long x)
Definition at line 72 of file rngs.c.
References A256, MODULUS, PutSeed(), SelectStream(), and STREAMS.
Referenced by gambit::RandomScanner::RandomScanner(), SelectStream(), and TestRandom().
{
  const long Q = MODULUS / A256;
  const long R = MODULUS % A256;
        int  j;
        int  s;
  initialized = 1;
  s = stream;                            /* remember the current stream */
  SelectStream(0);                       /* change to stream 0          */
  PutSeed(x);                            /* set seed[0]                 */
  stream = s;                            /* reset the current stream    */
  for (j = 1; j < STREAMS; j++) {
    x = A256 * (seed[j - 1] % Q) - R * (seed[j - 1] / Q);
    if (x > 0)
      seed[j] = x;
    else
      seed[j] = x + MODULUS;
   }
}
void PutSeed (long x)
Definition at line 102 of file rngs.c.
References MODULUS.
Referenced by PlantSeeds(), and TestRandom().
{
  char ok = 0;
  if (x > 0)
    x = x % MODULUS;                       /* correct if x is too large  */
  if (x < 0)
    x = ((unsigned long) time((time_t *) NULL)) % MODULUS;
  if (x == 0)
    while (!ok) {
      printf("\nEnter a positive integer seed (9 digits or less) >> ");
      int tmpi=scanf("%ld", &x);
      ok = (0 < x) && (x < MODULUS);
      if (!ok){
         printf("\nInput out of range ... try again (%d)\n",tmpi);
      }
    }
  seed[stream] = x;
}
double Random (void)
Definition at line 52 of file rngs.c.
References MODULUS, and MULTIPLIER.
Referenced by TestRandom().
{
  const long Q = MODULUS / MULTIPLIER;
  const long R = MODULUS % MULTIPLIER;
        long t;
  t = MULTIPLIER * (seed[stream] % Q) - R * (seed[stream] / Q);
  if (t > 0)
    seed[stream] = t;
  else
    seed[stream] = t + MODULUS;
  return ((double) seed[stream] / MODULUS);
}
void SelectStream (int index)
Definition at line 143 of file rngs.c.
References DEFAULT, PlantSeeds(), and STREAMS.
Referenced by PlantSeeds(), and TestRandom().
{
  stream = ((unsigned int) index) % STREAMS;
  if ((initialized == 0) && (stream != 0))   /* protect against        */
    PlantSeeds(DEFAULT);                     /* un-initialized streams */
}
void TestRandom (void)
Definition at line 156 of file rngs.c.
References A256, CHECK, GetSeed(), PlantSeeds(), PutSeed(), Random(), and SelectStream().
{
  long   i;
  long   x;
  double u;
  char   ok = 0;
  SelectStream(0);                  /* select the default stream */
  PutSeed(1);                       /* and set the state to 1    */
  for(i = 0; i < 10000; i++)
    u = Random();
  GetSeed(&x);                      /* get the new state value   */
  ok = (x == CHECK);                /* and check for correctness */
  SelectStream(1);                  /* select stream 1                 */
  PlantSeeds(1);                    /* set the state of all streams    */
  GetSeed(&x);                      /* get the state of stream 1       */
  ok = ok && (x == A256);           /* x should be the jump multiplier */
  if (ok)
    printf("\n The implementation of rngs.c is correct.\n\n");
  else
    printf("\n\a ERROR -- the implementation of rngs.c is not correct.\n\n");
}