#! /usr/bin/env python

import numpy as np
from matplotlib import pyplot as plt

### TODO: Implement this psuedo-code:
for point in grid:
  for degree in threesixty:
    ray = (1000. * cos(degree), 1000. * sin(degree)) + point
    rmin = np.infty
    for segment in limitContours:
      intersection = ray.intersectsAt(segment)
      raydius = len(lineSegment(point, intersection))
      if raydius < rmin:
        ray = lineSegment(point, intersection)
        rmin = raydius
        # TODO: also, need to keep track of which xsec this ray intersects with
